doc/help/commands.asciidoc, qutebrowser/commands/runners.py
=> Registered 'search' as command.

qutebrowser/config/configdata.py
=> Commas are awesome.

qutebrowser/config/configtypes.py, qutebrowser/mainwindow/mainwindow.py
This is a continuation of pull request #239 and addresses issues #48.  Finally found time to get back to this.
All the manual testing that I did in my last pull request is working.  I believe that I addressed all of the points that you brought up in the pull request.  Some of them were done in a slightly different way than you suggested, but I do cover the functionality you recommended.  Think it is much improved.  Let me know what you think.
Also, for some reason pylint is erroring out when I run: run_checks.py.  I get:
ImportError: No module named 'pylint_checkers
I have python-pylint installed from AUR.  I also have it enabled in vim, so I don't expect any pylint errors, but I thought I would try to figure out why it isn't working.  Google and the docs didn't help me, but maybe I …
=> Confirm quit if downloads running

qutebrowser/completion/models/completion.py
This resolves #392.  Tested it with several different types of values.
=> Show default config value in completion

doc/INSTALL.asciidoc
https://github.com/voidlinux/void-packages/blob/master/srcpkgs/qutebrowser/template
=> INSTALL: instructions for Void Linux

qutebrowser/completion/models/completion.py
This fixes the problem outlined at the bottom of #458
=> Add quotes for empty default value

README.asciidoc, doc/help/commands.asciidoc, qutebrowser/browser/commands.py, qutebrowser/browser/downloads.py, qutebrowser/browser/downloadview.py, qutebrowser/config/configdata.py
This should address issue #449.
=> Download cmdline-interface improvement

qutebrowser/config/configdata.py, qutebrowser/config/configtypes.py, qutebrowser/mainwindow/mainwindow.py
I wanted the downloadview at the bottom of the window. So I added an option.
=> Added option for downloadview placement.

qutebrowser/config/configdata.py
=> Add Ctrl-M as keybind for command-accept

misc/userscripts/dmenu_qutebrowser, misc/userscripts/qutebrowser_viewsource
- Added misc/userscripts/dmenu_qutebrowser
- Added misc/userscripts/qutebrowser_viewsource
=> Add misc/userscripts

tests/javascript/base.html, tests/javascript/conftest.py, tests/javascript/position_caret/invisible.html, tests/javascript/position_caret/scrolled_down.html, tests/javascript/position_caret/scrolled_down_img.html, tests/javascript/position_caret/simple.html, tests/javascript/position_caret/test_position_caret.py
@hackebrot @nicoddemus If you have the time, a review would be appreciated!
This is quite sophisticated (at least I think so :wink:), but I definitely need tests for the javascript file as I don't feel comfortable with JS at all (yet?).
I wrote my own thing instead of using [oejskit](https://bitbucket.org/pedronis/js-infrastructure/) or [pytest-splinter](https://github.com/pytest-dev/pytest-splinter) (or others?) because I actually wanted the tests to run with a `QWebView` (and `QWebEngineView` at some point) and I wanted to implement the actual testing code in python.
=> Add javascript tests for position_caret.js.

tests/misc/test_crashdialog.py, tests/misc/test_lineparser.py, tests/utils/test_log.py, tests/utils/usertypes/test_enum.py, tests/utils/usertypes/test_neighborlist.py
This PR rewrites all remaining tests using `unittest.TestCase` to pytest.
Reviews appreciated, @hackebrot @nicoddemus! :smile:
=> Rewrite remaining tests to use pytest.

qutebrowser/browser/webview.py
Previously, it just said "Text not found" when you hit the bottom.
=> Give a better error when wrapping on search

qutebrowser/browser/commands.py, qutebrowser/config/configdata.py
This fixes the issue #401 allowing the user to press enter to navigate to a selected link.
This pull request needs some work to allow using the control key to open the link in a new tab.
=> [WIP] Fixed issue #401.

tests/misc/test_readline.py
They now use a real QLineEdit and verify a lot more.
@hackebrot @nicoddemus reviews appreciated!
I know, many tests are marked with `fixme` again - those are issues I discovered while testing, but I don't care about them right now, as they're minor details and there's more important stuff to do :wink:
=> Refactor readline tests.

doc/help/commands.asciidoc, qutebrowser/config/configdata.py, qutebrowser/keyinput/basekeyparser.py, qutebrowser/keyinput/modeman.py
This fixes #716, which sufficiently annoyed me to make this quick fix. It's not
a great fix, but it's not worse than what we had already, and the current
behaviour is very surprising IMHO.
=> Allow clearing the keychain

.travis.yml, tox.ini
Even with our own buildbot available, using Travis would be useful for PRs. This is a first attempt at getting that to run.
=> Use Travis/AppVeyor

.appveyor.yml, MANIFEST.in, qutebrowser/misc/crashsignal.py, qutebrowser/utils/log.py, scripts/appveyor_install.py, scripts/link_pyqt.py, tox.ini
It seems AppVeyor needs a separate PR to trigger a build.
=> Add appveyor config.

qutebrowser/utils/standarddir.py, qutebrowser/utils/utils.py, qutebrowser/utils/version.py, tests/utils/test_qtutils.py, tests/utils/test_standarddir.py, tests/utils/test_utils.py, tests/utils/test_version.py
This makes this four modules the first ones where I'm really happy with the tests and consider them done (and 100% test coverage of course!).
My goal currently is to do the same for the other utils modules, and then start with the rest and see when I feel like I've had enough :wink:
A review would be much appreciated, @nicoddemus @hackebrot - no hurry, and if you lack the time feel free to ignore. Thanks in advance!
=> Tests for qutebrowser.utils.{utils,version,standarddir,qtutils}

qutebrowser/completion/completer.py, qutebrowser/completion/completionwidget.py, qutebrowser/config/configdata.py
An (IMHO) cleaner version of #705.
@Carpetsmoker could you maybe test (and if you want code-review) this, and tell me if it does what you want it to?
Docstrings are still missing as I need to start work now :wink:
=> Add new completion -> auto-open option.

qutebrowser/utils/usertypes.py, tests/utils/usertypes/test_enum.py, tests/utils/usertypes/test_neighborlist.py, tests/utils/usertypes/test_question.py, tests/utils/usertypes/test_timer.py
And another module with perfect tests (IMHO)!
@nicoddemus the tests in `test_question.py` were the reason I wanted to have `waitSignals` and `raising=True` in `pytest-qt` :wink: A quick review would be nice, but it's pretty trivial stuff anyways :smile:
=> Improve/add tests for utils.usertypes

qutebrowser/utils/urlutils.py, tests/conftest.py, tests/utils/test_urlutils.py
And the last test refactoring/improvement PR I had lying around for weeks now but never finished. :smile:
@nicoddemus A quick review would be appreciated as there are some more sophisticated fixtures (`fake_dns` and `message_mock`).
=> Add/improve tests for qutebrowser.utils.urlutils.

INSTALL.asciidoc
As promised, here my pull request.
Unfortunately this does not work with CentOS yet.
=> Adding fedora installation guide

qutebrowser/browser/network/qutescheme.py, qutebrowser/mainwindow/tabbedbrowser.py, qutebrowser/mainwindow/tabwidget.py
=> Set favicon size to tabbar size.

qutebrowser/browser/downloads.py
@Carpetsmoker can you check how much of a difference this makes on your system?
Also, can you try increasing `REFRESH_TIMEOUT` to `1000` or so and see how much that changes.
I'd have thought this makes quite a difference, but it doesn't for me...
=> Batch download redrawings/updates.

qutebrowser/browser/downloads.py, qutebrowser/config/configdata.py
=> Added config option for prompting the user for a download location #277

qutebrowser/app.py, qutebrowser/misc/crashdialog.py
=> Show launch time in crash logs.

tests/config/test_config.py, tests/conftest.py, tests/keyinput/test_basekeyparser.py, tests/utils/test_qtutils.py, tests/utils/test_standarddir.py, tox.ini
=> Skip GUI tests when no DISPLAY is available.

qutebrowser/completion/completer.py, qutebrowser/completion/models/base.py, qutebrowser/completion/models/instances.py, qutebrowser/completion/models/sortfilter.py, qutebrowser/completion/models/urlmodel.py
=> Completion model filters are now per-window (via completer.py)

misc/userscripts/openfeeds
Add a userscript to open feed links from tags <link rel="related" type="application/rss+xml" href="..."> of a page.
=> Added userscript to open feed links.

qutebrowser/completion/models/urlmodel.py
This pull request fixes issue #934.
=> Fixed issue #934: History in Completion When web-history-max-items is 0

qutebrowser/config/configdata.py, qutebrowser/misc/crashdialog.py, tests/unit/misc/test_crashdialog.py
for #907
but i dont know, how i can test it.
=> Add env vars in crash report (#907)

doc/help/settings.asciidoc, qutebrowser/browser/commands.py, qutebrowser/config/configdata.py, qutebrowser/config/configtypes.py, qutebrowser/utils/urlutils.py, tests/unit/config/test_configtypes.py, tests/unit/utils/test_urlutils.py
...so you can chose which URL-segments will be used for `:navigate increment/decrement`. Valid values are comma-separated lists of `host`, `path`, `query` and `anchor`.
See #850 for further discussion about the increment/decrement algorithm.
=> Add a url-incdec-segments setting

qutebrowser/app.py, qutebrowser/mainwindow/mainwindow.py, qutebrowser/misc/ipc.py, qutebrowser/qutebrowser.py, tests/unit/misc/test_ipc.py
There it is, my first contribution to the qutebrowser code base! ;)
The implementation follows what we had discussed in #922.
=> Added --target command line argument #922

qutebrowser/browser/webview.py, qutebrowser/config/configdata.py, qutebrowser/mainwindow/statusbar/url.py
https://github.com/The-Compiler/qutebrowser/issues/691
made the enum value 'success-https' but that didn't quite work. 
I have confirmed this works locally, have not run tests.
=>  Issue #691

qutebrowser/browser/downloadview.py, qutebrowser/completion/completiondelegate.py, qutebrowser/completion/completionwidget.py, qutebrowser/config/style.py, qutebrowser/mainwindow/statusbar/bar.py, qutebrowser/mainwindow/statusbar/progress.py, qutebrowser/mainwindow/statusbar/url.py, tests/unit/config/test_style.py
ref: https://github.com/The-Compiler/qutebrowser/issues/928
=> [wip] ColorDict/FontDict hacks

qutebrowser/completion/completionwidget.py, qutebrowser/config/configdata.py, qutebrowser/config/style.py, tests/unit/config/test_style.py
This PR resolves merge conflicts with https://github.com/The-Compiler/qutebrowser/pull/1019.
=> Scrollbar style options.

www/qute.css
Just a simple design update for broken INSTALL.asciidoc file
=> Style changes

MANIFEST.in, scripts/asciidoc2html.py
This PR improves the website rendering part, it fixes the broken titles and the broken links.
=> Improved asciidoc2html script

qutebrowser/config/configdata.py
Closes #1117.
---
I figured there wasn't much in this? But if there is more to this, then feel free to reject this and do it yourself whenever you want as appropriate.
=> doc: Document <unbound> in keys.conf.

scripts/asciidoc2html.py
This PR adds `xyz | qutebrowser` titles to the website instead of `xyz` ones.
=> Improved website titles

www/header.asciidoc, www/qute.css
This PR fixes [some HTML syntax errors](http://validator.w3.org/check?uri=qutebrowser.org&charset=%28detect+automatically%29&doctype=Inline&group=0) on the website.
=> Fixed W3C Markup Validation Service errors

qutebrowser/browser/commands.py, qutebrowser/config/configdata.py
Pretty pointless to have an empty value there.
=> Disallow empty values in url-incdec-segments

qutebrowser/browser/webpage.py, qutebrowser/config/config.py, qutebrowser/config/configdata.py, tests/integration/features/keyinput.feature, tests/integration/features/misc.feature
And there it goes, the innocent little change ...
=> log-javascript-console -> [none, debug, info]

qutebrowser/browser/commands.py, tests/integration/features/tabs.feature
=> Wrap tabs on :tab-move +/- if tabs->wrap is true

pytest.ini, qutebrowser/browser/commands.py, tests/integration/features/caret.feature, tests/integration/features/conftest.py
=> Tests for caret mode fails on Windows and OS X

README.asciidoc, qutebrowser/browser/mhtml.py
MIMEMultipart is not needed for the attachements, a simple Message is
enough.
Also fix the README markup and the _start_download docstring.
=> Clean up mhtml doc and use email.message.Message

qutebrowser/config/configdata.py, qutebrowser/config/configtypes.py, qutebrowser/mainwindow/tabwidget.py, tests/unit/mainwindow/test_tabwidget.py
This pull request adds a config option to change the tab title alignment. 
Once again, thanks to The Compiler for all the help!
=> Added config option to change tab title alignment

qutebrowser/browser/hints.py
copied string format from `yank()` in `commands.py`
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1229)
=> issue 1213: Display yanked link in statusbar

INSTALL.asciidoc
bleh how do I words.
If you can word it / format it better, please do
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1227)
=> Mention chocolatey and packagemanagement/oneget

INSTALL.asciidoc
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1251)
=> Fix install instructions for OSX

qutebrowser/completion/completiondelegate.py, qutebrowser/completion/models/sortfilter.py
A possible fix to #133. It is not fuzzy (which I don't like too), but it enhances searching so it fullfills 100% of all my needs.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1195)
=> allow to narrow down search by adding more words separated with space

qutebrowser/utils/urlutils.py, tests/unit/utils/test_urlutils.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1253)
=> Include leading zeroes in URL increment/decrement

qutebrowser/app.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1277)
=> Use system icon for windows if available

CONTRIBUTING.asciidoc, doc/help/index.asciidoc, scripts/asciidoc2html.py
please review
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1300)
=> [WIP] Contributing toxhelp

tests/conftest.py
Simple fix for issue #1308, so I can test things again. Still, #1309 sound like a good idea.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1312)
=> fixes #1308

qutebrowser/misc/crashdialog.py, qutebrowser/utils/log.py
Hi, I'm new here. I wanted to start with something simple by resolving Issue#1230. Hope it's OK.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1301)
=> Added time to standard log

INSTALL.asciidoc
qutebrowser is finally fully pushed into stable repos, so voila!
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1327)
=> Updated installation instructions for Fedora.

qutebrowser/browser/commands.py, qutebrowser/utils/urlutils.py, tests/integration/features/yankpaste.feature, tests/unit/utils/test_urlutils.py
Hi,
I've implemented the heuristic to check if pasted text is a list of urls or paths and otherwise open it as a text.
I've been able to find why the test was failing (function in tests/integration/quteprocess.py) but I've seen that you changed it and now tests run correctly.
Cheers.
P.S. Sorry for the double pull request but I had a bad commit that I removed.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1325)
=> Multi url heuristic

misc/userscripts/password_fill
Add a configurable userscript that fills login forms (i.e. the fiels
"Username" and "Password) of websites using a configurable backend where
the actual passwords are stored. The only backend yet is using the
password store "pass".
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/873)
=> [WIP] Add password_fill userscript

INSTALL.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1363)
=> Add sound troubleshooting instructions for debian-based distros

qutebrowser/browser/commands.py, qutebrowser/config/configdata.py, tests/integration/data/title with spaces.html, tests/integration/features/yankpaste.feature
Add `--pretty` flag to `:yank`. About the {url} substitution part of the issue, something like the following
seems to work but I haven't been able to test it properly yet.
```diff
diff --git a/qutebrowser/commands/runners.py b/qutebrowser/commands/runners.py
index fbd7b1b..bca05d8 100644
--- a/qutebrowser/commands/runners.py
+++ b/qutebrowser/commands/runners.py
@@ -33,24 +33,33 @@ ParseResult = collections.namedtuple('ParseResult', ['cmd', 'args', 'cmdline',
'count'])
+def _current_url(tabbed_browser):
+    """Convenience method to get the current url."""
+    try:
+        return tabbed_browser.current_url()
+    except qtutils.QtValueError as e:
+        msg = "Current URL is invalid"
+        if e.reason:
+            msg += " ({})".format(e.reason)
+        msg += "!"
+        raise …
```
=> [WIP] Issue #1372

.gitignore, qutebrowser/browser/commands.py, tests/integration/features/navigate.feature
Now `:navigate up` clears the fragment in url
=> Fixes #1318

qutebrowser/mainwindow/tabbedbrowser.py
I wasn't able to repro it, but this should resolve #1454
=> Don't crash when setting mark on invalid url.

FAQ.asciidoc
Add description of umpv script.
=> Update 9. How do I play Youtube videos with mpv?

doc/quickstart.asciidoc
I would have found it useful if I had these few notes to start with. These are meant to be the most basic commands that everyone using qutebrowser will want to know.
=> Add basic commands to docs

doc/help/settings.asciidoc, qutebrowser/config/configdata.py
I don't think this is exactly a _great_ explanation, but its better than before.
=> Explain timeout vs partial-timeout better in docs.

qutebrowser/app.py
I hope this fixes the issue. I just moved some existing code in the existing object validation code.
No logs atm.
=> Possibly fixed issue: #1484

qutebrowser/browser/commands.py, tests/end2end/features/editor.feature
=> Only load with :edit-url if the URL was changed, remove count argument

doc/userscripts.asciidoc, misc/userscripts/dmenu_qutebrowser, misc/userscripts/open_download, misc/userscripts/qutebrowser_viewsource, misc/userscripts/qutedmenu, qutebrowser/commands/userscripts.py
A $QUTE_CONFIG_DIR variable with the location of the configuration dir, for #937.
=> Add $QUTE_CONFIG_DIR for userscripts (#937)

doc/help/settings.asciidoc, qutebrowser/config/configdata.py, qutebrowser/mainwindow/mainwindow.py
See #1257.
I can't think of a good way to do widget-packing because tabs can be on the left or right.
=> Add status-position option

qutebrowser/mainwindow/mainwindow.py
=> Stop downloads bar from pushing away status bar

qutebrowser/browser/commands.py, tests/end2end/features/urlmarks.feature
=> Allow adding bookmarks by url

qutebrowser/misc/earlyinit.py, qutebrowser/utils/log.py
Fix the failure caused by additional ssl warnings:
* Ignore QSslSocket: cannot resolve SSLv3_*_method
* Initialize logging as early as possible (or least as early as I think is possible)
=> Issue 1670 tests fail due to ssl error

qutebrowser/completion/completiondelegate.py, qutebrowser/completion/models/base.py, qutebrowser/completion/models/sortfilter.py
See https://github.com/The-Compiler/qutebrowser/issues/545#issuecomment-236116394 for the plan :wink:
=> Trivial completion fixes

CONTRIBUTING.asciidoc
I fixed some minor errors/odd wordings while I was reading the Contribution guidelines. Hopefully things will flow slightly better.
=> Fix minor errors and improve flow of text

misc/userscripts/rss
This is a simple userscript for keeping track of RSS feeds, adapted from https://github.com/blyxxyz/rsspew.
=> Add rss userscript

qutebrowser/browser/hints.py
This gets a few more useful keywords out of stuff like buttons and input fields.
=> Add more methods for extracting hint tags

qutebrowser/browser/hints.py, qutebrowser/config/configdata.py, tests/manual/hints/hide_unmatched_rapid_hints.html
Fixes #1799, unless someone would prefer to make this optional.
=> Suppress hiding hints in rapid mode

qutebrowser/config/configdata.py, qutebrowser/keyinput/basekeyparser.py, qutebrowser/keyinput/modeman.py, tests/unit/config/test_config.py
Fixes #1805
I don't see a good way to test this though, since I was unable to reproduce both scenarios from #1805 on the current master. Currently the best chance is probably [this failure](https://travis-ci.org/The-Compiler/qutebrowser/jobs/151506710#L293) from #1817.
=> keyinput: fix clearing keychain when leaving a mode

qutebrowser/browser/commands.py, tests/end2end/features/tabs.feature
=> Give error when trying to detach a single tab

CHANGELOG.asciidoc, qutebrowser/browser/commands.py, tests/end2end/features/backforward.feature, tests/end2end/features/conftest.py, tests/end2end/features/misc.feature, tests/end2end/features/tabs.feature, tests/end2end/features/test_tabs_bdd.py, tests/end2end/features/yankpaste.feature
Inspired by an IRC conversation about the overuse of "Given I have a fresh instance", I implemented this command to greatly cut down on the need for it, and did a quick pass through all of those usages to slim them down.
=> Add :window-only command

qutebrowser/config/configdata.py, tests/unit/config/test_config.py
=> Rewrite paste -s/pP

tests/end2end/features/hints.feature
Is it okay to leave it with that or also be tested that it defaults to letter hints afterwards?
=> Added test for empty dictionary

qutebrowser/misc/utilcmds.py, qutebrowser/utils/log.py
Pull request for issue :debug-loglevel should change the log format #1876
=> Add change format for debug-log-level cmd

qutebrowser/browser/webkit/webview.py
closes #1886 
Verified with [this demo](http://daniemon.com/tech/webapps/page-visibility/).
=> QtWebKit: Handle visibility API

README.asciidoc
Founder of shortcutFoo was impressed with Qutebrowser and made a free tutorial to help people memorize the key bindings.  <https://www.shortcutfoo.com/app/dojos/qutebrowser>
=> link to shortcutFoo training course

tests/unit/completion/test_models.py
Fixing some test deficiencies I noticed while working on #74
=> Completion tests

qutebrowser/app.py, qutebrowser/utils/version.py, tests/end2end/test_invocations.py, tests/unit/utils/test_version.py
Displays the path names from standarddir in the qute://version builtin page.
fixes #1947
=> standarddir path names in qute://version (Issue #1947)

tests/unit/javascript/position_caret/test_position_caret.py
=> show webview when caret testing

doc/userscripts.asciidoc
Quick update for Issue #1946 (Document userscript types on Windows)
=> Note on Windows userscript extensions

qutebrowser/browser/commands.py, qutebrowser/commands/userscripts.py, tests/end2end/features/spawn.feature
=> improved error messages for inexistent userscripts

qutebrowser/browser/commands.py, tests/end2end/features/yankpaste.feature
=> correct yanking of URLs using the ';' separator

qutebrowser/javascript/scroll.js
Fix wrong scroll.height for xkcd. Solution according to:
http://stackoverflow.com/questions/1145850/how-to-get-height-of-entire-document-with-javascript
=> Fix scroll JS for xkcd.

tests/end2end/features/misc.feature
I wrote it as you suggested. I wanted to use `:enter-mode command`, but I ran into #1137.
=> BDD tests for :command-history-prev/next

pytest.ini
Discussed in #2016.
It fixes issue I had, but let's see if it doesn't break anything.
=> Ignore NetworkManager-related Qt warnings

qutebrowser/browser/webengine/webengineelem.py, qutebrowser/javascript/webelem.js
=> Implement __setitem__ in WebEngineElement

README.asciidoc, doc/help/settings.asciidoc, doc/qutebrowser.1.asciidoc, misc/cheatsheet.svg, qutebrowser/app.py, qutebrowser/config/configdata.py, qutebrowser/misc/crashdialog.py, scripts/dev/ci/appveyor_install.py, scripts/setupcommon.py
=> Use https for links in docs and elsewhere

INSTALL.asciidoc
=> Update macports Qt install instructions

CONTRIBUTING.asciidoc
adds a rough outline of how to set up a dev env on windows
=> Win Dev Environment instructions

www/header.asciidoc
For #1490: I've added the http://qutebrowser.org/doc/help/ page to the main menu. Please tell me what you think.
=> Fix for "Help not discoverable" (#1490)

tests/end2end/features/yankpaste.feature
https://github.com/The-Compiler/qutebrowser/pull/2054#issuecomment-257345920
=> Use jseval to test insert-text with js disabled

tests/end2end/features/yankpaste.feature
=> Fix insert-text with javascript disables test

qutebrowser/browser/hints.py, tests/end2end/features/history.feature
My take on #2073 (add an option to add hinted links to the history). 
This is my first time contributing to a major project, so sorry if I screwed something up, I'll be more than glad to fix it.
=> "Add to history" flag

qutebrowser.py, qutebrowser/browser/webkit/network/networkmanager.py, qutebrowser/browser/webkit/network/pac.py, qutebrowser/browser/webkit/network/proxy.py, qutebrowser/config/configtypes.py, qutebrowser/javascript/.eslintignore, qutebrowser/javascript/pac_utils.js, qutebrowser/utils/log.py, scripts/dev/ci/travis_install.sh, tests/unit/browser/webkit/network/test_pac.py, tests/unit/config/test_configtypes.py, tox.ini
I don't feel confident in several things:
- Handling of `QNetworkAccessManager` in `HTTPProxyResolver`. I want to get a signal and finish asynchronously but if someone has called `resolve` before that, to wait for its completion. Also I want to clean up after that (set things to `None`). I don't quite understand how signals work -- are `_finish` and `resolve` called from different threads?  When it's safe to remote `HTTPNetworkReply` so that completion signal is delivered to `QEventLoop`? If `resolve` is called long after signal is delivered, will it work? I feel not but I'm unsure how to get this right;
- Code style;
- Tests -- I haven't even run them because I don't know how.
To be honest, I haven't touched Python and Qt for a very long time, so I just used Google for every feature I …
=> Implement PAC support

qutebrowser/commands/userscripts.py
Fixes https://github.com/The-Compiler/qutebrowser/issues/2100
=> Add error handling for UnicodeDecodeError

qutebrowser/browser/hints.py, tests/end2end/data/email_address.html, tests/end2end/features/hints.feature
=> Strip mailto: when yanking a hint

FAQ.asciidoc
I was also confused about what was the difference between quickmarks and bookmarks #2226 but I think I figured it out. Here's my proposal for the FAQ.
Now please bear with me if I'm doing something wrong, I'm new to Github and still learning things.
=> Explanation about quickmarks and bookmarks to FAQ

qutebrowser/utils/urlutils.py, tests/unit/browser/webkit/network/test_pac.py, tests/unit/utils/test_urlutils.py
This fixes a bug in b220b5438f (tested locally) and also adds more tests for PAC (I haven't run it locally yet, so wait for Travis!).
=> Fix PAC and add more tests

qutebrowser/browser/commands.py, qutebrowser/browser/downloads.py, qutebrowser/browser/webkit/mhtml.py, qutebrowser/utils/utils.py, tests/end2end/features/downloads.feature, tests/end2end/test_invocations.py, tests/unit/utils/test_utils.py
=> Use the new download prompt for mhtml

misc/userscripts/ripbang
Adds a DuckDuckGo bang as local searchengine.
see https://github.com/rsteube/qutebrowser-ripbang
=> Added ripbang userscript

README.asciidoc, doc/help/commands.asciidoc, doc/help/settings.asciidoc, qutebrowser/browser/commands.py, qutebrowser/config/configdata.py
And superfluous whitespace removed.
=> Small docs improvements

qutebrowser/app.py, qutebrowser/browser/browsertab.py, qutebrowser/config/configdata.py
Auto saves a session when loadFinished is emmited.
=> auto save session

qutebrowser/browser/commands.py, tests/end2end/data/misc/jseval_file.js, tests/end2end/features/misc.feature
=> Adds a --file flag to :jseval

qutebrowser/browser/qutescheme.py, qutebrowser/html/bookmarks.html, qutebrowser/html/history.html, qutebrowser/html/styled.html
New qute:bookmarks page that follows the design of qute:history. For #2334.
=> Update qute:bookmarks design.

qutebrowser/browser/adblock.py
=> adblock: Don't show message if host-blocking-enabled is true

qutebrowser/mainwindow/mainwindow.py, qutebrowser/mainwindow/messageview.py, qutebrowser/misc/utilcmds.py, qutebrowser/utils/message.py
=> Add command to clear messages.

qutebrowser/config/config.py
Problem: I like to edit `~/.config/qutebrowser/qutebrowser.conf`
manually with Vim. This works great, except that the current format is a
bit of a pain to deal with:
[section-name]
#
actual options
So if I want to know the description or what the default value is, I
need to scroll up and back down.
Solution: change the order of the comments to:
[section-name]
option = value
optiontwo = value
[section-two]
...
Which is much more convenient (and also what almost any other program
does).
(This patch changes much less code than it looks in the diff; I just
de-looped and moved `_str_option_desc` below `_str_items` as that makes
more sense since it gets called by `_str_items`).
=> Put option comments right above the option value

FAQ.asciidoc
It's in #700, but not so easy to find.
=> Document how to do spell checking in the FAQ

qutebrowser/browser/qutescheme.py, qutebrowser/html/history.html, qutebrowser/html/history_nojs.html, qutebrowser/html/styled.html, qutebrowser/javascript/history.js
=> Show hostname in history page.

tests/unit/completion/test_models.py
I'm having trouble figuring out what's wrong with the history reading test. I'm guessing it has something to do with how `benchmark` handles I/O or coroutines, but the numbers are much smaller than they should be.
Oddly enough, I tried this and the print statements print very different results for `benchmark` (uncommenting the benchmark line):
def bench():
import datetime
t = datetime.datetime.now()
list(hist.async_read())
print((datetime.datetime.now() - t).microseconds)
#benchmark(bench)
bench()
Also, the completion tests seem fine, but I did wonder about using an actual history file instead of random data. I thought of using my own as a representative sample, but decided I didn't want my browsing history immortalized forever :grin:
=> Benchmark history

qutebrowser/browser/network/pac.py, tests/unit/browser/webkit/network/test_pac.py
Fixes https://github.com/qutebrowser/qutebrowser/issues/2476. Also add a test.
Haven't run the test because I have new Qt; let's see what Travis has to say.
=> Fix crash on PAC evaluation error

qutebrowser/config/configdata.py, qutebrowser/mainwindow/tabwidget.py
=> Implement changing of tab title when privacy mode is enabled

qutebrowser/browser/commands.py, tests/end2end/features/javascript.feature, tests/end2end/features/tabs.feature
=> Select the last focused tab when running ':tab-focus <current tab number>'

INSTALL.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2750)
=> Remove recommendation to use '-c' command line argument, which doesn't exist

qutebrowser/browser/commands.py, qutebrowser/browser/webengine/webenginetab.py, qutebrowser/mainwindow/mainwindow.py
Fixes #2778  but has stil an unneccessary animation (it seems to first restore a small window and then maximize that one again)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2782)
=> Fullscreen

FAQ.asciidoc, scripts/open_url_in_instance.sh
This PR adds the script discussed in IRC to the repo and some explaining lines to the FAQ on how to use it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2805)
=> Url launch script

qutebrowser/browser/browsertab.py, qutebrowser/browser/commands.py, qutebrowser/browser/webengine/webenginetab.py, qutebrowser/browser/webkit/webkittab.py
Per #2804
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2806)
=> Skip intermediate pages with :back/:forward and a count (Closes #2804)

qutebrowser/completion/completionwidget.py, qutebrowser/completion/models/completionmodel.py, qutebrowser/completion/models/histcategory.py, qutebrowser/completion/models/listcategory.py, tests/unit/completion/test_completionmodel.py, tests/unit/completion/test_completionwidget.py, tests/unit/completion/test_histcategory.py, tests/unit/completion/test_listcategory.py
Fix two recent issues and remove one old TODO.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2846)
=> Completion fixes

INSTALL.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2901)
=> INSTALL: update openSUSE install instructions

qutebrowser/browser/history.py, tests/unit/browser/test_history.py
Resolves #2963.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2965)
=> Resolve KeyError when deleting URL with space.

doc/help/commands.asciidoc, qutebrowser/browser/commands.py, tests/end2end/features/tabs.feature
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3024)
=> Add count support to buffer command

qutebrowser/commands/command.py, qutebrowser/misc/keyhintwidget.py, tests/helpers/stubs.py, tests/unit/misc/test_keyhints.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3056)
=> Show keyhints even with count prefix

doc/help/commands.asciidoc, qutebrowser/mainwindow/mainwindow.py, qutebrowser/mainwindow/statusbar/command.py, tests/end2end/features/misc.feature
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3025)
=> Add arg to run when count given for :set-cmd-text

misc/userscripts/view_in_mpv
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3057)
=> Support playlist in mpv userscript.

doc/help/settings.asciidoc, qutebrowser/config/configdata.yml, qutebrowser/mainwindow/tabwidget.py, tests/helpers/stubs.py
note that I couldn't use {url} as field for the FormatString
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3115)
=> it was not possible to show the current_url in tab or window title

qutebrowser/completion/completer.py, qutebrowser/config/configdata.yml, tests/helpers/stubs.py
Closes #1100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3034)
=> Completion performance tweaks

misc/qutebrowser.appdata.xml
This changeset adds a basic `appdata.xml` file, solving issue #328.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3139)
=> Add an appdata.xml file

doc/help/commands.asciidoc, qutebrowser/browser/commands.py, qutebrowser/completion/models/miscmodels.py, tests/end2end/features/invoke.feature, tests/end2end/features/tabs.feature, tests/helpers/fixtures.py, tests/helpers/stubs.py, tests/unit/completion/test_models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3054)
=> :tab-{give,take}

doc/install.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3147)
=> fix debian install instructions to fit debian9 and new apt

tests/end2end/features/tabs.feature
Super tiny typo I introduced in #3150, sorry!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3176)
=> Fix typo in :home on pinned tab test

qutebrowser/browser/commands.py, tests/end2end/features/tabs.feature
This closes #3178
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3180)
=> Ensure that a window with the given win_id exists

qutebrowser/app.py, qutebrowser/utils/version.py, scripts/asciidoc2html.py, scripts/dev/build_release.py, scripts/dev/check_coverage.py, scripts/dev/check_doc_changes.py, scripts/dev/gen_resources.py, scripts/dev/get_coredumpctl_traces.py, scripts/dev/misc_checks.py, scripts/dev/recompile_requirements.py, scripts/dev/run_profile.py, scripts/dev/run_pylint_on_tests.py, scripts/dev/segfault_test.py, scripts/dev/src2asciidoc.py, scripts/link_pyqt.py, scripts/setupcommon.py, tests/end2end/features/test_qutescheme_bdd.py, tests/end2end/test_invocations.py, tests/unit/misc/test_checkpyver.py, tests/unit/utils/test_standarddir.py, tests/unit/utils/test_version.py
Using subprocess run instead of Popen. It is recommended since python 3.5.
Part of #3020
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3203)
=> change subprocess Popen to run

qutebrowser/javascript/.eslintrc.yaml, qutebrowser/javascript/history.js, qutebrowser/javascript/pac_utils.js, qutebrowser/javascript/position_caret.js, qutebrowser/javascript/scroll.js, qutebrowser/javascript/webelem.js
i somehow messed up at #3217 so i redid the hole thing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3225)
=> es6ified js

doc/faq.asciidoc, doc/help/settings.asciidoc, qutebrowser/config/configdata.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3255)
=> Update documentation to reflect new dictcli.py script

doc/help/settings.asciidoc, qutebrowser/config/configdata.yml, qutebrowser/mainwindow/tabwidget.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3261)
=> change the code for the renamed preferences

doc/install.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3311)
=> Document installation using FreeBSD port

qutebrowser/misc/utilcmds.py, tests/end2end/data/misc/pyeval_file.py, tests/end2end/features/qutescheme.feature
fixes #3296
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3313)
=> Added --file for :debug-pyeval

qutebrowser/completion/models/configmodel.py, qutebrowser/config/config.py, tests/unit/completion/test_models.py
Closes #3331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3336)
=> Show default keybinding in :bind completion

scripts/open_url_in_instance.sh
Sometimes when qutebrowser crashes, it leaves the IPC socket file behind. In those cases this script still tried to use it, failed, and didn't open your URL at all.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3332)
=> check if qutebrowser process is running

qutebrowser/completion/models/completionmodel.py, qutebrowser/completion/models/urlmodel.py, tests/unit/completion/test_completionmodel.py, tests/unit/completion/test_models.py
Now using `metaObject` to emit signals for pyqt-571 compatibility
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3352)
=> Ensure HistCategory works in isolation

tests/end2end/features/test_editor_bdd.py
A few step definitions listed these in the parameters although they were
unused.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3356)
=> Remove needles quteproc/server fixture deps.

qutebrowser/browser/commands.py, qutebrowser/completion/completer.py, qutebrowser/completion/models/miscmodels.py, qutebrowser/mainwindow/mainwindow.py, tests/unit/completion/test_completer.py, tests/unit/completion/test_models.py
Resolves #3144.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3357)
=> Don't show current window for :tab-give/:tab-take.

.travis.yml, misc/userscripts/cast, misc/userscripts/dmenu_qutebrowser, misc/userscripts/format_json, misc/userscripts/open_download, misc/userscripts/password_fill, misc/userscripts/qutedmenu, misc/userscripts/rss, misc/userscripts/taskadd, misc/userscripts/view_in_mpv, scripts/dev/ci/travis_backtrace.sh, scripts/dev/ci/travis_install.sh, scripts/dev/ci/travis_run.sh, scripts/dev/download_release.sh, scripts/dev/quit_segfault_test.sh
Run shellcheck in docker on Travis against all `*.sh` files under `dev/scripts/` and all files with a sh/bash/dash/ksh shebang under `misc/userscripts/`.
Closes #1685 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3355)
=> Add shellcheck to CI - Closes #1685

doc/help/commands.asciidoc, doc/help/settings.asciidoc, qutebrowser/browser/qutescheme.py, qutebrowser/config/configdata.yml, qutebrowser/html/back.html, qutebrowser/misc/sessions.py, tests/unit/misc/test_sessions.py
Changes compared to the last pull request:
- restore tab if visible
- after restore:  forward the user to the 
* next history entry if he came from a previous history entry
* otherwise forward him to the previous history entry
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3345)
=> Lazy sessions

scripts/hist_importer.py
I made this script in order to import my firefox browser history to qutebrowser, some people over irc suggested that maybe it could be of any use to others, i polished it a little in order to post here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3044)
=> Import history data from other browsers

doc/install.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3386)
=> Fedora instructions for non-free codecs

qutebrowser/browser/commands.py, qutebrowser/config/configdata.yml, qutebrowser/mainwindow/statusbar/command.py, tests/end2end/features/qutescheme.feature, tests/end2end/features/search.feature, tests/end2end/test_invocations.py, tests/unit/config/test_configcommands.py, tests/unit/config/test_configdata.py
The first commit adds incremental search. The second commit is a kind of quality of life improvement I felt was needed as you can spam 'Text {} not found on page!' warnings a lot with this new feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3201)
edit by @The-Compiler: Closes #584
=> Add incremental_search config option

qutebrowser/browser/history.py
Fix #3396 
(edited by @the-compiler as issue references need to be in the body, not title)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3423)
=> Don't store qute://back URLs in history

qutebrowser/misc/sessions.py, tests/end2end/features/sessions.feature
closes https://github.com/qutebrowser/qutebrowser/issues/3503
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3506)
=> Added :session-load --delete

doc/help/commands.asciidoc, doc/help/settings.asciidoc, qutebrowser/browser/commands.py, qutebrowser/config/configdata.yml, qutebrowser/utils/urlutils.py, tests/unit/utils/test_urlutils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3515)
=> incdec_number: add support for port

qutebrowser/browser/network/proxy.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3540)
=> document proxy environment variable for system proxy

qutebrowser/browser/commands.py, qutebrowser/browser/network/proxy.py, qutebrowser/commands/userscripts.py
Resolves #3547
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3549)
=> fix spawn race condition when using --output option

qutebrowser/html/back.html
resolves #3542
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3558)
=> Fix going back twice on lazy loading a tab

doc/faq.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3565)
=> Add troubleshooting info for widevine to FAQ

qutebrowser/browser/commands.py
- Resolves #3548
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3581)
=> [count] overrides win_id for tab-give cmd

qutebrowser/browser/webengine/webenginetab.py
Resolves #3322
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3587)
=> Update tab scroll position when finished loading.

qutebrowser/browser/qutescheme.py, qutebrowser/html/tabs.html
Enable to see a list of all open tabs with their urls.
This is a feature I use to get the list of open tabs and then feeding it to some external script (usually a download manager).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3450)
=> Add tabs list page

doc/install.asciidoc
See https://github.com/lukesampson/scoop-extras/pull/783
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3607)
=> Add scoop installer

qutebrowser/browser/browsertab.py, qutebrowser/browser/webengine/webenginetab.py, qutebrowser/browser/webkit/webkittab.py
Fixes part 1 of #3583 
This is a small change, let me know if you think anything seems wrong with it though!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3592)
=> Fix caret being cleared when leaving any mode

qutebrowser/utils/version.py, tests/helpers/stubs.py, tests/unit/misc/test_pastebin.py, tests/unit/utils/test_version.py
In testing for success, it is ran twice, the second time without a signal to test it kept the url.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3594)
=> Add test for pastebin_version()

misc/userscripts/tor_identity
Add user script to change tor identity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3603)
=> Add tor_identity userscript.

qutebrowser/completion/models/histcategory.py, tests/unit/completion/test_histcategory.py
Resolves #3628.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3652)
=> Resolve empty completion.timestamp_format crash.

.flake8, misc/requirements/requirements-flake8.txt
For reference, see snoack/flake8-per-file-ignores#6.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3695)
=> Update flake8-per-file-ignores to version 0.5

doc/faq.asciidoc
The most common questsions regarding greasemonkey support on IRC are "how do I use it" and "why doesn't my script work", hopefully this can be a starting point for most people experiencing issues.
Hopefully it isn't to loooong.
I haven't used asciidoc before but I copied the other entries and it looks okay on my machine.
Happy now @jgkamat?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3715)
=> Greasemonkey: add FAQ entry.

misc/userscripts/taskadd
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3728)
---
[edit by @jgkamat to link issues: Closes #3726]
=> Fix: restrict output of `task` to one line (closes #3726)

misc/userscripts/getbib
No dependencies. Tested on Debian Stretch. Docstring should explain it all :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3791)
=> Add userscript to download bibtex for DOI scraped from current tab

doc/install.asciidoc
Follow up from discussion in #3885
@mrbig033, does this look good to you?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3930)
=> Clarify install command for Ubuntu 17.04

misc/Makefile, misc/qutebrowser.appdata.xml
Furthermore add some information about the latest releases
and remove a few trailing whitespaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3926)
=> appdata: install the metainfo using the Makefile

scripts/importer.py
Fix #4114 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4120)
=> Fix #4114 importer.py may fail on chrome bookmarks import

doc/install.asciidoc
Add install instructions for slackware
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4123)
=> Add slackware installation instructions

qutebrowser/app.py
Trying to fix the issue:
Show warning when using --backend and opening in existing instance #2211
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4105)
=> Show warning when using --backend with a running instance

doc/changelog.asciidoc, qutebrowser/utils/log.py
Fixes #4137
Fixes #2537
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4138)
*edited by @the-compiler to add #2537*
=> Fix double-escaping on qute://log

README.asciidoc
Checked other entries in both the Active and Inactive lists;
no changes needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4148)
Fixes #4141 *(added by @The-Compiler to auto-close the issue)*
=> Add two similar projects to the Active list in README.

doc/changelog.asciidoc, doc/help/configuring.asciidoc, doc/help/settings.asciidoc, qutebrowser/app.py, qutebrowser/browser/history.py, qutebrowser/browser/qutescheme.py, qutebrowser/completion/models/histcategory.py, qutebrowser/completion/models/urlmodel.py, qutebrowser/config/configdata.yml, qutebrowser/config/configtypes.py, qutebrowser/misc/sql.py, scripts/dev/run_vulture.py, tests/unit/browser/test_adblock.py, tests/unit/browser/test_history.py, tests/unit/browser/test_qutescheme.py, tests/unit/completion/test_histcategory.py, tests/unit/completion/test_models.py, tests/unit/config/test_configtypes.py, tests/unit/mainwindow/test_messageview.py, tests/unit/misc/test_sql.py
Sooo I originally only wanted to implement a blacklist for history items, but got a bit lost and took care of other SQL related stuff and cleanups as well :blush: 
I'd appreciate a quick review of this! It's probably easiest to review it commit-by-commit, as I tried to keep the things separate there.
Touches #1768 though it doesn't make it possible to filter by query, as URL patterns don't support that.
Fixes #3341 as per the discussions in #3073.
Fixes #3060.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4181)
=> Various SQL related changes

doc/changelog.asciidoc, qutebrowser/browser/commands.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4206)
=> Support multiple words for :tab-take without quotes

qutebrowser/mainwindow/tabwidget.py
I was poking around the qt source code looking at if [expanding](https://doc.qt.io/qt-5/qtabbar.html#expanding-prop) could help us (which I didn't think it could, due to how pinned tabs shrink). However, I realized that if we just request as much space as possible, qt will automatically size us down correctly so normal tabs take up the same amount of space (which seems to be what we want). I don't know why I didn't think of this earlier, maybe I was keeping some feature in mind that I forgot now, but I don't think this should affect any tab sizing behavior but should fix #4069 and make everything so much simpler :).
If this works out, we can close #4070.
--- …
=> Use qt to equally size tabs

qutebrowser/mainwindow/tabwidget.py
When deleting the first tab repeatedly from a list of 100 tabs, the `minTabSizeHint` cache is blown over and over (which exposes the performance problems from back when we added that cache). Every tabSizeHint call makes a call to `minTabSizeHint` as well, which dosen't seem to be cached on the same layer as the call from qt for some reason. This tries to remove that call, to make the call graph a little better.
We may want to reccomend removing `{index}` from `tabs.title.format` for people with >100 tabs, as it makes actions like this much more snappy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4246)
=> Avoid calls to minTabSizeHint in tabSizeHint

qutebrowser/browser/browsertab.py, qutebrowser/browser/webengine/webenginetab.py, qutebrowser/browser/webkit/webkittab.py, qutebrowser/config/configdata.yml, tests/helpers/stubs.py
See #4154
This is my first contribution, so if there's a better way to do this (most likely), please give me feedback and I'll make the changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4189)
=> Allow tabs be muted by default

qutebrowser/app.py, qutebrowser/completion/completiondelegate.py, qutebrowser/config/configdata.yml, qutebrowser/config/configtypes.py, tests/unit/completion/test_completiondelegate.py, tests/unit/config/test_configtypes.py
Resolves #4199 (and adds a little test coverage :grin:)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4220)
=> Completion escape

qutebrowser/config/configdata.yml, qutebrowser/mainwindow/tabbedbrowser.py, tests/end2end/features/tabs.feature
Closes #4007
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4008)
=> Add setting for controlling stacking of new tabs

qutebrowser/browser/adblock.py, qutebrowser/browser/webengine/interceptor.py, qutebrowser/browser/webkit/network/networkmanager.py, qutebrowser/config/configdata.yml
Add an additional argument to is_blocked for the current url, and enable
the host_blocking.enabled property to be set per domain.
This allows to bypass host blocking for specific domains
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4046)
=> make the host_blocker aware of patterns

qutebrowser/completion/models/configmodel.py, qutebrowser/config/configcommands.py, tests/unit/config/test_configcommands.py
Adds the config-add command.
Modifies #2794
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4283)
=> New config: More powerful :config- commands: add

qutebrowser/browser/hints.py
Commit 58ded41e5d7f611cf8629f174c8725d93eb28ac2 changed the code, but did not change the documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4352)
=> Fix docstring for HintManager.filter_hints

misc/requirements/requirements-tests.txt
CI is currently completely broken so hopefully @The-Compiler can take a look at this soon to make sure it's OK :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4386)
=> Upgrade itsdangerous to 1.1.0

doc/faq.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4428)
=> Fix FAQ grammar

doc/help/configuring.asciidoc
Very minor nit. qutebrowser is my main interface into the awkward mouse-driven modern WWW. Thank you all for this wonderful program.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4431)
=> Change some language about autoconfig to be clearer

qutebrowser/html/error.html
Fixes #4450.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4451)
=> Use tojson filter to convert url to Javascript string

doc/install.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4501)
=> Remove obsolete Fedora instructions

doc/changelog.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4528)
=> doc: link CVE  [ci skip]

qutebrowser/browser/greasemonkey.py, qutebrowser/browser/webengine/webenginetab.py, tests/unit/browser/webengine/test_webenginetab.py, tests/unit/javascript/test_greasemonkey.py
See #4322
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4604)
=> GreaseMonkey: Force document-end for known-broken scripts

doc/contributing.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4644)
=> Fix broken link in contributing.asciidoc

misc/userscripts/qute-keepass, qutebrowser/completion/completionwidget.py, qutebrowser/mainwindow/mainwindow.py, qutebrowser/mainwindow/tabwidget.py
source: https://lgtm.com/projects/g/qutebrowser/qutebrowser/alerts/?mode=tree
There're more warnings, in this PR mostly trivial stuff.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4676)
=> Fix a few lgtm warnings

qutebrowser/browser/browsertab.py, qutebrowser/browser/webengine/webenginetab.py, qutebrowser/browser/webkit/webkittab.py, qutebrowser/components/caretcommands.py, qutebrowser/config/configdata.yml, qutebrowser/javascript/caret.js, tests/end2end/features/caret.feature, tests/unit/browser/test_caret.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4513)
---
Fixes #3714 *(edited by @The-Compiler to auto-close the issue)*
=> Implement v_o in caret mode

qutebrowser/app.py, qutebrowser/browser/history.py, qutebrowser/completion/models/histcategory.py, qutebrowser/misc/sql.py, tests/unit/browser/test_history.py, tests/unit/completion/test_histcategory.py, tests/unit/misc/test_sql.py
Closes #4681
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4682)
=> Fix crash on long sql lines

qutebrowser/misc/sql.py
https://travis-ci.org/qutebrowser/qutebrowser/jobs/515081777
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4698)
=> Fix missing reference to SqlError

qutebrowser/config/configdata.yml, qutebrowser/config/configfiles.py, qutebrowser/mainwindow/tabwidget.py, tests/unit/config/test_configfiles.py
Currently {title} in the title format conflicts with the {title}
expansion which is undesirable (due to #4652)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4733)
=> Rename {title} to {current_title}

qutebrowser/misc/guiprocess.py, tests/unit/misc/test_guiprocess.py
This is in response to issue #4729
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4738)
=> Integrated exitinfo from _spawn_format and _on_finished for better spawn output.

misc/userscripts/README.md, misc/userscripts/format_json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4747)
=> Adapted alias instructions to modern configuration

qutebrowser/mainwindow/prompt.py
See https://github.com/qutebrowser/qutebrowser/issues/1249#issuecomment-446266469 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4756)
=> Fixes crash in #1249

qutebrowser/commands/runners.py
Essentially a little more fancy version of http://www.github.com/qutebrowser/qutebrowser/pull/4536
Continuation of https://github.com/qutebrowser/qutebrowser/pull/4652#issuecomment-484351967 
Haven't run all tests on this yet, but it seemed to pass what I thought would break. I'll fix anything if it comes up though (still not 100% sure this is safe).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4731)
=> Build variable replacement dict on init

qutebrowser/utils/urlutils.py, tests/unit/utils/test_urlutils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4795)
=> Fix incdec

qutebrowser/browser/pdfjs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4864)
=> Add pdf.js path for Flathub flatpak

doc/help/commands.asciidoc, doc/help/settings.asciidoc, qutebrowser/browser/shared.py, qutebrowser/browser/webengine/webenginetab.py, qutebrowser/browser/webkit/webpage.py, qutebrowser/config/configdata.yml, qutebrowser/mainwindow/prompt.py, qutebrowser/utils/message.py, qutebrowser/utils/usertypes.py, tests/end2end/features/conftest.py, tests/end2end/features/downloads.feature, tests/end2end/features/prompts.feature, tests/end2end/features/test_downloads_bdd.py, tests/end2end/fixtures/quteprocess.py
Fixes #832
Missing tests as I'm running out of battery, a review of what's here already would be good!
=> Add :prompt-accept --save for boolean prompts

qutebrowser/config/config.py, qutebrowser/config/configfiles.py, qutebrowser/utils/version.py, tests/unit/utils/test_version.py
This is a continuation of #4959 , this should close #4941 .
=> Version config.py path

qutebrowser/keyinput/keyutils.py, tests/unit/keyinput/test_keyutils.py
Fixes #4582.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4585)
=> Add AltGr to _MODIFIER_MAP

scripts/dictcli.py
Under Windows this is unneeded
=> Add check for platform in check_root()

doc/help/settings.asciidoc, qutebrowser/config/configdata.yml
My password generator found this one.
=> Support pasting text that starts with a hyphen

misc/userscripts/qute-keepass
=> Call format on the right object

misc/userscripts/qute-pass
=> Add argument extra-url-suffixes

qutebrowser/browser/downloadview.py, qutebrowser/mainwindow/mainwindow.py
=> Hide/show the downloadview when entering/leaving fullscreen

qutebrowser/browser/urlmarks.py
Allows easier organization of urlmarks.
=> Add comments for quickmarks and bookmarks.

qutebrowser/utils/utils.py, qutebrowser/utils/version.py, tests/unit/utils/test_version.py
This series is a first attempt to adjust the handling of dispatchers when inside a sandbox. Related to https://github.com/qutebrowser/qutebrowser/issues/4879
=> Dispatcher behaviour in Flatpak sandbox

qutebrowser/utils/urlutils.py, tests/unit/utils/test_urlutils.py
=> Fix IP address with port in naive url detector

misc/userscripts/qute-lastpass
Fixes #5130 
---
*edited by @The-Compiler to auto-close the issue*
=> #5130 - LastPass CLI errors that aren't lookup failures should terminate lookup loop

qutebrowser/browser/commands.py, qutebrowser/commands/userscripts.py, tests/end2end/features/conftest.py, tests/end2end/features/spawn.feature
=> Make `spawn -m -u` work properly

misc/userscripts/password_fill
=> Trigger input change event in password_fill.

doc/help/configuring.asciidoc
=> Corrected "c.tabs.possition" typo

scripts/asciidoc2html.py
=> Refactor script to use pathlib

scripts/asciidoc2html.py
Make asciidoc2html.py compatible with Python3.5 again.
=> Fix 3.5 incompatibility in script

scripts/asciidoc2html.py
=> Fixed paths in asciidoc2html

qutebrowser/browser/webengine/webenginetab.py
=> Check the current mode in _toggle_sel_translate callback

qutebrowser/completion/completionwidget.py, qutebrowser/config/configdata.yml, tests/unit/completion/test_completionwidget.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4301)
=> Handle PageUp/PageDown for completion 

misc/userscripts/readability-js
=> Rely on npm's version of the readability library

misc/userscripts/README.md
The title is self explanatory. Give me a feedback on my code please. I'm learning and hope to get better on this, specially on tests.
=> Added qute-snippets to Others section of userscripts README.md

qutebrowser/browser/browsertab.py, qutebrowser/browser/hints.py, qutebrowser/keyinput/modeparsers.py, qutebrowser/mainwindow/statusbar/bar.py, qutebrowser/mainwindow/statusbar/text.py, qutebrowser/mainwindow/statusbar/url.py, qutebrowser/utils/docutils.py, qutebrowser/utils/usertypes.py, qutebrowser/utils/version.py, scripts/dev/check_coverage.py, tests/unit/api/test_cmdutils.py, tests/unit/commands/test_argparser.py, tests/unit/utils/test_utils.py
This PR is an attempt to close #5336 . I've managed to replace all enums defined in function-like fashion. However, since I'm new to this project and not really familiar with its internals (yet), I need some help with docstrings for new class-based enums :)
=> Use class-based API instead of functions for enums

qutebrowser/app.py
It is always good to remove one level of indentation if we can, for readability!
For hacktoberfest..
=> app.py: remove one indentation level in event()

misc/apparmor/usr.bin.qutebrowser
Simple apparmor profile for qutebrowser. Could probably be improved taking inspiration from the [chromium profile](https://gitlab.com/apparmor/apparmor-profiles/blob/master/ubuntu/18.04/usr.bin.chromium-browser) found in the apparmor repository, but this one is a good start and works fine for me.
Closes #5729
=> update apparmor profile

qutebrowser/browser/downloads.py, qutebrowser/browser/navigate.py, qutebrowser/browser/qtnetworkdownloads.py, qutebrowser/browser/qutescheme.py, qutebrowser/browser/shared.py, qutebrowser/browser/urlmarks.py
Not all files in `qutebrowser/browser` have been included as I would
like the PRs to be easily reviewable. Let me know if you would prefer
larger PRs instead.
See #5396
=> mypy: use from-import in some qutebrowser/browser files

scripts/dev/ua_fetch.py
It's been a while since I did a contribution and this seemed something nice to do during midday break. Closes #5804. Implementation is almost exactly as asked, except I did the filtering of non-Chrome user agents before parsing (the parser crashed on a missing key `AppleWebkit` if I didn't).
=> Add new ua_fetch script

qutebrowser/browser/browsertab.py, qutebrowser/browser/commands.py, qutebrowser/browser/downloadview.py, qutebrowser/browser/greasemonkey.py, qutebrowser/browser/hints.py, qutebrowser/browser/history.py, qutebrowser/browser/inspector.py, qutebrowser/browser/network/pac.py, qutebrowser/browser/qutescheme.py, qutebrowser/browser/webelem.py, qutebrowser/browser/webengine/darkmode.py, qutebrowser/browser/webengine/webengineelem.py, qutebrowser/browser/webengine/webenginesettings.py, qutebrowser/browser/webengine/webenginetab.py, qutebrowser/browser/webengine/webview.py, qutebrowser/browser/webkit/cache.py, qutebrowser/browser/webkit/cookies.py, qutebrowser/browser/webkit/mhtml.py, qutebrowser/browser/webkit/network/networkmanager.py, qutebrowser/browser/webkit/tabhistory.py, qutebrowser/browser/webkit/webkitelem.py, qutebrowser/browser/webkit/webkitsettings.py, qutebrowser/browser/webkit/webkittab.py, qutebrowser/browser/webkit/webpage.py
The type comments have also been changed to annotations, since Python
3.5 support will be dropped with the next release.
See #5396
=> mypy: use from-import for typing in remaining files in `browser`

qutebrowser/api/cmdutils.py, qutebrowser/api/config.py, qutebrowser/api/hook.py, qutebrowser/commands/command.py, qutebrowser/commands/runners.py, qutebrowser/commands/userscripts.py, qutebrowser/completion/completionwidget.py, qutebrowser/completion/models/completionmodel.py, qutebrowser/completion/models/histcategory.py, qutebrowser/completion/models/listcategory.py, qutebrowser/completion/models/miscmodels.py, qutebrowser/completion/models/urlmodel.py, qutebrowser/completion/models/util.py, qutebrowser/components/adblock.py, qutebrowser/components/misccommands.py, qutebrowser/components/readlinecommands.py, qutebrowser/extensions/interceptors.py, qutebrowser/extensions/loader.py
Update files in `api`, `commands`, `completion`, `components`, and
`extensions`.
See #5396
=> mypy: use from-import style

qutebrowser/keyinput/basekeyparser.py, qutebrowser/keyinput/eventfilter.py, qutebrowser/keyinput/keyutils.py, qutebrowser/keyinput/macros.py, qutebrowser/keyinput/modeman.py, qutebrowser/keyinput/modeparsers.py, qutebrowser/mainwindow/mainwindow.py, qutebrowser/mainwindow/messageview.py, qutebrowser/mainwindow/prompt.py, qutebrowser/mainwindow/tabbedbrowser.py, qutebrowser/mainwindow/tabwidget.py, qutebrowser/mainwindow/windowundo.py, qutebrowser/misc/backendproblem.py, qutebrowser/misc/cmdhistory.py, qutebrowser/misc/crashsignal.py, qutebrowser/misc/debugcachestats.py, qutebrowser/misc/httpclient.py, qutebrowser/misc/lineparser.py, qutebrowser/misc/miscwidgets.py, qutebrowser/misc/objects.py, qutebrowser/misc/quitter.py, qutebrowser/misc/savemanager.py, qutebrowser/misc/sessions.py, qutebrowser/misc/throttle.py, qutebrowser/misc/utilcmds.py
Update files in `keyinput`, `mainwindow`, and `misc`.
See #5396
=> mypy: use from-import style for typing

qutebrowser/utils/debug.py, qutebrowser/utils/docutils.py, qutebrowser/utils/javascript.py, qutebrowser/utils/jinja.py, qutebrowser/utils/log.py, qutebrowser/utils/message.py, qutebrowser/utils/objreg.py, qutebrowser/utils/qtutils.py, qutebrowser/utils/standarddir.py, qutebrowser/utils/urlmatch.py, qutebrowser/utils/urlutils.py, qutebrowser/utils/usertypes.py, qutebrowser/utils/utils.py, qutebrowser/utils/version.py
=> mypy: use from-import for typing in `utils`

qutebrowser/config/configtypes.py
=> mypy: use from-import for typing in `configtypes.py`

qutebrowser/app.py, qutebrowser/misc/consolewidget.py, qutebrowser/misc/crashdialog.py, scripts/mkvenv.py, tests/unit/api/test_cmdutils.py
I believe this should close #5396
=> mypy: use from-import for typing in remaining files

qutebrowser/config/configdata.yml
=> add {0} as another placeholder available in searchengine

misc/userscripts/README.md, misc/userscripts/kodi
After seeing @The-Compiler add the qr userscript (6c42f97), I figured I should modify a script I used to play videos in Kodi.
Note, my text editor ate a trailing white space in the README.
Let me know if changes are needed.
=> add kodi userscript

doc/userscripts.asciidoc, qutebrowser/browser/greasemonkey.py, qutebrowser/commands/userscripts.py, tests/helpers/fixtures.py, tests/unit/javascript/test_greasemonkey.py
=> load scripts from config directory

qutebrowser/browser/webengine/webenginesettings.py, qutebrowser/config/websettings.py, tests/unit/browser/webengine/test_webenginesettings.py
See #5935 and my review comments in #5813.
I also ended up refactoring the settings handling a bit, but tried to split up everything into separate commits.
=> Profile cleanup 1

misc/userscripts/README.md, misc/userscripts/add-nextcloud-bookmarks, misc/userscripts/add-nextcloud-cookbook
A userscript that creates bookmarks in Nextcloud's Bookmarks app.
Let me know if changes are needed.
=> add add-nextcloud-bookmarks and add-nextcloud-cookbook userscripts

misc/userscripts/add-nextcloud-bookmarks
I discovered a bug when checking if a URL has already been bookmarked.  URLs with a '#' were not getting identified correctly when getting checked.  Encoding the URL fixes this.
=> userscript Nextcloud bookmark URL check fix

doc/help/configuring.asciidoc
I added explicitly searched the docs for "keyboard" and "shortcuts" to find how to customize and then asked. I hope adding the keywords makes it easier to find for others.
=> added keyboard and shortcuts

doc/help/settings.asciidoc, qutebrowser/config/configtypes.py
This escapes stuff in `+pass:[...]+` within asciidoc properly.
=> Escape ] chars in setting values in asciidoc

misc/org.qutebrowser.qutebrowser.desktop
=> added german comment to linux desktop file

doc/faq.asciidoc
=> doc: Fix certutil argument

doc/faq.asciidoc
=> FAQ about copy to clipboard buttons

misc/userscripts/readability-js
See the discussion in: https://www.reddit.com/r/qutebrowser/comments/lr84k4/readability_script_not_working/ 
(I think somebody had this problem before, hence the change)
=> [readability-js] Improve install instructions

qutebrowser/browser/shared.py, qutebrowser/mainwindow/prompt.py
=> Wrap and render newlines in JS dialogs

doc/faq.asciidoc
Changed the answer to ad blocker question based on the version 2.0.0 update.
=> Update the ad blocker question on faq.asciidoc

qutebrowser/browser/browsertab.py, qutebrowser/browser/inspector.py, qutebrowser/browser/webengine/webenginetab.py, qutebrowser/browser/webkit/webkittab.py
=> WIP: Adding abstract method to browsertab.py Closes #6121

misc/userscripts/README.md, misc/userscripts/qute-keepassxc
This PR adds my userscript `qute-keepassxc` to fetch credentials from KeepassXC using its browser protocol from https://github.com/ususdei/qute-keepassxc to qutebrowser itself.
Please forward any issues arising with this userscript directly to me.
Closes #6017
=> Add userscript qute-keepassxc

scripts/hist_importer.py
Hi me again; without the index qutebrowser will complain that the index does not exists
=> Force rebuild on history import

qutebrowser/browser/webengine/notification.py
=> Move function call with side effect out of assertion to avoid error when assertions are disabled

misc/nsis/qutebrowser.nsi
Inform the user of unsupported Windows version and deny installation, instead of experiencing #6476.
*(I hope at some point to finish up and submit a better version of the installer that I had almost ready but abandoned a couple of years ago).*
=> Windows Installer: Update minimum OS version

misc/userscripts/README.md
for quick navigation to localhost:port
=> userscripts: adding localhost userscript

qutebrowser/mainwindow/tabwidget.py
Closes #6148 
I have implemented what I think is a fix for issue #6148.  Let me know if I have done this properly, or if it needs changes.  Thanks!
=> fix mac scrolling through tabbar (issue #6148)

qutebrowser/app.py, qutebrowser/browser/history.py, qutebrowser/completion/models/histcategory.py, qutebrowser/completion/models/urlmodel.py, qutebrowser/misc/sql.py, qutebrowser/utils/version.py, tests/helpers/fixtures.py, tests/unit/browser/test_history.py, tests/unit/completion/test_histcategory.py, tests/unit/misc/test_sql.py
Opening this to make the progress visible and allow discussion while I work on it. I also left some comments in the code in case you want to give me some thoughts.
Closes #6039
=> Database class

doc/help/settings.asciidoc, qutebrowser/components/hostblock.py, qutebrowser/config/configdata.yml, tests/unit/components/test_hostblock.py
=> make blocking subdomains configurable

qutebrowser/javascript/greasemonkey_wrapper.js
=> Add support for overrideMimeType in Greasemonkey scripts

doc/help/configuring.asciidoc, misc/userscripts/qute-keepassxc
=> Fix a couple of minor mistakes

misc/userscripts/README.md
I'm creating this pr by [request](https://www.reddit.com/r/qutebrowser/comments/px2yf9/comment/hep3e6d/?utm_source=share&utm_medium=web2x&context=3) of @The-Compiler on reddit.
=> Add userscript bitwarden-rofi to the list of userscripts 

qutebrowser/browser/commands.py, tests/end2end/features/tabs.feature
=> Added Start/End arguments to :tab-move

qutebrowser/config/configdata.yml, qutebrowser/keyinput/basekeyparser.py, tests/unit/keyinput/test_basekeyparser.py
=> Allow disabling counts in config

misc/userscripts/qute-bitwarden
=> Fix typo in license

qutebrowser/config/configdata.yml, qutebrowser/mainwindow/tabbedbrowser.py, tests/end2end/features/tabs.feature
Closes #4960
I know there is a general approach suggested in #35 and maybe this is not the desired way. But thought I would submit this if others would want to use it since I find it quite useful. I'm also open to suggested changes to the approach here.
=> feat(tabbedbrowser) add option to select mode based on url pattern

misc/userscripts/README.md
Discussed here: [/r/qutebrowser](https://www.reddit.com/r/qutebrowser/comments/sionjt/personal_qutescripts/)
=> Add link to personal userscripts

qutebrowser/mainwindow/prompt.py, tests/unit/mainwindow/test_prompt.py
=> No more '..' in the file prompt (#2104)

qutebrowser/browser/webkit/http.py, qutebrowser/misc/sql.py, scripts/dev/change_release.py
=> Missing `f` prefix on f-strings fix

doc/install.asciidoc
Thanks to @The-Compiler 's help on IRC I was able to use the venv install method on debian bullseye but I needed to add `libasound-dev`.
My install script:
```
QUTEBROWSER_VERSION="v2.5.1"
sudo apt --yes --no-install-recommends install \                                                                                                                                                                     
ca-certificates \                                                                                                                                                                                                  
python3 \ …
```
=> Update docs for debian, include `libasound`

misc/userscripts/qutedmenu
Add options to open in new window or private window in qutedmenu
=> Add window and private options for qutedmenu

misc/userscripts/qute-keepassxc
Some updates from my development repo for the userscript `qute-keepassxc` including:
- Database Unlock on demand
- rofi menu if multiple accounts match
- Experimental support for TOTP
=> Updates for userscript qute-keepassxc (Auto-Unlock, TOTP, rofi)

doc/help/commands.asciidoc, qutebrowser/components/misccommands.py, qutebrowser/utils/utils.py, tests/end2end/data/click_element.html, tests/end2end/features/misc.feature, tests/unit/utils/test_utils.py
As suggested by @The-Compiler, I split the finished parts off of #6609 and submit them here. For more information see there.
=> Specify elements for `:click-element` via CSS, position and currently focused

doc/help/commands.asciidoc, qutebrowser/commands/__init__.py
If it's not actually repeated and is supposed to be something else, do tell me.
=> Remove repeated item in list

doc/quickstart.asciidoc
=> Fixed #7156: Added zoom keyboard shortcuts to quick start guide

misc/qutebrowser.spec
=> macOS: add MHTML file type to handled files

misc/requirements/requirements-tests-bleeding.txt
https://github.com/pytest-dev/pytest-bdd/issues/542 should be fixed now
=> Use pytest-bdd:master again in bleeding-edge CI runs

qutebrowser/config/configdata.yml, qutebrowser/config/configtypes.py, qutebrowser/mainwindow/tabwidget.py
=> Make elide position in truncated tab title configurable

misc/userscripts/qute-pass
=> Use url netloc as a candidate key for qute-pass

.github/workflows/nightly.yml, scripts/dev/build_release.py, tox.ini
See #6050, still keeping that open to track NSIS changes
=> Drop 32bit Windows release support

qutebrowser/keyinput/basekeyparser.py, tests/unit/keyinput/test_basekeyparser.py
When handling counts during keyparsing we convert the count string to an integer. If the count is too high (i.e. the count string has too many digits), we run into [Python's integer string conversion length limit](https://docs.python.org/3/library/stdtypes.html#integer-string-conversion-length-limitation):
```
ValueError: Exceeds the limit (4300 digits) for integer string conversion: value has
4301 digits; use sys.set_int_max_str_digits() to increase the limit
```
Instead of blowing up with an exception, we now handle this more gracefully by showing an error message.
Reproducer:
```
$ qutebrowser --temp-basedir ":later 500 fake-key -g $(printf '1%.0s' {1..4301})j"
```
**NOTE:**  
I had to rename `_debug_log()`'s `message` argument to `msg`, because pylint yelled at me for …
=> Handle count exceeding string to int conversion

qutebrowser/misc/sessions.py, tests/end2end/features/conftest.py, tests/end2end/features/test_treetabs_bdd.py, tests/end2end/features/treetabs.feature
=> Add end2end tests for tree tabs feature

doc/changelog.asciidoc, doc/faq.asciidoc, doc/help/configuring.asciidoc, misc/nsis/install.nsh, qutebrowser/browser/qtnetworkdownloads.py, qutebrowser/misc/elf.py, qutebrowser/misc/pakjoy.py, qutebrowser/utils/utils.py, tests/end2end/features/prompts.feature
Fix a few misspelled words I noticed. Shouldn't change any code.
=> Fix some spelling errors

misc/org.qutebrowser.qutebrowser.desktop
This is decent webp viewer, like other web browser.
=> desktop: qutebrowser as webp mime type viewer

doc/changelog.asciidoc, qutebrowser/browser/shared.py, qutebrowser/browser/webengine/interceptor.py, qutebrowser/browser/webengine/webview.py, tests/end2end/data/misc/xhr_headers.html, tests/end2end/features/misc.feature, tests/unit/browser/test_shared.py
=> Respect Accept-Language set via XHR
