qutebrowser/browser/hints.py

Corrected CSS property from 'texttransform' to 'text-transform'

Fixed uppercase hints option

---

qutebrowser/config/config.py
qutebrowser/config/configdata.py
qutebrowser/mainwindow/tabwidget.py

I already committed this, but as per certain things expressed in IRC, I decided to resubmit it after changing small formatting things and splitting it into 'one commit per feature' :)
You may now toggle boolean values with the `:set` command by appending an exclamation point to the option name (ex: `:set tab auto-hide!`). You may also entirely disable the tab bar with the `tab perm-hide` variable.

toggle boolean with :set & 'permanent' tab bar unconditionally

---

qutebrowser/browser/downloads.py
qutebrowser/browser/webpage.py
qutebrowser/config/configdata.py
qutebrowser/config/configtypes.py

This should address issue #505.
If a directory is given as the second argument to the `:download` command there will be an error. I don't really know how to fix that in a nice way. But maybe that is the desired behaviour, as the documentation says you should give a file path.

Download filename handling

---

qutebrowser/utils/urlutils.py

Closes #544. We might also merge #542 now.

Handle URLs with double-colon at the beginning as search strings

---

qutebrowser/browser/history.py
qutebrowser/completion/models/urlmodel.py

Here's a couple of commits for the histcomplete branch. I cleaned up that confusing comment (which is there in case anyone goes looking for history stats like number if hits for some reason and wonders why we are throwing that info away, for now). And added some code to remove duplicates, both when iterating `WebHistory` and in the completion model.

Histcomplete some fixes for #547

---

doc/qutebrowser.1.asciidoc
qutebrowser/config/websettings.py

There is a database created by QtWebkit in the cache folder called WebpageIcons.db. It has a table called PageURL, which stores a history of all visited URLs. The private-browsing setting does not stop this behaviour.  
Passing a blank string to "QWebSettings.setIconDatabasePath" stops the creation of the icon database in the cache folder. This change should fix the problem.

Stop the icon database from being created when private-browsing is set to true

---

doc/help/settings.asciidoc
qutebrowser/config/configdata.py
qutebrowser/mainwindow/tabbedbrowser.py
qutebrowser/mainwindow/tabwidget.py

When the setting is set to true (as by default), nothing changes and the mousewheel can be used for switching between tabs.
When it is disabled, the scroll event does not switch between tabs but is forwarded to the currently focused tab.
Feedback is appreciated. :)

Add setting to enable/disable mousewheel tab switching. See #374

---

qutebrowser/browser/commands.py

So you can scroll down & navigate when you're at the bottom.
To bind this to space:
scroll-page --navigate next 0 1
<Space>
Not sure if it's a good idea to bind this by default? May surprise some
people...
See #696

Add navigate option to scroll_page()

---

doc/help/settings.asciidoc
qutebrowser/browser/webpage.py
qutebrowser/config/configdata.py

I got too annoyed with the messages in the statusline ... :-/

Add ui.modal-js-dialog to restore the default JS dialogs

---

doc/help/commands.asciidoc
qutebrowser/browser/commands.py
qutebrowser/config/configdata.py

... As I want to copy only the domain fairly frequently.
I also changed the message in the statusline to show the actual text being
copied, which I find helpful. But if you disagree, then just undo it (it's not
that important or anything).

Add --domain to yank to yank only the domain

---

qutebrowser/browser/downloads.py

When downloading a bunch (7 or 8) of files I noticed qutebrowser was using a lot
of CPU (>60%).
I did some looking, and in the `downloadProgress` callback qutebrower emits the
updated signal which causes everything to be updated. We don't really need this,
since _update_speed() calls it every 500ms anyway.
I tested by downloading 3 copies of the 1GB file [on this
page]( http://www.thinkbroadband.com/download.html ) qutebrowser consistently
pulls about 25% CPU on my system.
When removing this call, the system pulls about 17% CPU. Not a great amount, but
still significant enough to warrant a pull request ;-)
Some other notes:
- wget uses about 1.5%-2% for each process when downloading.
- When not doing any UI updates & speed calculations qutebrowser uses about 15%.
- Doing some quick …

Use less CPU when downloading files

---

doc/help/settings.asciidoc
qutebrowser/config/configdata.py
qutebrowser/config/configtypes.py
qutebrowser/config/websettings.py

This sets the third-party cookie policy.
- I created a new ThirdPartyCookiePolicy() class, since this setting seems to be
unique in the way it is set...
- I set the default to 'never', which is the most secure/private setting, but
*may* break *some* features of a (very) limited number of sites; these are
usually "non-critical" features.
For example, on Stack Exchange sites you're logged in all 200+ sites if you
sign in on one of them, this features required 3rd party cookies. You can
still sign in with out, but you have to do so 200+ times (this is actually the
only example I've ever noticed).
AFAIK all "major" browsers accept 3rd-party cookies by default, except for
Safari. Firefox also made this change, but reversed it (see:
https://brendaneich.com/2013/05/c-is-for-cookie/), but they …

Add setting: 'content.third-party-cookie-policy', fixes #607

---

qutebrowser/mainwindow/statusbar/bar.py

Now, only Labels and Edit Lines are given additional styling -- not every child widget.

More specific statusbar styling: resolves #750.

---

README.asciidoc

The second link to the contribution guidelines  was pointing to the nonexisting doc/contributing.asciidoc.

Fix link to contribution guidelines in README

---

INSTALL.asciidoc

I added qutebrowser to the main Gentoo repo recently so using an overlay isn't needed.

doc: update Gentoo install instructions

---

qutebrowser/mainwindow/tabbedbrowser.py

IMHO this makes much more sense; for example, if you close the last tab but then
press u to "undo" it, you'll actually load the second-last tab. To undo you need
H for "back". Other things like gC, session save, etc. also behave in a way that
is, IMHO, unexpected...
I can also make a new option out of this, if you prefer. But I don't think that
many people would expect the current behaviour...

Always remove the last tab, instead of opening a new page in it.

---

qutebrowser/mainwindow/tabwidget.py

Here's a patch which seems to work well in my initial testing. We now use the
font size rather than the tabbar size, since the tabbar size is the window
size when it's vertical.
This also works nicer with the new tabs.padding setting (which didn't exist when
I wrote the first patch).

Favicon sizing is messed up with tabs -> orientation = west #847

---

CHANGELOG.asciidoc
qutebrowser/browser/commands.py
qutebrowser/utils/urlutils.py
tests/utils/test_urlutils.py

This prevents a host like "myfoo42.bar" changing to "myfoo43.bar" when
pressing Ctrl-A. It further prevents increasing the port number, e.g.
going from "foo.bar:8080" to "foo.bar:8081".
This should fix #850.

Ctrl-A only increments number in path segment (Fixes #850)

---

qutebrowser/browser/commands.py
qutebrowser/config/configdata.py

If no count or index is given, tab-focus switches to the next tab (using
tab-next internally). So the keychain gt behaves as gt in vim:
- gt focuses the next tab
- 1gt focuses the first tab
- <n>gt (e.g. 5gt) focuses the n'th (e.g. fith) tab

Make tab-focus (bound to gt) behave as in VIM

---

qutebrowser/completion/completionwidget.py

Having a light Qt theme but a dark qutebrowser theme, one can see an
ugly white border around the completion widget which is some relict from
the underlying Qt widget QTreeView. As qutebrowser has its own theming
settings for the mainwindow, it should hide the Qt theme as far as
possible.
Be encouraged to rebase this onto the current master if there are new commits in the meantime.

Hide the border of the completionwidget

---

qutebrowser/mainwindow/statusbar/progress.py

Formerly, the statusbar height changed when the progressbar was visible.
This was caused by the default font-size of the progressbar text (though
invisible). Now, the font-size is set small enought such that the
statusbar height does not change anymore.
With empty qutebrowser configuration, I got the following statusbar behaviour on reloading:
After the attched patch, the statusbar height does not change anymore.

Fix progressbar height to statusbar height.

---

qutebrowser/html/version.html

If you call the page "qute:version" the link to the full GPL license works fine, but if you call "qute://version" it doesn't work. This pull request will fix this little issue.

Fix license issue

---

misc/userscripts/view_in_mpv

Userscript for qutebrowser which views the current web page in mpv using sensible mpv-flags. While viewing the page in MPV, all `<video>`-tags in the original page are temporarily removed. By clicking on such a removed video restores the respective video.
Most of my machines are to slow to play youtube videos using html5, but they work fine in mpv (and mpv has further advantages like video scaling, etc). Of course, I don't want the video to be played (or even to be downloaded) twice — in MPV and in qwebkit. So I often clos the tab after opening it in mpv. However, I actually want to keep the rest of the page (comments and video suggestions), i.e. only the videos should disappear when mpv us started. And that's precisely what the present script does.

Add view_in_mpv userscript

---

doc/help/settings.asciidoc
qutebrowser/browser/adblock.py
qutebrowser/browser/network/networkmanager.py
qutebrowser/config/configdata.py

The config option "content host-blocking-whitelist" may contain comma
separated domains that are exempt from host blocking.
The listed domains may contain the wildcards "*" and "?" to match many
and one character, respectively.
~~You need to run :adblock-update after modifying the list.~~
:adblock-update no longer needed since the code is now in `networkmanager.py`
Should fix #948, though the exact config option might need to be tuned a bit - should the wildcards be kept, should we use a filepath instead (so a user can have a `~/.host_whitelist` or something like that), ...
The local domains are still hardcoded in `adblock.py` and cannot be removed with this config setting.

Add adblock host whitelisting

---

qutebrowser/browser/commands.py
qutebrowser/mainwindow/mainwindow.py

Previously, every tab had its own search term. This sets single search term per
window. using `/hello`, `gt`, and `n` will search for `hello` in the 2nd tab.
This fixes issue #940

Use a single search term per-window

---

misc/userscripts/open_download

Yet another userscript. It offers a menu with all files in your download directory and opens the selected file using `xdg-open`. It works both as a userscript and as a standalone script.

Add open_download userscript

---

tests/unit/config/test_configtypes.py

Fixes #967. Tests are not dependent on the regex cache anymore.

Use RegexEq in configtypes tests

---

qutebrowser/utils/version.py
tests/unit/utils/test_version.py

First contribution, low hanging fruit.
ref: https://docs.python.org/3/library/platform.html#unix-platforms
Would I need to change here too?
https://github.com/The-Compiler/qutebrowser/blob/6d1b0ba2603a93d9e4c85ac28cb38c4b14d295d5/tests/unit/utils/test_version.py#L469

Fixes #977 with non deprecated call.

---

qutebrowser/config/configdata.py
qutebrowser/mainwindow/tabbedbrowser.py
qutebrowser/mainwindow/tabwidget.py

Fix #894, add scroll_pos to title-format and connect page.scroll_pos_changed to update_tab_title
I wont use this feature, but it was interesting

add scroll_pos to title-format (fix #894)

---

INSTALL.asciidoc

Update INSTALL.md to recommend installing source-highlight before building the docs.

Document the need for source-highlight to be installed for asciidoc2html to work fully

---

qutebrowser/mainwindow/tabwidget.py

Occasionally there are extra pixels leftover in the tab bar on the right (see screenshot: http://lawrence.lu/sc/8a54bb3a04.png). This is due to the tab width being an integer and the window width is not always divisible by the tab count. This is fixed by adding an extra pixel to a subset of tabs.
Screenshot afterwards: http://lawrence.lu/sc/2bc9b8bf41.png

removes extra space in tab bar when window width % tab count != 0

---

doc/help/commands.asciidoc
doc/userscripts.asciidoc
qutebrowser/browser/commands.py
qutebrowser/browser/hints.py
qutebrowser/commands/userscripts.py

Userscripts can now be stored in the data directory (for example: ~/.local/share/qutebrowser/userscripts) and called from there or using an absolute path.

Issue #943 and changed the docs accordingly

---

qutebrowser/completion/models/urlmodel.py

This fixes issue #1008.
I found that this bug only happens when I click on the name of the bookmark.
It does not happen when I click on the URL.
It it probably because I can select both the name and the URL with the mouse.

Fixed issue #1008.

---

qutebrowser/config/configdata.py
qutebrowser/config/configtypes.py
tests/unit/config/test_configtypes.py

No more crash when 'completion->timestamp-format' is set to '%'.
Fixes #1039.

Add TimestampTemplate config type (#1039)

---

qutebrowser/mainwindow/tabwidget.py
tests/helpers/stubs.py
tests/unit/mainwindow/test_tabwidget.py

I could've done something like `opt.icon = QIcon()` too, but I didn't feel like modifying `opt` in `_tab_layout`, so I went the `icon_rect = None` route.
Fixes #1015.

Fix crash with small icons (#1015)

---

qutebrowser/browser/hints.py

I think it makes more sense to filter for any text within a link rather
than just the text at the beginning. I've been playing around with this
a little and I like it a lot better.
When using numbers as link hints, It would be awesome if the link hint
strings themselves could also be updated based on how many links are
left, but I'm still figuring out how to do this.
What do you think?

Flexible Link Hint Filtering

---

doc/help/settings.asciidoc
qutebrowser/config/configdata.py

https://www.duckduckgo.com gives a `301 Moved Permanently` to https://duckduckgo.com.
This made things more complicated for another improvement I'm working on at the moment.

Use duckduckgo.com instead of www.duckduckgo.com

---

qutebrowser/mainwindow/tabbedbrowser.py

This is the improvement I've been talking about in the IRC.
The idea is the following: Given you have the setting `last-close` with one of the values `blank`, `startpage` or `defaultpage`, when you close the last tab, a new tab is created. If you undo closing the last tab, this created tab is still there. With this patch the created tab gets removed again, given that it has not been used.
I only modified the `undo()` function. There are 3 things that are checked before the closed tab is restored:
1. Is there only one tab open?
2. Does this tab have an empty history?
3. Does this tab have the url of a tab that is created when the last remaining tab has been closed?
If all conditions are true, the tab is removed. I think we need all these checks to prevent tabs from being removed …

Remove unused tab on undo

---

qutebrowser/browser/cache.py
tests/unit/browser/test_cache.py

These are the first four unit tests for module browser.cache. From what I can see the remaining tests all require construction of files, QIODevices with files or valid QNetWorkCacheMetaData, which is a bit beyond my understanding of pyqt and the qute codebase right now.

First batch of unit tests for browser cache

---

doc/help/commands.asciidoc
qutebrowser/browser/downloads.py
qutebrowser/config/configdata.py
tests/unit/config/test_config.py

Fixes #1013.
If this gets merged, the --all option from download-remove could be removed. This will however break the 'cd' key binding from existing configurations. Is there a way to change it automatically or it should be left as it is?

Implement :download-clear command.

---

qutebrowser/browser/network/qutescheme.py

I was looking at implementing a new qute: handler for downloads, so I was studying the handlers file. Imho, registration decorators are easier to maintain than a global constant.

Avoid separated registering of qute: handlers

---

qutebrowser/browser/cache.py
scripts/dev/check_coverage.py
tests/unit/browser/test_cache.py

This includes a few more tests and fixes all the tests that weren't actually using qutebrowsers DiskCache class but rather Qts QNetworkDiskCache (thus not actually testing any code paths in cache.py).
It's not 100% coverage of cache.py yet, but much closer. Missing paths (WIP):
ref #999

Follow-up to test-browser-cache

---

qutebrowser/qutebrowser.py

`prog` parameter in `ArgumentParser` is `"usage: qutebrowser"` but the word `usage` gets already printed in the help message generated from argparse. So the output of `qutebrowser --help` ends up starting with `usage: usage: qutebrowser`. This PR fixes it.

Remove unnecessary 'usage:' from argument parser.

---

qutebrowser/browser/webview.py

This is a purely personal preference, but rather than open an issue and suggest it I thought I would just open a PR and you can decide to include it or not! :smile: It really bugged me every time I saw an 'error' in the log, which was just the result of a failed search. I changed the log level to 'info' first, but i think 'warning' highlights it better, without actually reporting an 'error'.
Now - as I say - this is purely a personal thing, please feel free to close the PR without merging if you don't agree, I won't have any problem with that. Thanks for all your work.

Change error to warning for text not found on page

---

qutebrowser/config/config.py
qutebrowser/config/sections.py

Calling remove_option() from config.config.ConfigManager raises a TypeError since 'Key Value' object does not support item deletion. This function isn't currently used in the project.

Fix TypeError in ConfigManager.remove_option

---

qutebrowser/browser/commands.py
qutebrowser/utils/urlutils.py
tests/integration/features/conftest.py
tests/integration/features/yankpaste.feature
tests/unit/utils/test_urlutils.py

This patch fixed a problem when pasting a local path that ends with newline (I think it is safe to strip paths as well). Do you think that it would be maybe better to strip only newlines and not all whitespace characters?
The second functionality added is the possibility to paste multiple URLs separated by newline. The paste command now splits the content of the clipboard on newlines and open each element while respecting the supplied options (window, tab, bg tab).
hcraT
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1217)

Implement pasting of mulitple urls

---

qutebrowser/browser/commands.py
qutebrowser/config/configdata.py
tests/integration/data/paste_primary.html
tests/integration/features/yankpaste.feature

This is the ugly hack to fix the annoying behaviour of [Shift+Ins pasting wrong selection](https://bbs.archlinux.org/viewtopic.php?pid=1597753#p1597753). It works pretty well for me, though there might be some problems with editability checks on some pages (I haven't figured out if I need to check also `elem.is_content_editable()` or not).
You might want to update other parts of the documentation, or just point them out and I'll try to do so. I'll also happily address any "nitpicks" ;-)
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1271)

Make Shift+Ins paste primary selection in insert mode

---

qutebrowser/browser/pdfjs.py
qutebrowser/utils/version.py
scripts/dev/update_3rdparty.py
tests/unit/utils/test_version.py

This adds the file path to the pdfjs version output (or "bundled" if a bundled version is used).
Additionally, I've modified the `update_3rdparty` script so that a specific pdfjs version can be installed, e.g. for debugging purposes.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1276)

pdf.js fixes

---

qutebrowser/config/configtypes.py
qutebrowser/misc/editor.py
tests/unit/config/test_configtypes.py
tests/unit/misc/test_editor.py

I tried to set my editor to `termite -e "vim -f {}"`, termite being a
pretty cool and light terminal I use within my i3wm Arch linux box.
So when I open my editor I want it to launch a terminal with Vim inside
instead of GVim for various reasons.
The validation rejected this at first because it was looking for '{}'
inside ['foo', 'bar', 'baz {}'], essentially. So I need it to look
inside the sub-strings, not just the list.
Then after validation I need to perform the '{}' replacement inside the
sub-string too, not just replacing the whole string.
--------------------
I'm not sure what I'm supposed to do testing wise, I haven't written production Python for quite a few years. Let me know if there's anything you'd like me to do or if this approach is a bad one! Happy to change it, I just …

Relax editor templating

---

qutebrowser/browser/network/qutescheme.py
qutebrowser/browser/pdfjs.py
tests/unit/browser/network/test_qutescheme.py
tests/unit/utils/test_version.py

(Issue #1280)
This PR attempts to fix the issues raised in the discussion of #1280.
I've used an Exception to signal the qute handler that an `ErrorNetworkReply` should be used, as that seemed to be the cleanest way.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1290)

Pdfjs fixes

---

tests/unit/mainwindow/statusbar/test_textbase.py

When testing in fullscreen layout on my tiling window manager, the `'Hello world! ' * 20` wasn't enough to create an ellipsis. It does work for `Hello world! ' * 100`, but that's not really a great fix. I'll look into a container to ensure the window size, so consider this a work in progress.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1313)

no ellipsis is inserted in "big" windows

---

qutebrowser/browser/downloads.py
tests/integration/data/downloads/issue1214.html
tests/integration/features/downloads.feature
tests/integration/features/misc.feature

Issue #1214
Now uses a sensible filename for `data:` links instead of the whole base64 content. For PDF.js, it even uses the correct pdf filename.
The "pdf.js test" is still a work in progess, as it constantly fails due to a Qt warning:
It produces a "QPainter::end: Painter ended with ? saved states"  (*emoji unintended*) warning while running the "Downloading a pdf via pdf.js button" test here, tested with
```
Arch Linux (32 and 64 bit)
CPython: 3.5.1
Qt: 5.5.1, runtime: 5.5.1
PyQt: 5.5.1
```
and
```
Ubuntu 15.10 32 bit
CPython: 3.4.3
Qt: 5.4.2, runtime: 5.4.2
PyQt: 5.4.2
```
Normally, the message says "2 saved states", but I could also get "4 saved states" when running with `--qute-delay=50`. When running with `--qute-delay=100` or higher, the tests seem to pass fine.
[<img …

downloads: fix filename for data: links

---

CHANGELOG.asciidoc
qutebrowser/browser/downloads.py

Issues #1269, probably #866
qutebrowser would crash when `XDG_DOWNLOAD_DIR` was set to some
non-absolute value (which should not happen, but it can) and
`storage -> download-dir` was empty, since when the user didn't give an
absolute filename, even the joined path of `download_dir()` (i.e.
`XDG_DOWNLOAD_DIR` in this case) and the filename was not absolute either.
Since the path was not absolute, `create_full_filename` returned `None`,
which meant that `os.path.basename(self._filename)` raised an exception.
Now we display an error message and fall back to $HOME.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1323)

downloads: handle relative XDG_DOWNLOAD_DIR

---

doc/help/settings.asciidoc
qutebrowser/config/configdata.py

The current help text doesn't match the actual funcionality of the option. Picture as proof (it shouldn't be possible to see a single hint if the option is `true`):
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1306)

hints->auto-follow - let help text match reality

---

qutebrowser/misc/editor.py
qutebrowser/misc/guiprocess.py
tests/unit/misc/test_editor.py

This patch attempts to fix an issue where an error occuring in
misc/guiprocess or the editor process crashing would delete the
temporary file thus making it impossible to recover changes not commited
to the form field from the editor.
In its current form, it doesn't pass tests because of an issue.

misc/editor: Fix tempfile deleted on error / editor crash

---

qutebrowser/config/configtypes.py
tests/unit/config/test_configtypes.py

allow {0} in search engine specification strings to allow multiple instances of the search term in the url.
also includes changes to accommodate this in the unit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1348)

allow {0} in search engine specification strings

---

tests/integration/features/tabs.feature

This adds feature tests for the `background-tabs` and `new-tab-position` settings.
I'm using hints to select and open the link. Not sure if there is a more concise way to achieve the same result.
Issue-Link: https://github.com/The-Compiler/qutebrowser/issues/999
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1361)

Add background-tabs and new-tab-position feature tests

---

misc/userscripts/openfeeds

Currently, the openfeeds userscript only works when a complete url is given. When an url such as:
- /feeds
- //hello.world/feeds
- ../feeds
is given, qutebrowser will search, or (try to) open a file. This fixes this.

Complete url's in openfeeds userscript

---

qutebrowser/commands/userscripts.py
qutebrowser/utils/standarddir.py
tests/unit/utils/test_standarddir.py

This implements a system-wide data location (/usr/share/qutebrowser) when running on Linux, and the userscript command has been modified to search in this location if it cannot find a script in the user-specific path that the standarddir.data() returns.
For non-Linux systems and Linux systems where nothing was installed to /usr/share/qutebrowser, the system_data() function defaults to calling data() for the user-specific path. This insures that there is always _something_ usable returned by this function, even if the path is not system-wide. 
Packagers would need to create this path (/usr/share/qutebrowser) on Linux systems, and install the userscripts directory to this location. In the future, other files could be placed here (global qutebrowser.conf, anyone? :P)
---
This change is [<img …

Allow searching system-wide data path on Linux for userscripts

---

qutebrowser/browser/network/filescheme.py
qutebrowser/html/dirbrowser.html
qutebrowser/utils/jinja.py
tests/integration/data/click_element.html
tests/integration/quteprocess.py
tests/integration/test_dirbrowser.py
tests/integration/test_quteprocess.py
tests/unit/browser/network/test_filescheme.py

Issue #1334
The problem was that there were too few slashes. On Linux, absolute
paths start with /, so
file:// + /home
gives file:///home, which is a valid path. On windows however, absolute
paths start with a drive letter, so
file:// + C:/Users
gives file://C:/Users, which is parsed as "host C, path Users", which is
why it could be written as file://c/Users (strip out the empty "port"),
giving us an invalid path.
The solution is to add the third slash in the template, and strip the
redundant slash on unix systems.
Additionally, this fixes a bug where navigating from '/home/' to the
parent directory would give '/home' instead of '/'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …

Fix dirbrowser navigation on Windows (#1334)

---

README.asciidoc
doc/help/commands.asciidoc
qutebrowser/app.py
qutebrowser/browser/commands.py
qutebrowser/completion/models/instances.py
qutebrowser/completion/models/miscmodels.py
qutebrowser/mainwindow/mainwindow.py
qutebrowser/mainwindow/tabbedbrowser.py
qutebrowser/utils/usertypes.py
tests/integration/features/tabs.feature

This is so you can jump between tabs based on tab title or URL instead
of just index just like the `buffer` command in vim. Adds a `b` alias
for `tab-focus` to be more like vim too.
The method of updating the completion model (rebuild the whole thing
every time a tab is created, removed or updated) is inefficient but is
still very fast for even unreasonable numbers of open tabs.
TODO: I did a quick test and it doesn't seem to work with multiple windows.
Probably because of how I am getting the `win_id`. Can anyone tell me how
to get the _current_ `win_id`?
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1317)

Adds completion for tab-focus.

---

README.asciidoc
doc/help/commands.asciidoc
qutebrowser/browser/hints.py
qutebrowser/browser/webelem.py
tests/integration/data/hints/link_blank.html
tests/integration/data/hints/link_span.html
tests/integration/features/hints.feature
tests/unit/browser/test_webelem.py

Fix for #676
It removes the target of the link, like VimFX, as to prevent the website to overrule the user. Thanks to @The-Compiler to point me to QWebElement. I guess one of the following things should be done:
- add setting to enable/disable this behaviour
- add "hint all current"
I'm not sure what you would prefer, so I'll wait for some comments.

[WIP] force link to open in current tab

---

misc/userscripts/password_fill

This adds support for for libsecret keyrings (GNOME keyring and others), using `secret-tool`, to the `password_fill` userscript.

Implement libsecret password backend

---

CONTRIBUTING.asciidoc
INSTALL.asciidoc

New contributors might like to be reminded to redirect the config
access of their locally-built qutebrowser to avoid overwriting their
global settings.
I started hacking on qutebrowser and quickly found out that I was overwriting my `~/.config/qutebrowser` and breaking my 'non-development' version'. It might be nice to remind new contributors of this.

Add note about redirecting config for testing.

---

doc/help/commands.asciidoc
qutebrowser/browser/commands.py

The edit-url command opens a url (by default, the current url) in the
user's external editor and navigates to the result when the editor is
closed. This makes it easy to tweak the current url to navigate within
a site.
`edit-url` accepts the same flags as `open` (e.g. -t will open in a new
tab.
One may provide a url as an argument to create a shortcut to
pre-populate part of a url and allow filling in the rest.
There is no default keybinding.
Resolves #1261.

Implement edit-url to craft a url with an editor.

---

.editorconfig
MANIFEST.in

Here is my [editorconfig](http://editorconfig.org/) file from the other PR. These are the settings I could infer, but if anything is wrong let me know! With editorconfig it's also possible to have different configs for different files (ex: size 2 spaces for yml and size 4 spaces for .py). If there are any other special cases like that, I can write them in, but this seems to match what I see so far.

Add basic editorconfig for enforcing style

---

doc/help/commands.asciidoc
qutebrowser/browser/commands.py
tests/integration/features/tabs.feature

This makes it possible to jump to the very last tab, as opposed to the
last focused tab, by using -1 as the index. Generally negative indexes
are counted from the end.
Solves issue #1166

Make tab-focus count from end with negative index

---

qutebrowser/app.py

When a url is opened from the command line, it should probably be opened explicitly. This should address the first part of issue #1272. Maybe this should depend on the value of open_target, though?

Open command line urls explicitly.

---

scripts/dev/update_3rdparty.py

If update_3rdparty.py isn't run in the right directory pdf.js isn't downloaded into the right directory. With this change the script chdirs to the expected directory before downloading.

Make update_3rdparty.py install correctly when run from any directory

---

qutebrowser/browser/commands.py
qutebrowser/commands/runners.py
tests/integration/data/title with spaces.html
tests/integration/features/conftest.py
tests/integration/features/spawn.feature

Related to issue #1372.
I've been trying to add tests like the following but I keep getting "Error while splitting command: No closing quotation" from [here](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/browser/commands.py#L994). Any idea what could be wrong?
```diff
diff --git a/tests/integration/features/spawn.feature b/tests/integration/features/spawn.feature
index 03506c1..9df270e 100644
--- a/tests/integration/features/spawn.feature
+++ b/tests/integration/features/spawn.feature
@@ -16,6 +16,16 @@ Feature: :spawn
When I run :spawn echo {url}
Then "Executing echo with args ['about:blank'], userscript=False" should be logged
+    Scenario: Running :spawn with url variable in fully encoded format
+        When I open data/title with spaces.html
+        And I run …
```

Allow {url:pretty} variable in commands

---

qutebrowser/mainwindow/tabbedbrowser.py
tests/integration/features/tabs.feature

Avoid a crash when undoing twice on the default page with last-close set to
default-page.
This was caused by logic to reuse the current tab if it is on the default page
and has no history. The fix is using openurl rather than removeTab/tabopen.
Resolves #1423

Don't crash when undoing twice on default page.

---

qutebrowser/browser/cache.py
tests/integration/test_invocations.py
tests/unit/browser/test_cache.py

Issue #1412
When passing `--cachedir=""` on the command line, `standarddir.cache()`
returns `None`, which stands for "deactivate cache" and has to be
properly handled in `DiskCache.__init__()` (i.e. don't pass it to
`os.path.join`)

cache: fix crash when cache_dir is None

---

qutebrowser/completion/models/miscmodels.py

Allows to use ctrl+d to close tabs from the buffer completion widget
when they are selected. Respects current tab settings like whether you
can close the last tab in a window.
Had to change the `rebuild()` method to use `setData()` when possible
because the selection was being lost if the whole model was being rebuilt.
Current problems are:
1) When opening a new window while you already the tab completion open on
one window a category is added for the new window but new rows in
that category aren't picked up. Interesting if you open a third
window then close the second window the completion display is now
correct... I can see that the model is being updated correctly but I
am not sure why that isn't propagating to the view. Not sure whether
it is worth looking into (further) either.
2) …

buffer completion: handle deleting items see issue #1443

---

qutebrowser/keyinput/basekeyparser.py
tests/unit/keyinput/test_basekeyparser.py

Now `3<ctrl-o>` will execute whatever `<ctrl-o>` is mapped to with count=3.
Resolves #57

Handle counts for special keys.

---

qutebrowser/config/configtypes.py
tests/unit/config/test_configtypes.py

Allow a variable amount of whitespace for rgb, rgba, hsv, and hsva
strings in the config.
Previously only 'rgb(0, 0, 0)' was allowed. Now things like
'rgb(0,0,0)' are permitted.
The repeated 3-digit segments of the regexes were separated out to
reduce repetition and line length.

Allow flexible whitespace in color strings.

---

qutebrowser/browser/downloads.py
qutebrowser/browser/network/networkmanager.py
tests/integration/features/downloads.feature
tests/integration/features/test_downloads.py

Issue #1413
This happens when the networkmanager is used by something that has no
tab_id, like the generic DownloadManager. In this case, we should just
skip the webview connection (as it makes no sense) instead of crashing
(which is the last thing we want to do).
**The test is still flaky (it somehow produces a unclosed resource warning), I will need to look into this some more** - but the main test works.

Fix downloading a page with SSL errors (#1413)

---

scripts/link_pyqt.py

This fixes a bug where `link_pyqt` crashes when the path to the python
interpreter contains a space.

link_pyqt: fix crash with spaces in pypath

---

qutebrowser/browser/downloads.py
qutebrowser/mainwindow/mainwindow.py

Fixes #846
`.rowCount()` returns all downloads, even the finished ones that have not
yet been removed from the list. For confirming the quit event, we should
only consider downloads that are still running.

fix confirm-quit=downloads with finished downloads

---

qutebrowser/completion/models/instances.py
qutebrowser/config/parsers/keyconf.py
qutebrowser/utils/usertypes.py
tests/integration/features/keyinput.feature

This is a simpler alternative to #1446. Instead of showing the current binding in the completion menu, you can print the binding with `bind [--mode=mode] <key>`.
This also adds command completion to bind, so `bind <key> ` will offer all commands as completions. Unlike #1446, the list it is not filtered by mode.

Show binding2

---

qutebrowser/mainwindow/statusbar/command.py
tests/integration/features/misc.feature

Fixes #123 and partially fixes #1483.
I tried splitting arguments with `shlex.split()` but I had some problems with
quotes.  I had to use `posix=False` to keep them from disappearing, but even
then tests like
```
When I run :set-cmd-text -s :message-info "foo
And I run :set-cmd-text -a bar"
```
failed because of unmatched quotes.  So I used `srt.split()` instead, which
seems OK to me in this context.
I will open a separate pull request for decoding hovering URLs later.

Properly replace variables in set-cmd-text command

---

qutebrowser/browser/commands.py
qutebrowser/browser/network/qutescheme.py
qutebrowser/utils/log.py
tests/integration/features/conftest.py
tests/integration/features/misc.feature

This adds a `level` query parameter to qute://log and qute://plainlog.
For example, `qute://log?level=warning` will show an html page containing
log entries with severity warning or greater.
If the query is omitted, the original behavior of `qute://log` is preserved.
`:messages [level]` is a command that opens `qute://log?level=<level>`.
By default, level defaults to 'error' as an easy way to see missed
error messages.
Resolves #64

Add :messages command to show past messages.

---

qutebrowser/mainwindow/statusbar/url.py
tests/unit/mainwindow/statusbar/test_url.py

Fixes the second part of #1483.
I used `QUrl(link).toString()` for PrettyDecoded format.  Another option was
`QUrl.fromPercentEncoding(bytearray(link.encode()))` that decodes every
possible character (e.g. `<`, `>`, `"`) but I chose the former for consistency
and making sure no ambiguous data is shown.
I also removed the `'Th1$ i$ n0t @ n0rm@L uRL! P@n1c! <-->'` test in
`test_set_hover_url` because now `<` and `>` are shown encoded and it failed.
Without these characters it would work but a decoded argument like this would
never be given to `set_hover_url` by Qt anyway.

Decode URL in statusbar when hovering over it

---

qutebrowser/config/configdata.py
qutebrowser/mainwindow/mainwindow.py
qutebrowser/misc/keyhintwidget.py
scripts/dev/check_coverage.py
tests/helpers/stubs.py
tests/unit/misc/test_keyhints.py

Pop up a small window during a partial match to show possible keychain completions.
Resolves #209 
I remember really liking this in dwb, so I initially went dwb-style, showing completions horizontally in the status bar. However, there wasn't nearly enough room for something like `;`. I guess we just have longer command names than `dwb` did?
So instead I went with a separate semi-transparent window:

Show keychain completions

---

qutebrowser/completion/models/instances.py
qutebrowser/completion/models/miscmodels.py

The command completion menu now uses the misc colum to show a
comma-separated list of normal-mode keybindings for each command.
Continuing the trend of increasing discoverability...
Resolves #45.

Show currently bound keys in command completion.

---

qutebrowser/completion/models/miscmodels.py
qutebrowser/keyinput/basekeyparser.py
qutebrowser/misc/keyhintwidget.py
qutebrowser/utils/utils.py
tests/unit/misc/test_keyhints.py
tests/unit/utils/test_utils.py

Resolve #1507 by preventing the dialog from showing if there are no matches.
The second commit is just for cleanup and replaces an oft-repeated special key check with a utility function.

Keyhint fix

---

qutebrowser/completion/completer.py
tests/integration/features/misc.feature

It doesn't crash, but it also doesn't return a completion model. Is this intended behavior?

fix crash on empty parts[] (#1523)

---

qutebrowser/browser/commands.py
qutebrowser/utils/urlutils.py
tests/integration/features/yankpaste.feature
tests/unit/utils/test_urlutils.py

Adds some options to implement a way to treat multiline text that starts
with a scheme-like line as text instead as an URL.

Tweaks the multi-line heuristic to handle scheme-like text

---

qutebrowser/qutebrowser.py
qutebrowser/utils/log.py
qutebrowser/utils/message.py
tests/end2end/fixtures/quteprocess.py
tests/end2end/fixtures/test_quteprocess.py
tests/end2end/test_invocations.py
tests/unit/utils/test_log.py

Fixes #1501
Enabled via the `--json-logging` parameter.
Opening the PR to let Travis look at it.
Todo:
* ~~Update the test in `test_quteprocess.py`~~
* ~~Tests for `LogLine.formatted_str`~~

log: implement JSON as logging output

---

qutebrowser/browser/mhtml.py
tests/end2end/data/downloads/issue1535.html
tests/end2end/features/downloads.feature

Fixes #1535
The browser crashed because both callbacks were called (finished and
error), trying to remove the item twice from the list of downloads.
I've tried to write a test for this, but it seems like the download from localhost is just too fast, even no delay doesn't work (error on `:download-cancel` because there is no download) (or I'm just missing something here)

mhtml: don't crash when user cancels a download

---

qutebrowser/browser/hints.py
tests/end2end/data/hints/buttons.html
tests/end2end/features/hints.feature

This was disallowed by an assertion, but has a legitimate use case for
clicking multiple buttons or ticking multiple checkboxes.
Resolves #1541.

Allow hint --rapid in normal mode.

---

qutebrowser/config/parsers/keyconf.py
tests/end2end/features/keyinput.feature

Load all special keystrings (e.g. <ctrl-a>) into memory as lowercase,
and automatically lowercase any special keystring given to bind/unbind.
This prevents <ctrl-a> and <Ctrl-A> from being treated differently.
Resolves #1544, where `:bind <ctrl-t>` would not complain even though
`<Ctrl-T>` was bound.

Handle special keystrings case-insensitively.

---

qutebrowser/browser/hints.py
tests/integration/features/hints.feature

Continuing #1311 and making sure that this is not lost. Only the last two commits are relevant:
- [The first](https://github.com/The-Compiler/qutebrowser/commit/ac2c5439dc963229fef50a5afb7f9a6bed1ddea4) moves the click position from the center of the element near the top-left corner, which should help if the element is overlayed with another one (see e.g. #1005).
- [The second](https://github.com/The-Compiler/qutebrowser/commit/5ce3c42d807c85b62db7a9b26ebc497281d6e59a) uses the `getClientRects()` method (introduced in #1311) also for positioning the hint label, which is visually more pleasing but also considerably slower on pages with many links, so I'm not sure if it should be used by default. It should solve at least https://github.com/The-Compiler/qutebrowser/issues/824#issuecomment-208 …

Hints positioning

---

qutebrowser/commands/runners.py

[Issue #1386 ](https://github.com/The-Compiler/qutebrowser/issues/1386)
If there's only one result (I tried it with :bac for :back as Jumblemuddle mentioned), hitting enter will replace the command with the only suggested completion.

Match partial results in completion (#1386)

---

tests/end2end/features/hints.feature

After ee8247525e0a9894730fa5981bcdb3546b2d52a9, the given reason (clicking an iframe to get a focus) applies to only one test, the others are either stable or flaky for a different reason.
Letting Travis to take a look at it...

tests: un-xfail some iframe tests (#1525)

---

qutebrowser/browser/history.py
qutebrowser/completion/models/urlmodel.py
qutebrowser/misc/lineparser.py

These two commits add the history clear command, if you are willing to pull this I would be willing to write any required unit tests for it.
To fully implement anything like #58 would take a rather interesting rework of AppendLineParser.
I decided to forego this for a simpler approach for now.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-compiler/qutebrowser/1264)

Added history clear command

---

qutebrowser/browser/history.py
qutebrowser/browser/webview.py
qutebrowser/completion/models/urlmodel.py

Changes history items to be added when initialLayoutCompleted is fired as opposed to when navigation is initiated. Regarding #1345 this method saves the final url after redirects and doesn't save the url of the redirect.
There are some things I am unsure about:
* Encoding. I haven't tested the serialization with unicode titles (and urls) on windows.
* Testing. I was looking at the history behavior for redirects and errors and was wondering if this was worth adding to the test suite and how.
Here is some comparisons with dwb and otter:
Otter (for the qtwebkit backend at least) calls handleHistory() at a few
places but calls after the first one update an entry instead of adding a new
one. It gets called on title changed, navigate (load started I think) and load
finished. Due to events that …

Switch browsing history away from QWebHistoryInterface and add titles.

---

qutebrowser/config/config.py
tests/end2end/features/set.feature

It appears that since the introduction of the ability to toggle a config value, the config toggling code sets the specified setting to "True" if it was false and "False" if it was true, although this is not incorrect, it doesn't match the stylistic choice throughout qutebrowser to use lower case "true" and upper case "false" for settings.
This pull request attempts to solve this inconsistency.

Fix toggle config using capitalised boolean value.

---

qutebrowser/browser/hints.py
tests/end2end/data/hints/html/with_spaces.html

This won't hurt and will help with some poorly formatted sites
including blank spaces around the url (e.g. the Previous link in a
dashboard make with CDash 2.0.2).

Strip the url before processing it

---

qutebrowser/config/configdata.py

- Use the whole home-row
- Produce easier chords
- 2-key chords alternate hands first (f-[aoeui]-[dhtns])
This is indeed a poor patch for easier chords as it should work on
every home-row, but there are not that much home-rows around.

Fix Dvorak hint chars

---

qutebrowser/browser/commands.py
tests/end2end/features/scroll.feature

G accepts a count but gg ignores it. Giving the count priority makes more sense and matches dwb.

Make gg accept count

---

qutebrowser/commands/runners.py
qutebrowser/completion/completer.py
tests/unit/commands/test_runners.py
tests/unit/config/test_config.py

This is a fix for #956.
With recent addition of `history-clear` command I feel that it would be extremely useful to have an alias for `history-clear ;; quit`. However above bug prevented that. I fixed that by simply moving a logic of checking if a given command is an alias from `CommandRunner.parse()` to `CommandRunner.parse_all()`.
Please review the changes and tell how you feel about them. Thanks. :)

Alias multi commands

---

qutebrowser/config/sections.py
scripts/dev/check_coverage.py
tests/helpers/fixtures.py
tests/helpers/stubs.py
tests/unit/browser/webkit/test_history.py
tests/unit/completion/test_models.py
tests/unit/config/test_configtypes.py

This establishes a pattern that can probably be used to test any of the
completion models.
See #999.
Let me know if this pattern looks good, and I'll start testing the other models.

Add unit tests for completion models

---

qutebrowser/misc/readline.py
tests/unit/misc/test_readline.py

Closes #1512 
Now, unix_word_rubout behaves like in bash, eg it deletes the last word in the command line.
For example , if you type 
`:open -t https://github.com/The-Compiler/qutebrowser/`
and your cursor is at the end of the line, hitting c-w will bring you to `:open -t `.
If you liked the previous behaviour, you can use `Ctrl-Backspace`

#1512 Update behaviour of rl_unix_word_rubout

---

tests/end2end/fixtures/quteprocess.py
tests/end2end/fixtures/test_quteprocess.py
tests/end2end/fixtures/testprocess.py

Fixes #1611
This marks errors that are expected by a test with an "(Expected)"
marker and white color (instead of red).
The formatting of the log messages has been deferred to `_render_log`,
since the `.expected` attribute is not correctly set right after we read
the message.

quteproc: mark expected errors as such

---

misc/userscripts/taskadd

The `taskadd` userscript adds a task based on the current title and URL.
It passes additional arguments along to `task`.
For example:
:spawn --userscript taskadd due:eod pri:H
will add a task with high priority due at the end of the day.
The description will be the current page title and it will be annotated
with the current page url.
If used with hints, the hint text is used as the description.
Unfortunately, there is currently no way to use :hint fill and maintain
the hint text, which limits the ability to provide additional args in
hint mode.

Add a userscript to integrate with taskwarrior.

---

README.asciidoc
doc/help/commands.asciidoc
qutebrowser/browser/commands.py
tests/end2end/features/conftest.py
tests/end2end/features/misc.feature
tests/end2end/features/test_misc_bdd.py

I've given #1630 a try, and I hope it's up to quality standards. 
I'm having a lot of trouble writing a test for it. I've never used pytest or BDD, but I figure the strategy would be to open up `hello.txt` or something, run `:print --pdf tmp/dir/hello.pdf`, and wait for the pdf to show up. I can keep trying if the test is necessary, but I'll probably need a few hints.

Add :print --pdf flag to skip printing dialog

---

tests/helpers/fixtures.py
tests/unit/browser/test_adblock.py
tests/unit/browser/test_tab.py
tests/unit/browser/webkit/test_cookies.py
tests/unit/browser/webkit/test_qt_javascript.py
tests/unit/config/test_config.py
tests/unit/config/test_configtypes.py
tests/unit/config/test_configtypes_hypothesis.py
tests/unit/utils/test_standarddir.py

`~/.config/qute_test` and `~/.local/share/qute_test` kept showing up on disk.
They really mess with my tab completion, but took me a while to figure out it was these unittests, as I just kept assuming I forgot to delete them. :smile:.
Also, the fixture to prevent creation of `~/.cache/qute_test` wasn't working because `usefixtures` doesn't work on fixture, as a past version of you [pointed out](https://github.com/pytest-dev/pytest/issues/1014).

Stop creating qute_test!

---

doc/help/commands.asciidoc
qutebrowser/browser/commands.py
qutebrowser/browser/urlmarks.py
qutebrowser/browser/webkit/network/qutescheme.py
qutebrowser/html/bookmarks.html
tests/end2end/features/urlmarks.feature

There is a new page now, qute:bookmarks that will display all bookmarks and quickmarks. It's still missing a search / filter feature, but you can use the built-in search / navigation just as easily for now.

Issue 1033 bookmark display

---

qutebrowser/app.py
qutebrowser/browser/adblock.py
qutebrowser/browser/commands.py
qutebrowser/browser/webkit/downloads.py
qutebrowser/browser/webkit/mhtml.py
qutebrowser/config/configdata.py
qutebrowser/mainwindow/mainwindow.py
qutebrowser/mainwindow/statusbar/prompter.py
qutebrowser/utils/usertypes.py
scripts/dev/misc_checks.py
tests/end2end/features/downloads.feature
tests/end2end/features/misc.feature
tests/end2end/features/test_downloads_bdd.py
tests/unit/browser/test_adblock.py
tests/unit/utils/usertypes/test_downloadtarget.py

Fixes #39.
The file is saved in a temporary directory, which is cleaned up when the
window is closed.
Bind `prompt-open-download` to a key combination (e.g. `:bind --mode prompt <ctrl-o> prompt-open-download`) and press it during the filename prompt to download the file to a temporary location and automatically open it after it has finished downloading.
Todo:

allow downloads to be opened directly

---

misc/userscripts/open_download
misc/userscripts/password_fill
misc/userscripts/view_in_mpv

Fix for https://github.com/The-Compiler/qutebrowser/commit/dfbd31f35f718f49b965f91551951061cd3463bd. On most platforms (according to shellcheck), you can't pass two arguments in a shebang. I.e. on Debian you get:
`/usr/bin/env: ‘bash -e’: No such file or directory`

Don't pass 2 arguments to shebang

---

qutebrowser/browser/commands.py
qutebrowser/browser/urlmarks.py
tests/end2end/data/numbers/18.txt
tests/end2end/features/urlmarks.feature

Issue #1667, to the letter. Adds a return value to BookmarkManager.add to indicate whether the bookmark was added or deleted (which is then used to print the correct message). I didn't change the default keybinding for `M` but I'm not against it.

Bookmark add toggle

---

qutebrowser/browser/commands.py
tests/end2end/data/numbers/19.txt
tests/end2end/features/urlmarks.feature

Uzbl has a very nice feature called temp bookmarks which are deleted once you visit them. Adding a `--delete` flag to `bookmark-load` allows a user to replicate this functionality without creating a new kind of bookmark. This is similar to `bookmark-del` with no arguments, but doesn't require the user to wait for the page to load and also works even if the bookmarked page redirects.
A similar feature might be useful for `quickmark-load` but my impression is that there's no reason to create a shortcut name for a mark if you only plan on visiting it once.

--delete option for bookmark-load

---

misc/userscripts/password_fill

On some websites, e.g. https://www.engie-electrabel.be, you can't login after you filled the login form using `password_fill`. This can be fixed by focusing the input fields, and removing focus afterwards.

Focus field before filling password

---

qutebrowser/utils/qtutils.py
tests/unit/utils/test_qtutils.py

it seems flush might throw which will not be caught inside the (try-)
else branch. (hopefully) fixes config corruption when no space
available.

move savefile flush into try: block

---

qutebrowser/browser/commands.py
tests/end2end/features/open.feature

The function CommandDispatcher.openurl now checks in the quickmarks registry to see if the user's URL matches a quickmark's name. If it does, the quickmark is opened instead, otherwise the function proceeds as normal. This addresses issue #1663.

:open opens quickmark when given a quckmark name

---

qutebrowser/misc/readline.py
tests/unit/misc/test_readline.py

unix_filename_rubout deletes to the previous slash or whitespace,
unlike the previously implemented backwards-kill-word which treats and
non-alphanumeric character as a boundary.
To illustrate, given the text 'foo/bar.baz', unix_filename_rubout will
delete 'bar.baz' while backwards-kill-word will delete only 'baz'.
See #1710.

Implement unix_filename_rubout.

---

qutebrowser/completion/completer.py
qutebrowser/completion/completionwidget.py
qutebrowser/mainwindow/mainwindow.py
tests/helpers/fixtures.py
tests/helpers/stubs.py
tests/unit/completion/test_completer.py
tests/unit/completion/test_completionwidget.py

There are kinda two things going on in this PR (sorry, maybe should've done two).
The first two commits are touching up tests for `Completer`. I took a look at how it actually gets used and saw that the public entry point is `schedule_completion_update` rather than `update_completion`, so in c00ce1e I'm testing that instead. In 124bdf2 I marked functions that aren't used externally as private (but I can omit that commit if you'd rather keep them public).
The second bit adds tests for the `CompletionView`, which was previously untested. I decided to use the real `BaseCompletionModel` and `SortFilter` instead of mocking them out. `test_next_previous_item` is flaky, and occasionally fails with
```
None:None:0:
QtWarningMsg: QItemSelectionModel: Selecting when no model has been set will …
```

More completion tests

---

qutebrowser/browser/commands.py
tests/end2end/features/tabs.feature

Fixes issue #1701. `tab-move` now takes an index, which does an absolute move like `tab-focus` but is overridden by `count`.

Extend tab-move's direction argument to take an index

---

qutebrowser/config/config.py
qutebrowser/config/configdata.py
qutebrowser/config/configtypes.py
scripts/dev/src2asciidoc.py
tests/unit/config/test_configtypes.py
tests/unit/config/test_configtypes_hypothesis.py

As promised, code for #989. In addition to the `List` type, which is basically the same as the one described there, I implemented `LengthList` (no pun intended, seriously) which enforces a length on the value provided it isn't empty. Everything was tested for compatibility by recreating the old classes as subclasses of the new ones, and then those versions and their tests were deleted.
The old classes mostly conflated the inner `none_ok` with the outer one, and I haven't given serious thought to which one is required in all cases. Probably worth looking over. Also, three of the values just used plain `List` when they should probably have stricter requirements; for now they use a new class `BaseList`.

Generalize configtypes.List

---

INSTALL.asciidoc

qutebrowser can be installed via [Homebrew Cask](https://caskroom.github.io/) (see its [cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/qutebrowser.rb)). I added instructions for this to the Install asciidoc (and some headings to give the Mac OS section some structure).

Mac OS install: add Homebrew Cask instructions

---

qutebrowser/completion/completionwidget.py
tests/unit/completion/test_completionwidget.py

I _think_ this fixes both issues while preserving the original behavior of `completion.show` and `completion.auto-open`. For some reason I thought that, with both of these set to `false`, you would still be able to tab complete (but without the completion view showing). However, checking out some older commits it looks like that was never how it worked. Can someone confirm?
Maybe that behavior was something that just happened accidentally when I was halfway through refactoring. Like @mlochbaum , I'm now rather confused about what these settings were ever supposed to do :confused:

Fix completion crashes

---

qutebrowser/browser/webkit/downloads.py

Going for the hat-trick with fixes for #1725, #1726 and #1728 as they are all pretty much one-liners.
I've added the length limitation because we rely on the suggested filename to be valid as there's no way for the user to change the filename (as opposed to a normal download), so for the feature to work, the suggested filename has to "work", so better be safe and shorten it.
I will add tests for the "no crash on cancel" feature in the next days. For the other bugfixes, I'd really like to add tests, but the problem is that we don't control what the OS will do if you open the file. We could probably introduce some "test mode" where the download is not opened but still loaded, so we could make sure that at least the filename doesn't crash qutebrowser, but other than that, I'm not sure how …

Open download fixes

---

qutebrowser/browser/commands.py
qutebrowser/commands/cmdutils.py
tests/end2end/features/tabs.feature
tests/end2end/features/zoom.feature
tests/unit/commands/test_cmdutils.py

As discussed in #1735. I removed the check that ensures `tab-focus`'s argument is an int, since we are going to bounds-check it anyway. ~~The case where `zoom` uses the `ui default-zoom` value was never tested, but this is now caught by coverage since the logic is explicit.~~ (Never mind; it was tested).

Remove cmdutils.arg_or_count

---

qutebrowser/browser/commands.py
qutebrowser/config/configdata.py
tests/end2end/features/open.feature

Some keybindings with `:open -t` or `:open -b` open a tab which is related to the current one. In particular, `hint links fill :open -t {hint-url}` (default `;O`) essentially opens a link with the ability to inspect it first. Adding an `--implicit` flag to `:open`, which treats any new tab opened by the command as implicitly opened, lets these commands work like opening a link does.

Add --implicit option to :open

---

qutebrowser/misc/editor.py
tests/unit/misc/test_editor.py

Fixes #1767.
On windows, only one process can open a file in write mode at once. We
didn't close the handle we got (self._oshandle) before _cleanup, which
means that we had the file open the whole time, which means that the
external editor couldn't write back the changes.
This patch closes the file while the external editor is running and only
opens it once the editor is closed. We re-opened the file anyway, so
this shouldn't be a huge change. Additionally, tempfile.NamedTemporaryFile
is used instead of mkstemp, as we don't have to deal with os-level file
handles that way.

editor: fix external editor on windows

---

doc/help/commands.asciidoc
qutebrowser/browser/commands.py
qutebrowser/commands/command.py
qutebrowser/commands/runners.py
qutebrowser/config/parsers/keyconf.py
qutebrowser/mainwindow/statusbar/command.py
qutebrowser/misc/utilcmds.py
scripts/dev/src2asciidoc.py

This makes commands like `:open web.archive.org/web/{url}` possible.
It also adds a no_replace_variables command register argument that stops the replacement from happening, which is important for commands like `:bind` and `:spawn` that take a command as an argument.

Allow {url} and {url:pretty} as parts of arguments

---

doc/help/commands.asciidoc
qutebrowser/completion/completionwidget.py
qutebrowser/config/configdata.py
tests/unit/completion/test_completionwidget.py

- Use a single command completion-item-focus with a next/prev argument.
- Add a rule to translate old configs.
- Regenerate the docs.
See #1095.

Combine completion-item-{prev,next}.

---

qutebrowser/config/configdata.py

Changed the description for the 'hints/auto-follow-timeout', 'input/timeout' and 'input/partial-timeout' settings to specify that the time should be given in milliseconds

add time units to timeout descriptions

---

README.asciidoc
doc/help/commands.asciidoc
qutebrowser/browser/hints.py
qutebrowser/keyinput/modeparsers.py
tests/end2end/features/hints.feature

This allows a specific keybinding, for whatever reason, to override the
default mode. Examples of when this could be useful:
* :hint --rapid --mode=word  (to type them more rapidly)
* :hint --mode=letter input  (if the default mode is number)
Also reword the description of 'group' to make the distinction between
'group' and 'mode' clearer.

Add a --mode flag to :hints

---

qutebrowser/misc/earlyinit.py
qutebrowser/utils/docutils.py

when running qutebrowser on python with optimlizations `-OO` enabled, it will crash because docstrings will not be available.

DocstringParser - support python with optimizations on

---

CHANGELOG.asciidoc
qutebrowser/app.py
qutebrowser/config/config.py
qutebrowser/config/configdata.py
qutebrowser/mainwindow/mainwindow.py
qutebrowser/utils/objreg.py
tests/end2end/fixtures/quteprocess.py

Fixes a bunch of “silent” bugs, and one feature request.
I would like to add tests to this but I'm not entirely sure how. (I would need to switch focus, then spawn a new tab via the IPC, then see if the right window got the tab)

Fix the behavior of 'last-focused-main-window' and use it for new (IPC) tabs

---

qutebrowser/browser/hints.py

This is similar to `<input>` and also often uses a placeholder or name to
identify itself.

Extract hint tags from <textarea>

---

qutebrowser/completion/models/instances.py
qutebrowser/completion/models/miscmodels.py
qutebrowser/config/parsers/keyconf.py
qutebrowser/utils/usertypes.py
tests/unit/completion/test_models.py

Note that with the refactoring in 52d0735, bindings are now included in the help completion model but not shown as it allocates 0 width for the `misc` column. Doing so can clip some setting descriptions so I wasn't sure if it was worth it.
Resolves #1707

Complete hidden commands

---

qutebrowser/completion/models/miscmodels.py

In addition to the url and text column, also filter by the index column
so the user can enter a number to navigate to that tab.
Resolves #1830.
This is an easy enough fix, my only concern would be encouraging an anti-pattern of using completion to type the tab index when `Alt+0-9` would be faster (or filtering by content rather than an index).
Then again, I'm one to talk about anti-patterns when I mostly mash `J/K` until I get the tab I want.

Filter buffer completion by all columns.

---

qutebrowser/mainwindow/tabbedbrowser.py
tests/end2end/features/tabs.feature

This makes the default `:undo` setting in qb more like FF and other browsers.

Add code to save and restore the old tab position

---

qutebrowser/app.py
qutebrowser/config/configdata.py
qutebrowser/mainwindow/mainwindow.py
qutebrowser/utils/objreg.py

I usually use my browser with a one-window-per-workspace flow. If I
click on a URL anywhere, I personally would prefer it to go to the
browser instance that's on the same workspace.
To this end, the easiest way to accomplish this is to simply track when
windows are made visible and register them as the last visible object.
(To get finer control for when you have multiple windows on the same
workspace, focus changes also update the last visible object - the
implication being here that focusing something also means you're looking
at it)
Not all users may like this behavior, so I consider it strictly optional.

Add general->new-instance-open-target.window=last-visible

---

qutebrowser/browser/commands.py
qutebrowser/mainwindow/tabbedbrowser.py

By default, closed tabs should be undoable, but when a tab is detached `:undo` should not reopen that tab in the old window. (Fixes #1827)
Note: I have written a test for this which is not included, as the test requires #1831. Adding the test now would just result in a test that always passes, and just add to the noise (especially when it passing doesn't mean anything without #1831).

Add add_undo parameter for closing tabs

---

doc/help/commands.asciidoc
qutebrowser/browser/commands.py
qutebrowser/browser/navigate.py
qutebrowser/utils/urlutils.py
tests/end2end/features/navigate.feature
tests/unit/utils/test_urlutils.py

After opening #1854 I thought I'd try and implement it myself. `:navigate increment` and `decrement` now change the url by the count, and `:navigate up` goes up by count levels. At the moment ctrl-a and ctrl-x don't take counts due to #1856, but binding the commands to other keys works as expected, as does `[count]gu`. The behaviors of `:navigate prev` and `next` are unchanged except for that they now consume a count but don't do anything with it.
My experience with python is pretty minimal, so let me know if I messed something up or forgot anything.

Make :navigate take a count

---

qutebrowser/completion/completionwidget.py
qutebrowser/config/configdata.py
tests/unit/completion/test_completionwidget.py

Implement `completion-item-focus next-category` and
`completion-item-focus prev-category` to jump through completions by
category rather than by item.
Resolves #1567.

Focus completion by category.

---

qutebrowser/commands/runners.py
tests/end2end/features/misc.feature

Fixes the problem described in https://github.com/The-Compiler/qutebrowser/pull/1791#issuecomment-239284646.
Unfortunately without escaping, it can't be tested using BDD tests, because we can't set the clipboard to contain `{url}`.

Fix nested expansion of {variables} in command args

---

qutebrowser/browser/hints.py
qutebrowser/config/config.py
qutebrowser/config/configdata.py
qutebrowser/keyinput/modeparsers.py
tests/end2end/features/hints.feature
tests/end2end/features/test_hints_bdd.py

Fixes #1809 and addresses #219.
Is there a way to test 4ea2d68d771991128846343c87756848ec960bac regarding the partial keystring? In number mode all hint strings are exactly the same length, in letter they are almost the same length so using the word mode is the only sensible way. Unfortunately it requires a system wordlist...

Refactor filter_hints and generalize auto-follow

---

misc/docker/archlinux/Dockerfile
misc/docker/debian-jessie/Dockerfile
misc/docker/ubuntu-xenial/Dockerfile

Since we use pytest-xvfb, Xvfb is automatically started and stopped by
pytest. The herbstluftwm also runs in the "outer" Xvfb and is not
actually available inside the tests, as the tests run in another
display, while  herbstluftwm runs in :0.
This patch removes herbstluftwm completely (it was not used until now,
so there shouldn't be a problem), and doesn't start Xvfb (the package is
still needed for pytest-xvfb to work).
Additionally, it adds the "xauth" package on debian, because we'll need
it anyway sooner or later. It's automatically included in Ubuntu and
Arch because xvfb depends on it, but on debian, xauth is only
recommended and not installed automatically.

docker: don't start Xvfb and herbstluftwm

---

CHANGELOG.asciidoc
qutebrowser/config/configdata.py
qutebrowser/mainwindow/mainwindow.py
qutebrowser/utils/objreg.py
tests/end2end/features/conftest.py
tests/end2end/features/invoke.feature
tests/end2end/features/test_invoke_bdd.py
tests/end2end/fixtures/quteprocess.py

Fixes #1060.
In the process of adding this, I also decided to rewrite
mainwindow.get_window() for clarity (and also because flake8 was warning
about complexity).
Also adds some tests to the new-instance-target mechanism, currently
stuffed into tabs.feature to make use of the "clean up open tabs",
including a test for the issue specifically.

Add new-instance-open-target.window = first-opened

---

CHANGELOG.asciidoc
doc/help/settings.asciidoc
qutebrowser/browser/hints.py
qutebrowser/browser/webelem.py
qutebrowser/browser/webengine/webengineelem.py
qutebrowser/browser/webkit/webkitelem.py
qutebrowser/config/config.py
qutebrowser/config/configdata.py
scripts/dev/run_vulture.py
tests/helpers/stubs.py
tests/unit/browser/webkit/test_webkitelem.py
tests/unit/config/test_config.py
tests/unit/config/test_configtypes.py

This is a complete rewrite of how hints are drawn, which now use native Qt drawing and QLabels instead of injecting elements into the QWebView. This has various benefits:
- Fixes issues like #925 and #1126 where the hint drawing is influenced by the page
- Lets us use a single coordinate system for drawing and clicking hints, which simplifies `webelem.rect_on_view`.
- Lets us get rid of various `webelem` methods which aren't needed anymore now, which in turn
- Gets us a step closer to having hints with QtWebEngine.
As an effect of that, how e.g. gradients and the label opacity is configured changes. I've tried to migrate the most common cases, but this will probably require some manual intervention for some users.
Since this is quite a big change with some potential of breakage, I'd …

Use QLabels to draw hints

---

qutebrowser/html/settings.html
tests/end2end/features/set.feature

qute://settings: set valid type of <input> fields

---

tests/end2end/features/completion.feature
tests/end2end/features/test_completion_bdd.py
tests/unit/completion/test_completionwidget.py

Add tests for completion bugs fixd by #1811 as discussed in #1899.
These tests cover #1600 and #1812. #1519 doesn't actually appear to be fixed.
Note that #1840 also adds `completion.feature` and `test_completion_bdd.py` so someone will have to resolve a conflict (just an add/add so not a big deal).

Test completion

---

qutebrowser/mainwindow/tabwidget.py

Attempt to fix the issue #1693 by:
- setting the TabBarStyle to TabWidget in addition to TabBar
- chain up SE_TabWidgetTabBar requests in TabBarStyle.subElementRect
to the super() rather than self._style, in order to avoid getting
adwaita-specific rect sizes instead of default ones that are also
used in rendering.

TabWidget: a possible fix for #1693 - grey area under custom tabbar

---

qutebrowser/browser/commands.py
tests/end2end/features/editor.feature

':open-editor' can now be run in all modes.
Resolves #1902

Allow :open-editor in modes other than insert

---

qutebrowser/commands/runners.py
qutebrowser/completion/completer.py
qutebrowser/completion/completionwidget.py
tests/unit/completion/test_completer.py
tests/unit/completion/test_completionwidget.py

While trying to fix #1519 I noticed the code seemed excessively complicated. I rewrote using locals rather than class variables that are persisted between method calls.
[The fix](https://github.com/The-Compiler/qutebrowser/commit/6e5cc62a0dd6bc4b06cecc13173f86c3803516e7) is independent of the refactoring but I think the refactored version is worth it (~100 less lines of code, and that's including quite a few more test cases :grin:)

Refactor Completion.on_selection_changed and fix #1519

---

qutebrowser/commands/command.py
tests/unit/commands/test_cmdutils.py

Fixes #1872.
This prevents `inspect.Parameter.empty` from slipping through to the
command.

Make sure keyword-only parameters have a default

---

qutebrowser/completion/completer.py
tests/unit/completion/test_completer.py

Exit before trying to partition if the command prefix is not ':'.
Resolves #1969:
'TypeError with refactored completion when searching for command'

Completer: don't try to partition search.

---

qutebrowser/browser/commands.py
qutebrowser/commands/runners.py

This is useful for prettifying URLs like [this](https://wiki.archlinux.org/api.php?action=query&list=recentchanges&rcprop=title%7Cids%7Cuser%7Cflags) (where `%7C` is the `|` symbol).
According to the [QUrl documentation](http://doc.qt.io/qt-5/qurl.html#ComponentFormattingOption-enum), `QUrl::DecodeReserved` is the default for the individual component getters. I think that the corner cases where `encode(decode_also_reserved(url))` does not give the original URL are rare enough - in that case the pretty-url doesn't make much sense in any form.

Prettify yank pretty-url

---

qutebrowser/html/settings.html

This shows each option's description (if available) below its name in the table on the qute:settings page in a slightly lighter and smaller font.

show option description in qute:settings

---

qutebrowser/completion/completer.py
tests/end2end/features/completion.feature

Just limit the cursor position to the length of the text to avoid
crashes in this case.
Resolves #2007.

Handle unicode characters in Completer.

---

qutebrowser/mainwindow/tabwidget.py
tests/unit/mainwindow/test_tabwidget.py

I'm not happy about those four magical pixels. I'm not sure why (maybe because of margins?), but they are needed to align tab labels properly. I have a creeping suspicion they might mess thing up on high DPI displays, but I don't have any to test on.

Reserve space for favicon with vertical tabs (fixes #1968)

---

qutebrowser/browser/pdfjs.py
tests/unit/browser/test_pdfjs.py

Fixes #2012
They renamed `PDFView` to `PDFViewerApplication`, which we need to account
for in our pdfjs scripts.
Also, it seems like the actual viewer is now only created when the DOM
has been loaded. This means that at the time when our script is
executed, the viewer does not yet exist. Thus we need to delay the open
request too by registering a `DOMContentLoaded` handler.

pdfjs: compatibility for v1.6.210

---

qutebrowser/commands/runners.py
qutebrowser/misc/utilcmds.py
tests/end2end/features/caret.feature
tests/end2end/features/misc.feature
tests/end2end/features/tabs.feature
tests/end2end/fixtures/quteprocess.py
tests/unit/commands/test_runners.py
tests/unit/completion/test_completer.py

CommandRunner.parse had some logic for handling commands of form
`:<count>:cmd`. However, this complicated the parsing logic for something
that appears to only be used in tests. One could use it in a
userscript, but this is unlikely as it is undocumented. Removing
support for this simplifies the logic of parse.
The commnd `run-with-count` is added to provide this functionality.
It works like `repeat` but passes the count along to the command
instead of running the command multiple times.
This resolves #1997: Qutebrowser crashes when pasting commands.
This bug was caused by excess stripping of ':' from the command string
by _parse_count.

Remove :<count>:cmd syntax support.

---

misc/userscripts/cast

I thought this would be a nice one. The usage is described in the begining of the userscript file. Some process may be left dangling in the background. It is documented in the file. However, running the script successively will only leave one dangling process in the background. Also, temporary files will be cleaned up.
*However, I want to point out that castnow may not always be really reliable. I am personally having issues with it (it sometimes stops video playback for some reason). But until there's a better way, this is cool.*

add cast userscript for ChromeCast

---

README.asciidoc
doc/help/settings.asciidoc
qutebrowser/browser/webkit/network/networkmanager.py
qutebrowser/config/configdata.py

This adds a configuration option for the location of the netrc file. By adding a configuration option, we also document the existence of the feature itself.

Make netrc location configurable

---

misc/userscripts/qutebrowser_viewsource

For months, I've been wondering what created these files in my home directory, till I finally found out after I'd run this userscript quite a few times. If you give a template to `mktemp`, it stops assuming `--tmpdir`, you have to give it explicitly.

Fix viewsource userscript

---

qutebrowser/browser/webkit/webkitelem.py
tests/end2end/features/hints.feature

As null-elements can't be wrapped anyway, I think it makes sense to just return None. The fact we don't check this, nor catch the exception, gives trouble with `:hint all current`.

Check if parent is null element

---

qutebrowser/browser/webelem.py
qutebrowser/browser/webengine/webengineelem.py
qutebrowser/browser/webkit/webkitelem.py
qutebrowser/javascript/webelem.js

This morning, I noticed that one of the remaining issues in WebEngine causing tests to fail was the "current" hint target.
The problem is caused by the fact the `parent` method isn't implemented yet. This can easily be done by extending the `serialize_elem` to include the parent element. However, this can cause the whole page to be serialized to python. That's why I implemented `remove_blank_target` in javascript instead, and moved the existing implementation to `WebKitElement`.
For my first attempt using `parent`, I needed `__setitem__` in `WebEngineElement`. If you want, I can open a PR with [the comit](https://github.com/paretje/qutebrowser/commit/5fed65adc6c9c0c193b1b01f21c3eacd64251b12).

Implement hint target "current" for webengine

---

misc/qutebrowser.spec

This should probably be fixed in pyinstaller, not sure how yet. See [this comment](https://github.com/pyinstaller/pyinstaller/blob/b78bfe530cdc2904f65ce098bdf2de08c9037abb/PyInstaller/hooks/hook-PyQt5.QtWebEngineWidgets.py#L24).

Set the bundle identifier to a fake value to allow icu data to be found.

---

qutebrowser/__init__.py
tests/unit/config/test_config.py

Bump version info to 0.8.2 so that it shows up in `qutebrowser --version`
My apologies if this is left at 0.8.1 for a reason, it just seemed like a small oversight.  Noticed when I ran `qutebrowser --version` and despite being the latest git commit, still showed 0.8.1
I guess this doesn't make a whole lot of difference - release-wise, it by necessity won't make it in until it's obsolete - but handy for git-compilers, at least.

Update version number to 0.8.2

---

qutebrowser/mainwindow/statusbar/progress.py

The progress bar didn't specify a font, so if the system-supplied font was larger than the status bar font the entire status bar grew. With the status bar at the top this moved almost everything else.
See #886.

Stop progress bar from growing status bar height

---

qutebrowser/browser/webkit/webkittab.py
tests/end2end/features/javascript.feature

Some time ago, I found out that javascript does work, also when disabled in qtwebkit, when executed from a webelement. We can use this to enable `jseval` for users disabling javascript.

jseval when javascript disabled in qtwebkit

---

doc/help/index.asciidoc

also use rel paths for toplevel docs

---

qutebrowser/browser/browsertab.py
qutebrowser/browser/commands.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webkit/webkittab.py
tests/end2end/features/yankpaste.feature

The javascript of `insert-text` is run in the context of a webelement, which means we don't necessarily need it to be enabled for the content.

insert-text without javascript

---

doc/help/commands.asciidoc
doc/help/settings.asciidoc
qutebrowser/browser/commands.py
qutebrowser/config/config.py
qutebrowser/config/configdata.py
qutebrowser/config/configtypes.py
qutebrowser/mainwindow/tabbedbrowser.py
tests/end2end/features/open.feature
tests/end2end/features/tabs.feature
tests/unit/config/test_config.py

First commit implements the suggestion from issue #1619, the remaining ones are for naming consistency.
During implementation the names `before` and `after` seemed better suited to me despite disliking the terminology at first. Feel free to cherry-pick 828b7d744a6c5fa0f54853ec13342fdcfce65862 only or I could modify this PR to adapt a different naming convention.

Setting values of tabs->select-on-remove (Issue #1619)

---

tests/unit/utils/test_typing.py

See #2090. The old tests fail with the newer versions.

Fix Union tests for newer Python 3.5 versions

---

qutebrowser/keyinput/modeparsers.py
tests/end2end/features/keyinput.feature

See #2108. I implemented it as a general `RegisterKeyParser` feature, so it also works for `run-macro`, `set-mark` and `jump-mark`.

Cancel register key input with escape

---

qutebrowser/browser/webkit/mhtml.py
tests/end2end/data/downloads/mhtml/complex/complex.mht
tests/end2end/data/downloads/mhtml/simple/simple.mht
tests/unit/browser/webkit/test_mhtml.py

Saving some space when downloading sites as mhtml.
When a space is encountered at the end of the line, it's encoded as `=20` instead of `<space>=`, but it seems to be OK with Quoted-Printable docs. 
I attach [MHTML file](https://github.com/The-Compiler/qutebrowser/files/618055/qutebrowser_mhtml.zip) generated from qutebrowser.org and UnMHT's version submitted by @stroobandt to compare it with.
Obviously I had to rewrite test .mht files, since they had included all the unnecessary `=20`.

Fixed mhtml quopri encoding with spaces and tabs (see: #2063)

---

qutebrowser/browser/commands.py
qutebrowser/completion/models/miscmodels.py
tests/end2end/features/completion.feature
tests/helpers/stubs.py

It was a bit hard to recreate the issue #2141 in tests, since the completer seems to update the pages by itself from time to time. The current feature test is a bit weird, but indeed fails in the old version and passes in the new one.
Not really sure if I changed `TabbedBrowserStub` test helper correctly (I had to, since in the old version it didn't have tabBar() method).

Fixed problems with tab completion after moving tabs (#2141)

---

qutebrowser.desktop

Debians lintian pointed out that a .desktop file should contain a Keywords-entry

Add Keywords entry to comply with freedesktop guidelines

---

doc/help/settings.asciidoc
qutebrowser/browser/downloads.py
qutebrowser/config/configdata.py
tests/end2end/features/downloads.feature
tests/end2end/features/test_downloads_bdd.py

- adds new `general` -> `default-open-dispatcher` setting (string)
- if set, will be used instead of QDesktopServices.openUrl - (xdg-open backend)
- fixes the 'download handlers' part of issue #841
- note that this is only relevent to the `:download-open` command and other
methods of opening downloaded files from qutebrowser

implement optional download-open handler setting

---

qutebrowser/browser/downloads.py
qutebrowser/browser/webengine/webenginedownloads.py
tests/end2end/features/downloads.feature

Fixes #2173.
See [this comment](https://github.com/The-Compiler/qutebrowser/issues/2173#issuecomment-268246936) for explanation.

downloads: don't remember dir for temp downloads

---

qutebrowser/config/configdata.py

Currently, only `<Escape>` clears the keychain, but not `<Ctrl-[>`. This adds the missing functionality.

Clear keychain on <Ctrl-[> in addition to <Escape>

---

doc/userscripts.asciidoc
qutebrowser/commands/userscripts.py

[Comment from #937](https://github.com/The-Compiler/qutebrowser/issues/937#issuecomment-274883241).
Although it makes more sense to pass this environment variable while in command mode only, it seemed to be more trouble than it's worth to get it to do that, so it passes the variable regardless of what mode you're in.
I looked into adding a test, but I wasn't sure what to do. Since `grep -r QUTE_TITLE tests/` came up with nothing, I presume it's not so important, but i'll add a test if neccessary, though I'll need some guidance if so.

Add "QUTE_COMMANDLINE_TEXT" environment variable for userscripts.

---

qutebrowser/keyinput/modeman.py
tests/end2end/features/misc.feature

This disallows using :enter-mode with modes that don't work properly when entered that way. Fixes #1137.

Blacklist some modes for :enter-mode

---

qutebrowser/keyinput/modeparsers.py
tests/end2end/features/keyinput.feature

Ignore all keys with an empty .text() return value, not just modifier keys. You can still use unusual things like ß for registers, but XF86WakeUp is out. Fixes #2125.

Ignore non-register keys

---

qutebrowser/browser/navigate.py
tests/end2end/data/navigate/rel_nofollow.html
tests/end2end/features/navigate.feature

The _find_nextprev function of browser/navigate.py only checks to see if
the rell attribute equals 'prev', 'previous', or 'next'. This patch
changes this to check for a set intersection between {'prev',
'previous'} or {'next'} and the set of the space separated list of the
rel attribute.

browser/navigate: _find_nextprev allow for space sep rel attribs

---

qutebrowser/javascript/pac_utils.js
tests/unit/browser/webkit/network/test_pac.py

Fix isPlainHostName() implementation and add test-case for it.
Signed-off-by: Kirill A. Shutemov <kirill@shutemov.name>

PAC: fix isPlainHostName()

---

README.asciidoc
doc/help/commands.asciidoc
qutebrowser/misc/sessions.py
tests/end2end/features/sessions.feature

The new optional argument --only-active-window makes :session-save to
save only the tabs in the currently active window.

Add optional argument --only-active-window to :session-save.

---

qutebrowser/browser/downloads.py

Fixes #2296
By using a singleshot timer, we return fast from `DownloadItem.open_file`, which in turn closes the prompt fast, which in turn doesn't allow a second Ctrl-x to be registered, which in turn doesn't want to set the filename twice.
With this patch, I can't recreate the bug anymore, though it'd be interesting to know if it works for other people too. @troubas, could you try if you can reproduce it with this patch applied?

return fast from DownloadItem.open_file

---

qutebrowser/browser/qutescheme.py
qutebrowser/config/configdata.py
qutebrowser/html/history.html
qutebrowser/javascript/history.js
tests/end2end/features/history.feature
tests/unit/browser/test_qutescheme.py

Improvements to qute:history as outlined in #2333.
The history page now shows history from the past 24 hours. More items are
automatically loaded and appended when scrolled to the bottom. Items are also
separated if there's a 30 minute gap between them.

New qute:history page.

---

qutebrowser/browser/qtnetworkdownloads.py
tests/end2end/features/downloads.feature
tests/end2end/fixtures/webserver.py
tests/end2end/fixtures/webserver_sub.py

Fixes #2304
In some cases, the finished handler fired before the error handler, e.g. when downloading a 500 error page that is sent as attachment:
HTTP/1.1 500 Internal Server Error
Content-Type: application/octet-stream
Content-Disposition: inline; filename="attachment.jpg"
here we downloaded 0 bytes, fired the finished handler and after that fired the error handler because of the 500 - but the finished handler had already set our reply to `None` (and displayed the error message).

Check for None-reply in _do_die

---

qutebrowser/config/configdata.py
qutebrowser/misc/keyhintwidget.py
tests/unit/misc/test_keyhints.py

ui.keyhint-delay controls the time from starting a keychain to showing the
keyhint dialog. Resolves #2462.
Kinda a relief to do something this easy between the completion work :grin:

Make keyhint delay configurable.

---

qutebrowser/browser/commands.py
qutebrowser/browser/downloads.py
qutebrowser/browser/webkit/mhtml.py
qutebrowser/mainwindow/mainwindow.py
qutebrowser/mainwindow/prompt.py
qutebrowser/utils/utils.py
tests/end2end/features/downloads.feature
tests/unit/utils/test_utils.py

Fixes #2305 
I'd like to add an integration test, but that would require downloading to a drive root, which would leave temporary test data on the drive and could lead to permission errors...

treat E: and E:\ the same when downloading

---

tests/end2end/features/adblock.feature
tests/end2end/features/backforward.feature
tests/end2end/features/caret.feature
tests/end2end/features/completion.feature
tests/end2end/features/downloads.feature
tests/end2end/features/editor.feature
tests/end2end/features/hints.feature
tests/end2end/features/history.feature
tests/end2end/features/invoke.feature
tests/end2end/features/javascript.feature
tests/end2end/features/keyinput.feature
tests/end2end/features/marks.feature
tests/end2end/features/misc.feature
tests/end2end/features/navigate.feature
tests/end2end/features/open.feature
tests/end2end/features/prompts.feature
tests/end2end/features/scroll.feature
tests/end2end/features/search.feature
tests/end2end/features/sessions.feature
tests/end2end/features/set.feature
tests/end2end/features/spawn.feature
tests/end2end/features/tabs.feature
tests/end2end/features/urlmarks.feature
tests/end2end/features/utilcmds.feature
tests/end2end/features/yankpaste.feature
tests/end2end/features/zoom.feature

This really tripped me up yesterday, My "Vim default" is to use tabs.
This (where `!···` is a tab) does not work as you'll hope it works:
```
Scenario: Retrying a failed download when the directory didn't exist (issue 2445)
When I download http://localhost:(port)/data/downloads/download.bin to <path>
And I wait for the error "Download error: No such file or directory: *"
And I make the directory <mkdir>
And I run :download-retry
!···!···And I wait until the download is finished
Then the downloaded file <expected> should exist
Examples:
| path                 | mkdir   | expected             |
| asd/zxc/             | asd/zxc | asd/zxc/download.bin |
```
Unfortunately, pytest-bdd uses the "Python 2 behaviour" of "expand all
tabs to 8 spaces", and doesn't give any errors on …

Add a modeline to all the *.feature files

---

qutebrowser/app.py
qutebrowser/misc/crashsignal.py

All of it is just converting `objreg.get('xxx')` to `objreg.get('xxx',
None)` and adding a `if xxx is not None` check.
Fixes #1170

Allow pressing ^C when there's an unknown setting

---

qutebrowser/commands/runners.py
tests/end2end/features/misc.feature

Problem 1: Entering a command of `:::save` gives an error.
Problem 2: Entering a command of `:save\n` gives an error.
Both scenarios may seem a bit silly at first, but I encountered both by
copy/pasting a command:
1. Enter `:` in qutebrowser.
2. Copy a full line from a terminal starting with `:`.
3. You will now have both of the above problems.
Solution: Trim all whitespace and `:` of a command. This is also what
Vim does, by the way.

Relax commandline parsing a bit

---

qutebrowser/config/parsers/keyconf.py

Also change the logic in _load_default a wee bit so that it won't try to
write the keys.conf on startup.
Fixes #1235

Don't crash when trying to write an unwritable keyconf.

---

qutebrowser/config/config.py
qutebrowser/config/parsers/keyconf.py

Also catch `cmdexc.CommandError` on startup to show these errors in the
alert dialog on startup.
Fixes #1340

Fix display of errors while reading the key config file

---

README.asciidoc

Mini-PR, since I subscribed to both twice not realizing I would get double emails.

Mention that qutebrowser@ also gets the mails from qutebrowser-announce@

---

CHANGELOG.asciidoc
qutebrowser/misc/utilcmds.py
qutebrowser/utils/log.py
tests/end2end/features/utilcmds.feature

There was no `LogFilter`. The fix is to always initialize a
`LogFilter()` with `None`. as the "filter".
Fixes #2303.

Fix crash of :debug-log-filter when --filter wasn't given

---

qutebrowser/browser/qutescheme.py
qutebrowser/html/history.html
qutebrowser/html/history_nojs.html
tests/end2end/features/history.feature

Use old history page on QtWebKit and when javascript is disabled.
Fixes #2472.

Fix qute:history on QtWebKit.

---

INSTALL.asciidoc

Hi,
OpenBSD 6.1 was released a few days ago so update doc.
Also packages are preferred to ports.
Cheers,
Daniel

Update INSTALL doc with new OpenBSD release

---

tests/unit/browser/test_qutescheme.py

I've been going crazy trying to figure out why I couldn't get SQL even close to as fast as the old implementation...
This benchmark was running very quickly due to an improper setup.
The current history implementation expects that a newly inserted entry must
be more recent than any existing entries and sorts according to this
assumption.
The benchmark test inserts increasingly older entries, breaking this invariant.
When run in the benchmark, the qute://history/data implementation would
see an entry older than the oldest time in the time window and would
immediately return with a single "next" entry.
This patch inserts data in an order that mantains history's invariant and adds
a sanity-check at the end of the test. It does not check for the exact length
as not all entries will be within …

Fix qute_history benchmark.

---

doc/help/settings.asciidoc
qutebrowser/config/configdata.py
qutebrowser/mainwindow/tabwidget.py
tests/unit/mainwindow/test_tabwidget.py

This allows users to change the size of the favicon independently from
the size of the font/tab, in order to adjust the balance between
favicons and text. The drawing code is also adjusted to re-center the
favicons vertically with the text. The only other change is that the
initialization function also explicitly calls set_font() in order to
force the font/favicon size to be recomputed when the tab settings are
changed.
Works as expected even for values of 0.0 (which is equivalent to hiding
the favicon completely).
Closes #2549.

Add tabs->favicon-scale setting

---

qutebrowser/browser/browsertab.py
qutebrowser/browser/webelem.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webkit/webkitelem.py
qutebrowser/browser/webkit/webkittab.py
qutebrowser/javascript/webelem.js
tests/end2end/data/search.html
tests/end2end/data/search_select.js
tests/end2end/features/search.feature

This PR adds support for follow selected in webengine, so users can search via `/`, select a link, and press enter to follow the link.
This works in webengine by first clearing the search (this causes the selected search result to become selected), and then using the javascript click method found here: https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/browser/webkit/webkittab.py#L348-L376
This is pretty hacky, but it does work (and I've seen this beahvior in chrome for a long time, so I don't think it would be removed soon).
This PR is very rough and needs a bunch of work though, for example:
This is my first time ever writing any javascript, so let me know if I'm doing anything stupid on that front. Let me know what you think!
Thanks again for maintaining such a great …

Add support for follow_selected in qtwebengine

---

CHANGELOG.asciidoc
qutebrowser/browser/commands.py

It turns out that `:navigate --tab up`, `:navigate --tab increment` and `:navigate --tab decrement` open tabs with `explicit=True`, similarly to the issue raised in #2624 and fixed in 273749c. This PR fixes this.
Note that the current behavior is inconsistent within the `:navigate` command, since tabs opened by `:navigate --tab prev` and `:navigate --tab next` are opened with `explicit=False`, so this really should be addressed.

Set explicit=False for :navigate --tab

---

qutebrowser/config/configtypes.py
scripts/dev/ua_fetch.py

PR for adding Android user-agent.
[android.googlesource.com](https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/values/strings.xml#2074)
https://amazon.com/underground
* __no UA:__ Page offers to send link to an email
*  __UA Version <4.1.0:__ Page tells you that it requires at least 4.1
*  __UA Version >=4.1.0:__ Page offers download to APK

Add Android UA

---

CONTRIBUTING.asciidoc

Added a list of chrome urls that work.  A couple of with (?) next to
them did nothing and didn't hang or kill the browser, so I removed them.
They only work in OSX, not windows (opened separate issue for this).

Document chrome:// URLs (fixes #2292)

---

INSTALL.asciidoc
scripts/asciidoc2html.py
www/header.asciidoc
www/qute.css

This adds a table of contents to the installation instructions to
improve the navigation within the document.
I decided to use the command line to configure the TOC because there
were problems with just using an attribute entry in the asciidoc 
document header.
Specifically the insertion of the `header.asciidoc` into the resulting
HTML file prevented the attribute entry approach from working.
The TOC can now be inserted into any doc file at any position using
toc::[]
One small thing that changed is the `h1` element in the site header.
Asciidoc was putting this into the table of contents as well, so I changed
that element to a `span` and reapplied the same styles as before.
Here is what it looks like: http://i.imgur.com/qb3SPCH.png
More asciidoc TOC options are documented at the bottom of …

Add TOC to installation instructions

---

qutebrowser/config/configdata.py

This continues the spirit of my previous PR and allows formatting tab
titles to designate when private mode is enabled. I didn't even realize
that tab title-format was a separate thing from window-title-format
(yes, it's in the name.. silly craftyguy), until now.

Add private mode title format for tabs too

---

qutebrowser/mainwindow/tabwidget.py

When filling up leftover space in the tabbar, pinned tabs have to be taken care of. Firstly, only the space that is not used by pinned tabs should be considered. Secondly, pinned tabs may also have their width increased by 1px so returning early does not work.
To reproduce: Open three tabs, pin one of them and resize the window a little. There should be gray leftover space at the right and of the bar.

Fix padding of remaining tabbar space with pinned tabs

---

qutebrowser/browser/commands.py
qutebrowser/mainwindow/tabbedbrowser.py
qutebrowser/mainwindow/tabwidget.py
qutebrowser/misc/sessions.py
tests/end2end/features/tabs.feature

An attempt to fix (possibly) #2759. Conflicts with (slightly) #2762, which I'll deal with. This is probably more important...
I think that this change makes it impossible for the `tab` object to be `None`, as long as a tab creation does not result in `None`, (but I can't confirm the issue is fixed because I can't repro). 
Let me know what you think :smile:.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2765)

Refactor set_tab_pinned to take a tab widget.

---

qutebrowser/mainwindow/mainwindow.py
qutebrowser/mainwindow/statusbar/backforward.py
qutebrowser/mainwindow/statusbar/bar.py
scripts/dev/check_coverage.py
tests/helpers/stubs.py
tests/unit/mainwindow/statusbar/test_backforward.py

Fixes https://github.com/qutebrowser/qutebrowser/issues/2737.
TODO:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2738)

[RFC] add statusline widget for back/forward indicator

---

qutebrowser/mainwindow/messageview.py
tests/unit/mainwindow/test_messageview.py

Show messages longer if there are multiple of them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2808)

resolve issue #2797

---

misc/userscripts/readability

Just a small addition to the inline documentation of the `readability` userscript.
It requires the `readability` python module to be present on the system, so I added a note with two choices that fulfill this dependency:
- https://github.com/buriy/python-readability
- https://github.com/bookieio/breadability
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2831)

Clarify dependecies for readability userscript

---

misc/userscripts/readability

Turns out the latest version of `python-readability` breaks the userscript, apparently some UTF-8 error...
So in addition to my documentation update in #2831, I have patched the script to prefer the `breadability` fork if available. If not available the script will try to use the old module as before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2834)

Add support for breadability module in readability userscript

---

qutebrowser/mainwindow/tabwidget.py

Closes #2826 
Let's see if the tests pass....
Also, does this logic seem right? Essentially enforcing a minimum size allocated for non-pinned tabs, even if the window is small.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2827)

Enforce a minimum size for non-pinned tabs

---

qutebrowser/completion/models/histcategory.py
tests/unit/completion/test_histcategory.py

Fixes #2849, where pressing 'o' immediately after starting with
web-history-max-items set would cause a crash as the query result is
empty.
The query is not returning an error here, so it seems like the best
approach is to simply ignore an empty result.
In this case, there will be no crash, but the completion will be empty
anyways (as the main query is also returning an empty result).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2852)

Fix web-history-max-items-crash.

---

qutebrowser/completion/completionwidget.py
tests/unit/completion/test_completionwidget.py

Some reports came in that a resizeEvent was causing a crash due to the
model being none in the CompletionView.
Fixes #2854.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2856)

Abort resizeEvent if model is None.

---

qutebrowser/completion/models/miscmodels.py
tests/unit/completion/test_models.py

When a key is bound to a command line that includes one or more
arguments to a command, bind completion should show the whole command
for the "Current" category, and use only the command name to look up the
description.
Fixes #2859, where a crash was caused by looking up the description by
the full command text rather than just the name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2861)

Fix bind completion for bindings with arguments.

---

qutebrowser/completion/completionwidget.py
tests/unit/completion/test_completionwidget.py

When tabbing to the last index of history completion, call expandAll
which will call fetchMore to retrieve more query results, if available.
Calling fetchMore directly will not update the view, and for some
reason self.expand(idx.parent()) and
self.expand(self.model().index(idx.row(), 0)) did not work, so I'm using
expandAll.
Fixes #2841.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2853)

Expand history completion results if on last index.

---

qutebrowser/completion/models/histcategory.py
tests/unit/completion/test_histcategory.py

Fixes #2868, where pressing <shift-tab> then <ctrl-d> in history
completion (with > 256 items) would cause later items to disappear (and
cause a crash if you try to delete again).
Cause:
Scrolling to the bottom would fetch an additional 256 items (in addition
to the 256 that are fetched at first). Deleting causes the query to
re-run, but it only fetches the initial 256 items, so the current index
is now invalid.
Fix:
After deleting from the history category, call fetchMore until it has
enough rows populated that the current index is valid.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2871)

Fix fetch/delete sql category bug.

---

qutebrowser/completion/models/miscmodels.py
tests/unit/completion/test_models.py

Pressing ctrl-d in the completion menu for
:quickmark-load/:bookmark-load  will now delete the selected
quickmark/bookmark.
Resolves #2840.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2873)

Support delete from :{quick,book}mark-load.

---

qutebrowser/browser/urlmarks.py
qutebrowser/misc/sessions.py
tests/unit/misc/test_sessions.py

The added/removed signals for the urlmark managers are no longer used as
the completion models are generated on-the-fly. The changed signal is
still needed so the save-manager knows when to trigger a write to disk.
Also removes session_manager.update_completion, which is no longer
needed for the same reason as above.
keyconf.changed cannot be removed, as it is still wired up to
basekeyparser.
Resolves #2874.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2875)

Remove obsolete signals.

---

qutebrowser/completion/models/configmodel.py
qutebrowser/completion/models/listcategory.py
qutebrowser/completion/models/miscmodels.py
tests/unit/completion/test_listcategory.py
tests/unit/completion/test_models.py

Instead, expect the data to be given in the desired order. Completion
functions should sort their data _if_ they want it sorted in the
completion. This has a few implications:
- {book,quick}marks appear in the same order they do in the text file.
This means users can rearrange their mark files for custom sorting.
- Sessions are sorted as they appear in the session manager
- Tabs are sorted numerically, not alphabetically (Fixes #2883)
Note that prefix-based filter sorting is still performed, so items
starting with the filter pattern come first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2888)

Don't perform alphabetical sort in listcategory.

---

qutebrowser/browser/commands.py

This allows for relative paths instead of having to specify the absolute path to the file. Useful for example when executing a javascript file through a binding using `jseval`, in a similar fashion to userscripts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2899)

Expand ~ to user's home on Linux

---

misc/userscripts/format_json

Hey, this pull request adds a useful userscript that will will format and syntax highlight a json response. Here's a quick before/after set of screenshots showing it off:
The script uses `jq` to validate and format the json and `pygments` to provide syntax highlighting. After the json is formatted, it is base64 encoded (to prevent formatting issues) and sent in the form of a `jseval` command to qutebrowser to replace the page's content. It is relatively safe to use as it validates proper json formatting before proceeding to highlighting and attempting to replace the current page's content.
It additionally provides an optional parameter that can be used to set the desired pygments theme used to generate the syntax highlighted html.
Thanks!
--- …

implemented format_json userscript

---

qutebrowser/browser/history.py
tests/unit/browser/test_history.py

Encode urls that are inserted into the history, but do not encode urls
for completion (other than removing passwords).
Also ensure that urls read from the history text file are formatted
consistenly with those added while browsing.
Fixes #2903.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2905)

Consistently format urls in history.

---

qutebrowser/misc/sessions.py
tests/end2end/features/private.feature

Replaces https://github.com/qutebrowser/qutebrowser/pull/2902
Closes #2900 
I have a tiny bit of work on this to clean it up, but it should be good for the most part.
@cryzed (just fyi)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2909)

Fix saving a session with --only-active-window

---

misc/userscripts/password_fill

> There is no reason to fill usernames into invisible input fields. We are
> probably not leaking anything but it can break some apps (like TTRSS).
I just found out that Tiny Tiny RSS is not working with `password_fill` because it has multiple hiddent text fields in login page (not sure why). And all of them get populated with found username which breaks whole app.
IMHO there isn't any use case where filling hidden input field is wanted anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2942)

password_fill: Stop filling username to invisible input fields

---

INSTALL.asciidoc

This was the incantation that worked for me on Fedora 26.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2950)

Use python3-qt5-webengine for Fedora

---

README.asciidoc

Otherwise clicking the link from GitHub gives a 404.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3000)

fix link to configuring page in readme

---

qutebrowser/utils/utils.py

Added 3 functions in ```qutebrowser/qutebrowser/utils/utils.py``` that return ```True``` or ```False``` depending on the OS/Platform.
Functions being : 
- ```is_mac()```
- ```is_linux()``` 
- ```is_windows()```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2972)

Added functions to check OS/Platform

---

qutebrowser/completion/models/configmodel.py
tests/unit/completion/test_models.py

The parsing bind() did manually is now available through CommandParser.
Resolves #2952.
This also adds a unit test for the case when there is no current
binding, as I broke that while working on this and there was no test to
catch it :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2953)

Use CommandParser for configmodel.bind.

---

qutebrowser/config/configfiles.py
tests/unit/config/test_configfiles.py

This is done so config.py can import other python files in the config directory. For example, config.py can 'import theme' which would load a theme.py.
The previous path is restored at the end of this function, to avoid tainting qutebrowser's path
Feel free to trash this PR if this dosen't seem like a good approach.
See #2969
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2970)

Add qutebrowser config directory to python path

---

qutebrowser/browser/history.py
tests/unit/browser/test_history.py

Previously, a successful import of the text history into sqlite would
move 'history' to 'history.bak'. If history.bak already existed, this
would overwrite it on unix and fail on windows.
With this patch, the most recently imported history is appended to
history.bak to avoid data loss.
Resolves #3005.
A few other options I considered:
1. os.replace:
- fast, simple, no error on Windows
- potential data loss
2. numbered backups (.bak.1, .bak.2, ...):
- fast, no data loss, but more complex
3. append each line to the backup as it is read:
- more efficient than current patch (no need to read history twice)
- potentially duplicate data if backup fails
--- …

Append multiple history backups on import.

---

qutebrowser/config/configdata.yml
qutebrowser/html/settings.html

Makes editing long values easier and removes extra backslashes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3029)

Add table headers and widen input fields in qute://settings, Remove extra backslashes in configdata.yml

---

doc/help/index.asciidoc

It got broken in 4c616a5733dfa98a0d1b557d679af255ddb9759b
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3032)

Fix the link to faq.html in help page

---

qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webengine/webview.py

Adds the [`proxyAuthenticationRequired()`](http://doc.qt.io/qt-5/qwebenginepage.html#proxyAuthenticationRequired) signal handler to the WebEnginePage to allow users to login to a proxy server.
Aborting the username/password dialog displays an error page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/2984)

Enable proxy server authentication

---

doc/help/configuring.asciidoc

This is a minor documentation update that fixes a bad example of creating an alias using config.py. The current example will produce an error when it is used since the leading `:` is interpreted as part of the command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3039)

fix example config.py alias creation example

---

qutebrowser/browser/history.py
qutebrowser/misc/sql.py
tests/unit/completion/test_histcategory.py

Ideally, we'd update all existing tables to add the new constraints, but sqlite
doesn't offer an easy way to do so: https://www.sqlite.org/lang_altertable.html
Since that migration really isn't worth the effort, we only set the constraint
for new tables...
This came up with #3044 with @josefson - the import script didn't set the `redirect` field at all, so it was `NULL`, and qutebrowser silently treated that as "it's a redirect" when generating `CompletionHistory`.
(Not sure why that was, though, and I should probably fix that up as well... I guess `WHERE not redirect` is false when `redirect` is `NULL` for sql~~ite~~?)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrows …

Default to NOT NULL for table constraints

---

README.asciidoc
doc/contributing.asciidoc

I fixed some typos and some bullet lists that were not working. I also unified a bit the style in bullet lists (for example, there were items without an ending full stop while others had it).
Besides, I changed the license link to an http**s** link to the GPLv3, not all the GNU licenses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3058)

Small typos and bugs fixed in docs

---

qutebrowser/browser/browsertab.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webkit/webkittab.py
tests/end2end/data/long_load.html
tests/end2end/features/test_zoom_bdd.py
tests/end2end/features/zoom.feature
tests/end2end/fixtures/quteprocess.py
tests/end2end/fixtures/webserver_sub.py

This pull request is intended to fix #2507.
The problem this is solving is that using the WebEngine backend, the zoom will very frequently become stuck at the default 100% zoom level during a normal browsing session. This is caused by the fact that the zoom level needs to be set to the user-defined default zoom value __after__ the page has fully finished loading. Due to this fact a tab frequently becomes stuck at the 100% resolution because Qutebrowser uses the actual widget as the source of the zoom value.
This pull request adds a new private variable to `AbstractZoom` called `_zoom_factor` that is used to track the current zoom factor for a tab. Additionally, the `factor()` function is now implemented by the `AbstractZoom` class (previously this was implemented on the concrete tab …

Improved zoom level management and enforcement

---

misc/qutebrowser.spec
qutebrowser/app.py
qutebrowser/mainwindow/mainwindow.py
scripts/dev/build_release.py

These are some OSX-specific changes, required for being a default browser (see #22):
I've also done task 6 (as a `:`-command), but that will add some deps on osx (`pyobjc-framework-LaunchServices`, `pyobjc-framework-Cocoa`, `pyobjc-core`). As of 4 and 5 - the only option, that I haven't tried yet, requires going deeper in pyobjc land (see part 3 of the accepted answer [here](https://stackoverflow.com/questions/49510/how-do-you-set-your-cocoa-application-as-the-default-web-browser)).
Also need to make my changes compliant with the contributing guidelines. Haven't started on this, because the main work is not completed.
UPDATE: completed task 5, agreed to drop task 6.
UPDATE: completed task 4.
UPDATE: reverted task 4 due to bugs.
--- …

OSX URLs handling

---

qutebrowser/app.py
qutebrowser/browser/history.py
qutebrowser/misc/sql.py
tests/unit/browser/test_history.py
tests/unit/misc/test_sql.py

We mark some SQL errors as "environmental", and then show those as error
messages instead of raising an exception.
Fixes #3004
Workaround for #2930
@lahwaacz @rcorre Can you help with reviewing this?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3073)

Handle some sqlite errors gracefully

---

doc/help/configuring.asciidoc

The doc explains how to ignore flake8 errors, but the `c` and `config`
variables may also make pylint unhappy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3102)

Note how to ignore pylint in configuring doc.

---

qutebrowser/config/configdata.yml
qutebrowser/mainwindow/statusbar/bar.py

Addressing issue #3111 
Triggering passthrough mode colors the statusbar at the bottom dark-blue.
This is my first time trying to contribute to a public repository, so just tell me if I did anything wrong
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3119)

Issue3111: Separate color config for "pass-through mode"

---

qutebrowser/utils/version.py
scripts/setupcommon.py
tests/unit/utils/test_version.py

Replaces output of git-describe
Closes #3095 
Here's a new output of `qute:version`
```
qutebrowser v1.0.1
Git commit: 07105f4fe34048d062a3ad384d8893ef1430c71f (2017-10-13 21:33:03 -0400)
Backend: QtWebEngine (Chromium 49.0.2623.111)
```
I really dislike `git-describe` and I saw the issue that's why I'm doing this :P 
Let me know if you intended a different format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3118)

Change qute:version git commit to display hash

---

qutebrowser/mainwindow/tabwidget.py

This pull request tries to add more consistency to favicon spacing in vertical tab labels. Currently, smaller favicons can cause spacing issues resulting in the labels in the tabs list being misaligned. I worked around this by always allocating a consistent amount of space for the icon when the tabs list is vertical and always centering the image within this space. I feel that this results in a much more visually appealing and consistent tab list.
This has been a minor annoyance of mine for a while, but became especially apparent when I recently picked up the tree-style-tabs initial commit to play around with. You can see the specific issue in the following images:
Before:
After:
This change should not affect horizontal tabs at all.
Thanks!
--- …

Consistently space + center favicons when using vertical tabs

---

qutebrowser/commands/runners.py
qutebrowser/config/configdata.yml
tests/unit/commands/test_runners.py
tests/unit/config/test_configcommands.py

This fixes #623
Previously, trying to run a non-existent but partially-matching command would fail with "no such command" error, unless the number of partial matches was exactly one.
This adds the `completions.use_best_match` config (defaults to `false`) which if active uses the first of the completions suggestions even if more than one exists.
To illustrate, with `completions.use_best_match` set to `false` (default behaviour), typing `:do<enter>` would result in `no such command`
With `completions.use_best_match` set to `true` (new behaviour), typing `:do<enter>` results in running the `:download` command, since that's the best match
--- …

[RDY] Add option to run best partially-matching command

---

scripts/dev/pylint_checkers/qute_pylint/config.py

Useful for editors that run from non-root directories for integrations, but skips some tests. Shouldn't impact tests run normally. For example, flycheck runs pylint from the directory above the current file, which breaks all tests currenly (since it searches but cannot find `configdata.yml`). 
I also switched this test to use pathlib over os.
Let's see if travis prints the warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3149)

Fix crashes on qute_pylint module when not running in the root

---

qutebrowser/browser/commands.py
tests/end2end/features/tabs.feature

Closes #3138 
Very simple fix, telling `:home` to use the same function as `:open`, and allowing `:open` to take `QUrls` as well as strings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3150)

Prevent :home from bypassing pinned tab warnings

---

qutebrowser/config/configdata.yml
qutebrowser/misc/keyhintwidget.py

The radius for the keyhint dialog box should be configurable vi via
c.keyhint.radius. The default was set to 6px, which is the previous
hardcoded value.
Test:
Works fine, default was applied as expected. Changes are applied
successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3165)

Add keyhint radius configuration option

---

qutebrowser/config/configdata.yml
qutebrowser/mainwindow/tabbedbrowser.py
qutebrowser/mainwindow/tabwidget.py

As discussed in IRC, I don't like how middle clicking the tab bar closes the current tab. Chromium's behavior is to ignore it, and Firefox's is to open a new tab. I added these as options, as well as a "close-last" option for people who may misclick while closing tabs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3136)

Configurable behavior of close mouse button on bar

---

qutebrowser/app.py

This fixes blurry favicons on hidpi displays.
Related to https://github.com/qutebrowser/qutebrowser/issues/1585
Results on non hidpi display:
Results on hidpi display:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3129)

fix blurry favicons on hidpi displays

---

qutebrowser/config/configfiles.py
tests/unit/config/test_configfiles.py

#3195 Sorry for not totally obey contents described in [contributing doc](https://github.com/qutebrowser/qutebrowser/blob/master/doc/contributing.asciidoc), but I think this pull request contains very, very few modification to code base.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3196)

handle <EOL> of `:config-write-py` generated file

---

qutebrowser/completion/completer.py
tests/end2end/features/completion.feature

This fixes #2974 
Instead of setting `_ignore_change` to `True` before calling
`_change_completed_part` we just stop `_cmd` from emitting
`update_completion`.
This has the nice side-effect that when writing a complete command
`_ignore_change` was set to `True` regardless, and thus hitting space
would not update the completion view.
Now, hitting space will (as always) schedule a completion update that
now will not be incorrectly ignored
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3179)

[RDY] Avoid scheduling spurious completion updates

---

.pylintrc
qutebrowser/browser/commands.py
tests/end2end/features/editor.feature

The command :edit-url --private (or :edit-url -p) will spawn a new
private window with the url input from the editor.
I had to add 'Given I have a fresh instance' to the feature file to
ensure tests were not interfering.
Resolves #3185.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3200)

Add --private flag to edit_url.

---

qutebrowser/mainwindow/tabwidget.py
qutebrowser/misc/utilcmds.py
tests/unit/mainwindow/test_tabwidget.py

I noticed that in newer versions of qb, `:tab-move` has become much slower (it's only noticable if you bind it to a key, I `:bind <alt-h> :tab-move -`.
I took a profile and (as I suspected) there was a regression which was partially introduced in https://github.com/qutebrowser/qutebrowser/pull/2847 (but not all).
I took a profile:
So I decided to cache the minimumTabSizeHint function, which resulted in this profile
It still seems slower than before though....
This is a super low priority thing, so please handle other PR's first since they are more important :) 
One of the possible problems that I see is this won't have indicator and other padding changes take effect until text or icons change. Maybe I'll add a hook to clear the cache when those settings are reset...
---
This change …

Add caching for tab size hints

---

qutebrowser/mainwindow/tabbedbrowser.py

The Qt slot/signal paradigm is a lot nicer than I originally thought!
I don't think this will have any side effects, but I'm not 100% sure. Let's see if travis is happy :)
Is it possible to add a test which closes a qutebrowser window?
Closes #3223
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3228)

Abort pinned tab prompt if tab is destroyed

---

doc/help/settings.asciidoc
qutebrowser/browser/commands.py
qutebrowser/browser/webengine/webengineelem.py
qutebrowser/browser/webkit/webkitelem.py
qutebrowser/config/configdata.yml
qutebrowser/config/configtypes.py
qutebrowser/javascript/webelem.js
qutebrowser/misc/editor.py
tests/unit/config/test_configcommands.py
tests/unit/config/test_configtypes.py
tests/unit/misc/test_editor.py

Fixes #2725.
Added several possible placeholder to `editor.command` in order to be able to pass line and column numbers to the external editor in order to be able to place the cursor in the correct place in the buffer.
Added placegolders:
* `{file}` has the same function as `{}`
* `{line}` is the 1-based index of the target line in the buffer
* `{column}` is the 1-based index of the target column in the buffer
* `{line0}` is like `{line}` but 0-based
* `{column0}` is like `{column}` but 0-based
Also the placeholder check for shell commands accepts both `{}` or `{file}` placeholders
The reason `{line}` and `{column}` are 1-based by default is because most editors count lines and columns starting from 1. In fact I did not find any editor that starts counting lines or columns from 0. …

[RDY] Pass line and column number to external editor

---

qutebrowser/completion/completer.py
tests/unit/completion/test_completer.py

As requested in https://github.com/qutebrowser/qutebrowser/pull/3179#issuecomment-339581332, we can remove the `_ignore_change` attribute from the `Completer` class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3208)

[RDY] Make completer less stateful

---

qutebrowser/browser/qutescheme.py
tests/end2end/features/qutescheme.feature

qute://help (without the trailing slash) opens about:blank page due to path being empty. This fixes the issue by redirecting to the root path when path is empty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3215)
edit by @The-Compiler: Fixes #3161 (I think this needs to be in the body for GitHub to auto-close the issue)

Add trailing slash to qute://help pages

---

qutebrowser/completion/models/configmodel.py
qutebrowser/completion/models/listcategory.py
qutebrowser/completion/models/miscmodels.py
qutebrowser/completion/models/urlmodel.py
tests/unit/completion/test_histcategory.py
tests/unit/completion/test_listcategory.py
tests/unit/completion/test_models.py

There's also a fix for a histcategory test that was failing locally while working on this -- turns out it was timezone sensitive :grimacing:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3237)

Fix completion sorting

---

scripts/dev/run_vulture.py
scripts/importer.py

This adds supports for the places.sqlite format as used by Firefox, Seamonkey, Pale Moon, and presumably others. 
Search engine support is still limited to keyword-style '%s' functionality, as while the places database is fairly straightforward and backward-compatible (for reads, anyway) across everything in current use, the search engine file [is intentionally unstable in format to stop hijacking](http://blog.queze.net/post/2015/11/02/What-about-search-hijacking).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3229)

importer: add mozilla places.sqlite support

---

.github/CODEOWNERS
qutebrowser/config/configdata.yml

This PR contains several changes of the configdata descriptions:
* add units where appropriate (fixes #3171)
* apply trivial fixes:
* fixed typos
* add missing periods (.) add the end of descriptions
* fix capitalization of URL where appropriate
* break long lines (max. 79 chars as per PEP8)
* replace abbreviations by full expressions:
* ms -> milliseconds
* px -> pixels
* regexes -> regular expressions
* chars -> characters
* standardize description format:
* encapsulate units in parenthesis
* move units right behind the corresponding noun
* add articles where appropriate
* use 'whether' for bools (& boolAsks)
* use 'when' for selections
* drop phrases referring to the settings themselves ('set', 'control', ...)
Originally I just wanted to work on #3171 but I found some obvious mistakes …

[RFC] fix, extend & standardize configdata descriptions

---

misc/userscripts/cast

Custom location installed castnow can't be killed with the command `pkill -f /usr/bin/castnow`. Now recover the path to the binary in the path for calling and killing the program.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3244)

userscripts/cast: effectively kill old proc

---

qutebrowser/browser/commands.py
tests/end2end/features/tabs.feature

This is to match `:open` and because `:buffer` takes no other arguments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3247)

Support multiple words in buffer without quotes

---

.gitignore
qutebrowser/mainwindow/tabwidget.py

In reviewing these methods to try to find a cause for #3245, I found a couple minor bugs in the calculation of the minimum pinned with.
- Clear width cache when changing fonts (as font's can impact the size of tabs)
- Use correct calculation for the size of the icon (previously, we were using the minimum size)
- Fix extra space being added in pinned tabs when indicator is no longer present.
Before, setting the font size or favicon scaling in the tabbar caused the icon to scale (which wouldn't be reflected in the calculations for pinned tabs), making them too small to fit everything. Now, I *think* they scale correctly. 
I also discovered that these methods are essentially duplicating the work found in the [methods which determine where to place items in the …

Fix icon width calculation for pinned tabs

---

qutebrowser/completion/completionwidget.py
qutebrowser/config/configdata.yml
tests/unit/completion/test_completionwidget.py

Adds:
- `completion-item-yank` bound to `<ctrl+c>`
- `completion-item-yank --sel` bound to `<ctrl+shift+c>`
I often find myself in this situation:
1. "Hey, what's the url for X?"
2. "I have it bookmarked, let me get that for you"
3. `:open`
4. Find the item
5. Press Enter
6. Wait for the page to load (as yank won't work before the page loads)
7. `yy`
Now you can press <ctrl+c> after step 4.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3249)

Completion yank

---

qutebrowser/mainwindow/tabwidget.py

See #3245 
@helbling, I'm confident this will fix #3245, could you please verify that for me on this branch?
This is still a wip, I haven't verified all the edge cases, but the tab sizing seems right when I add `&`'s to `title_format_pinned`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3254)

Fix Qt Mnemonics affecting min tab width

---

doc/help/commands.asciidoc
qutebrowser/browser/commands.py
qutebrowser/mainwindow/tabbedbrowser.py
tests/end2end/features/tabs.feature

This changes the undo stack from a list of `UndoEntry` objects to a list of lists of `UndoEntry` objects, so groups of tabs can be added. Only `:tab-only` does that, but it's exposed by `TabbedBrowser.close_tab` as a keyword argument.
I've pressed `co` by mistake a few times. This should make it less destructive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3253)

Make :undo re-open all tabs closed by :tab-only

---

qutebrowser/browser/webkit/network/filescheme.py

Fixes #1450 
This fixes the crash, instead displaying an error.
It's not the best option, but it's better than a crash
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3175)

[RDY] Avoid crash with `LC_ALL=C` and unicode filename

---

pytest.ini
qutebrowser/config/config.py
tests/unit/config/test_config.py

I ran the test selectively like this: `tox -e py36 -- tests/unit/config/test_config.py` and it seems to work properly. However, even without any of the changes, I get the following for some reason: `FAIL tests/unit/config/test_config.py::TestKeyConfig::()::test_bind[message-info foo-normal]` in the summary. I'm unsure what's going wrong there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3259)
edited by @The-Compiler: Fixes #3251

Prevent empty commands from being bound

---

qutebrowser/config/configdata.yml
qutebrowser/mainwindow/tabwidget.py

Closes #3226
I'm not sure if the name/description of this setting is good. Let me know if you think they are off. (also, it's so easy to add new settings! :smile: )
I don't think there's a good way to unit or end2end test tab sizes, is there a way to do that?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3266)

Add setting to avoid shrinking pinned tabs

---

qutebrowser/config/configdata.yml

Many people accidentally hit 'x{x,t,b}', hiding their statusbar by mistake
Discussion on IRC:
```
<radiantgum> Hello guys, my top panel with tabs in qutebrowser is gone and i
can't find a way to bring it back, please give me a clue. Thank
you [03:51 PM]
<jgkamat> radiantgum: :set tabs.show always [03:52 PM]
<radiantgum> thanks a lot
<jgkamat> I think there's a keybind that toggles that setting, dont remember
what it was [03:53 PM]
<pkill9> jgkamat: xx [03:57 PM]
<pkill9> and xt
<jgkamat> ah yes [03:58 PM]
<jgkamat> imho that shouldn't be a default :P  [03:59 PM]
<The-Compiler> I think I agree after seeing so many people accidentally
trigger it, even though dwb has it :P [04:06 PM]
<The-Compiler> Open a PR so I don't forget again? :D [04:07 PM]
```
--- …

Remove default config-cycle bindings.

---

qutebrowser/completion/models/urlmodel.py
tests/unit/completion/test_models.py

If there are no quickmarks/bookmarks, hide the entire category in url
completion. Note that this only hides the category if
quickmarks/bookmarks is empty to begin with. An empty category is still
shown if the completion pattern filters out all items in that category.
See #960. I think it makes sense to implement category hiding on a case-by-case basis (just not adding empty categories) rather than implemeting some more complex logic to hide empty categories in the parent completion model.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3279)

Hide quickmark/bookmark completion if empty.

---

qutebrowser/config/config.py
tests/unit/config/test_config.py

Fixes #3263, may help with #1476.
There is a memory savings here, but I'm still not sure how much. If you want to test it out for yourself you could try:
```
diff --git a/qutebrowser/mainwindow/statusbar/url.py b/qutebrowser/mainwindow/statusbar/url.py
index a91c67550..25493920c 100644
--- a/qutebrowser/mainwindow/statusbar/url.py
+++ b/qutebrowser/mainwindow/statusbar/url.py
@@ -88,6 +88,8 @@ class UrlText(textbase.TextBase):
self._normal_url = None
self._normal_url_type = UrlType.normal
+        for i in range(10000 * 6 * 5):
+            config.set_register_stylesheet(self, update=False)
@pyqtProperty(str)
def urltype(self):
"""Getter for self.urltype, so it can be used as Qt property.
```
or similar, and see how the memory usage on your system changes before/after this patch.
The only …

Fix garbage collection of StyleSheetObserver objects

---

qutebrowser/browser/webengine/webengineelem.py
qutebrowser/javascript/webelem.js
qutebrowser/misc/editor.py
tests/unit/misc/test_editor.py

With Chromium 61 in Qt 5.10, we get null when getting .selectionStart on a
non-text element, like described in the WhatWG HTML standard:
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#dom-textarea/input-selectionstart
Older QtWebEngines and QtWebKit raise InvalidStateError instead.
This also changes the surrounding code and API so None is used to say "there's
no caret position available", which seems like a nicer API.
@7lb, can you please take a quick look at this?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3258)

Fix handling of caret position with Qt 5.10

---

qutebrowser/utils/version.py
tests/unit/utils/test_version.py

Sorry for taking an easy issue but I really wanted this for memory testing in the future. 
Closes #3265.
1. Is that a good location to put the uptime in the version output?
2. Is calling `QApplication.instance()` safe? Can it error out?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3286)

Add an uptime section to qute:version

---

qutebrowser/completion/completionwidget.py
tests/unit/completion/test_completionwidget.py

If text is highlighted in the status command bar, completion-item-yank
should yank that rather than the selected completion item.
Resolves #3281.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3290)

Yank selected text with completion-item-yank.

---

qutebrowser/config/configdata.yml
qutebrowser/mainwindow/mainwindow.py
qutebrowser/misc/miscwidgets.py

#3213 Adds `content.desktop_fullscreen` config option to enable/disable fullscreen covering the entire desktop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3285)

Limit fullscreen to window only

---

qutebrowser/browser/navigate.py
qutebrowser/browser/qutescheme.py
tests/end2end/features/navigate.feature
tests/end2end/features/qutescheme.feature

fixes #3221, Also prevents AssertionError in qute://help pages when url resolves to a directory path by raising an OSError beforehand
@The-Compiler I hope I've added test scenarios appropriately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3291)

normalize url path and strip trailing slashes when doing gu/gU

---

qutebrowser/browser/downloads.py
qutebrowser/browser/qtnetworkdownloads.py
qutebrowser/browser/webengine/webenginedownloads.py
tests/end2end/features/downloads.feature

Closes #2120 
Hi!
This is my first real pull request here on github! :)
Nothing really complicated going on, I just split `_set_filename`, so that we can display the prompt. flake8 and pylint seem to pass, and I updated the relevant feature test.
Thanks, best regards, congratulations on writing my favorite browser! :)
Panos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3097)

Prompt for non-existing download directories.

---

qutebrowser/mainwindow/statusbar/command.py
tests/end2end/features/editor.feature

:edit-command opens the current command line in an editor, and updates
the command line if the editor exits successfully. If --run is passed,
the command is executed when the editor exits sucessfully.
Resolves #2453.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3306)

Implement :edit-command.

---

qutebrowser/mainwindow/statusbar/command.py
tests/end2end/features/editor.feature

Resolves #3317, where the command prompt was left open and populated
with text after running the command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3318)

Exit command mode after :edit-command --run.

---

qutebrowser/config/configdata.yml
qutebrowser/mainwindow/tabbedbrowser.py

Implements #3065. The current behaviour is retained by default, with a config option added to enable the new behaviour.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3323)
---
edit by @the-compiler: Closes #3065

Add option to persist current mode on tab change

---

qutebrowser/mainwindow/statusbar/command.py
tests/end2end/features/editor.feature
tests/end2end/features/test_editor_bdd.py

Show an error message if the user edits the command such that it is
missing a start character (:, /, or ?). Previously, this would cause the
browser to crash.
Resolves #3326.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3328)

Abort :edit-command on invalid input.

---

misc/qutebrowser.desktop

These links mostly occur within qutebrowser's documentation.  But the
are also written to the auto generated config file.  Clicking them in
any application that consults the desktop database (or uses xdg-open)
will thus open them in qutebrowser correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3330)

Register qutebrowser as a handler for qute:// links

---

doc/help/commands.asciidoc
doc/help/settings.asciidoc
qutebrowser/browser/qutescheme.py
qutebrowser/config/configdata.yml
qutebrowser/html/back.html
qutebrowser/misc/sessions.py
tests/unit/misc/test_sessions.py

Lazily restore sessions:  
I added an option "session_lazy_restore"(1) which allows to expand the history on restoring a tab.  
The new history entry is the page qute://back which simply executes window.history.back() as soon as it receives a focus event.  
Use cases:  
- reduce load
- reduce (mobile) data usage
- avoid auto play 
(1) I named it like "session_default_name".  
However shouldn't it be named "session.default_name" and "session.lazy_restore", so it would fit to the other entries?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3309)

Lazy sessions

---

qutebrowser/browser/hints.py
tests/end2end/test_hints_html.py

Possible fix for https://github.com/qutebrowser/qutebrowser/issues/3242, although I would prefer another solution if someone can come up with one.
I've manually tested the edge cases, but I would like to add unit tests as well. Is it possible for me to contstruct a fake `HintManager` in a way that I can still call the `_hin_scattered` function? When I tried to construct one manually, I got errors for referring to a non-existent window.
Closes #3242
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3329)

Fix undercounting short hints

---

qutebrowser/browser/browsertab.py
qutebrowser/browser/commands.py
qutebrowser/browser/webelem.py
qutebrowser/browser/webengine/webengineelem.py
qutebrowser/browser/webkit/webkitelem.py
tests/end2end/features/editor.feature
tests/end2end/features/test_editor_bdd.py
tests/unit/browser/webkit/test_webkitelem.py

If an editor is open on a form in a tab and that tab is closed, rewire
the callback to print a warning. Previously, the callback would access a
deleted C++ object and cause a crash.
Resolves #2758.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3333)

Resolve crash when editor tab is closed.

---

qutebrowser/completion/models/histcategory.py
tests/unit/completion/test_histcategory.py

Resolves #1649.
I'm not seeing any noticeable difference in speed on my machine, and the benchmark times are similar. Still, it might be nice if a few people could try this out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3367)

History completion by both URL and title.

---

qutebrowser/app.py
qutebrowser/browser/browsertab.py
qutebrowser/browser/greasemonkey.py
qutebrowser/browser/webengine/webenginesettings.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webengine/webview.py
qutebrowser/browser/webkit/webpage.py
qutebrowser/javascript/.eslintignore
qutebrowser/javascript/greasemonkey_wrapper.js
qutebrowser/utils/jinja.py
qutebrowser/utils/log.py
tests/end2end/features/javascript.feature
tests/end2end/features/test_javascript_bdd.py
tests/end2end/fixtures/quteprocess.py
tests/unit/javascript/test_greasemonkey.py

Adds support for reading in userscripts from `<datafolder>/greasemonkey` -(configurable)- and injecting them into pages based on the greasemonkey compatible metadata block.
Tested on (old)webkit and qtwebengine 5.9. qtwebengine 5.7 and below not supported allthough I can add that finicky stuff back in if people actually want it.
Most of the work comes from andor44's fork from a couple of years ago. The impact on the existing codebase is very small. On webkit we manually pick scripts to inject in event handlers on webengine deciding when to inject and on what pages is handled for us.
greasemonkey.py wraps the userscripts in a simple lexical scope along with a bunch of GM_ functions that are used by various userscripts floating about, certainly not all of the ones listed on the docs page. …

Greasemonkey

---

doc/help/commands.asciidoc
qutebrowser/browser/commands.py
qutebrowser/browser/qutescheme.py
qutebrowser/misc/guiprocess.py
scripts/dev/run_vulture.py
tests/unit/misc/test_guiprocess.py

This puts the exit status, stdout, and stderr in a new tab when spawn is called with the flag.
This modifies guiprocess.py, so in principle the spawn_output variable could be renamed and used for other processes that could use a simple textual output.
This is my first public contribution to any software, please be gentle :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3374)

Add --output flag for :spawn.

---

qutebrowser/browser/downloads.py
qutebrowser/browser/webengine/spell.py
qutebrowser/config/configtypes.py
qutebrowser/keyinput/basekeyparser.py
qutebrowser/misc/crashdialog.py
qutebrowser/misc/keyhintwidget.py
qutebrowser/utils/debug.py
qutebrowser/utils/docutils.py
qutebrowser/utils/urlutils.py
qutebrowser/utils/utils.py
scripts/asciidoc2html.py
scripts/dev/run_vulture.py
scripts/dictcli.py
tests/end2end/conftest.py
tests/end2end/fixtures/quteprocess.py
tests/end2end/fixtures/testprocess.py
tests/unit/misc/test_checkpyver.py
tests/unit/utils/test_debug.py
tests/unit/utils/test_utils.py

`re.match` features an implicit left anchor, which can be surprising!
in contrast:
`re.fullmatch` features implicit anchors on both sides, but is aptly named
and therefore unsurprising.
`re.search` has no such implicit anchors, which ought to be the default
even if a single anchor is needed.
By modifying the existing instances, we can in future encourage all contributors to use one or the other of the alternatives and ensure that the regex used is the regex that is intended to be used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3382)

Modify usage of re.match to fit re.fullmatch or re.search.

---

misc/userscripts/password_fill

The password_fill broke in 595a53ad3b29570bed35764b0b2cbfdda9af2dfe. More precisely the libsecret backend.
The regex matching the username prefix was replaced with globbing, but you can't use `BASH_REMATCH` then. As this is a constant prefix of constant length, I replaced it with a simple position-based substring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3392)

fix password_fill using libsecret

---

qutebrowser/config/configdata.yml
qutebrowser/mainwindow/statusbar/command.py
tests/end2end/features/misc.feature

command-accept --rapid will run the command without clearing the prompt,
allowing "rapid fire" commands. For example, one could open completion
for `open -t` and open several tabs in a row.
The default binding is ctrl+enter.
Resolves #588.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3393)

Implement command-accept --rapid.

---

qutebrowser/completion/completiondelegate.py
qutebrowser/config/configdata.yml
tests/unit/config/test_config.py

Now colors.completion.fg may be set to a list to specify a different
color for each completion column. For example:
:set colors.completion.fg [black,blue,white] will use black text for the
first column, blue for the second, and white for the third.
Setting to a single value still works and behaves as before. The default
is unchanged from 'white'.
Resolves #1794.
It looks like this after `set colors.completion.fg '["white","#999999","#777777"]'`:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3407)

Support different colors per completion column.

---

doc/faq.asciidoc

The link to the stacktrace guide is wrong. https://www.qutebrowser.org/doc/faq.html#footer
If this isn't the correct fix just close this and fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3422)

Fix broken link

---

qutebrowser/browser/webengine/webenginetab.py
tests/end2end/features/marks.feature

This uses the much more reliable `loadProgress(100)` in place of
`loadFinished(true)` for WebEngine, with `loadProgressFake` and
`loadFinishedFake` used instead of the 'official' variants.
Fixes #3401 and #3110.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3427)

supplement broken webengine load signals

---

doc/help/configuring.asciidoc

Just a minor typo fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3441)

Fix minor doc typo in example code

---

qutebrowser/completion/completer.py
tests/unit/completion/test_completer.py

Always interpret the first word in the command string as the command to
offer completions for, even if that word looks like a flag.
Fixes #3460, where the command string `:-w open` would attempt to offer
completions for `open` but crash because the parsing was thrown off.
By moving the flag-stripping logic to _after_ we determine the command,
`:-w open` interprets `:-w` as the command. Since that is not a valid
command, we won't offer any completions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3468)

Don't attempt completion if input starts with flag.

---

qutebrowser/browser/commands.py
qutebrowser/mainwindow/mainwindow.py

On OSX, currently if you open the external editor and finish editing, the edited content will get copied into the the appropriate input field but the editor will remain the "active app", that is qutebrowser will not have focus and will not receive further keystrokes until you click or cmd-tab back into it. I don't know if this is also the behavior on other platforms but if focus is being redirected there it shouldn't hurt to set it again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3432)

Return focus to qutebrowser when external editor finishes.

---

scripts/hist_importer.py

came across a tiny issue when importing history from my firefox profile. I had some records with None fields in atime and title.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3445)

filter out records with None in any field.

---

scripts/hist_importer.py

We don't need to import history records about `moz-extensions`, `about` pages, `dactyl` and so on...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3464)

scripts: filter history records

---

qutebrowser/browser/commands.py
qutebrowser/mainwindow/tabbedbrowser.py
tests/end2end/features/tabs.feature

Closes #3461
If anyone thinks the new behavior seems wrong, let me know.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3467)

Clear unpinned tabs before prompting user with :tab-only

---

qutebrowser/browser/qutescheme.py
qutebrowser/config/configcommands.py
qutebrowser/html/bindings.html
tests/unit/config/test_configcommands.py

implement issue #24
currently only shows bindings for the following key modes: normal, hint, command, insert, passthrough
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3484)

show current bindings when calling "bind" command without arguments

---

qutebrowser/browser/greasemonkey.py
tests/unit/javascript/test_greasemonkey.py

Like the spec says, if a value for the @include or @exclude rules starts
and ends with a '/' it should be parsed as a regular expression.
https://wiki.greasespot.net/Include_and_exclude_rules
Technically an ECMAScript syntax regular expression, but I am not sure of
the differences and I assume they are far fewer than the similarities.
One that I did see mentioned was that javascript RegExp doesn't support
unicode. Although it apparently does support a 'u' flag now.
Anyway, I'm just being lazy and passing is blindly to the python re module. Also I haven't used that much so hopefully I am not using the returned thing wrong.
Note that code will only be ran for QtWebkit and QWebEngine < 5.8
we rely on the builtin support for metadata it QWebEngine for most
things greasemonkey related. Sadly …

Greasemonkey: support regexes in @include and @exclude.

---

qutebrowser/misc/sql.py

Enable write-ahead-logging and reduce the synchronous level to NORMAL.
This should reduce the number of writes to disk and avoid some of the
hangs users are experiencing.
Resolves #3507.
Resolves #2930 (optimistically, reopen if not fixed).
See https://sqlite.org/pragma.html and https://www.sqlite.org/wal.html.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3509)

Set some PRAGMAs to optimize the history database.

---

qutebrowser/completion/completiondelegate.py

When highlighting the matched part of the text, we need to html-escape
the pattern used to find the matching text so it will replace terms that
have been escaped in the text, like &amp;.
Resolves #3508.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3510)

Show '&' properly in completion widget.

---

qutebrowser/browser/browsertab.py
qutebrowser/browser/commands.py
qutebrowser/browser/history.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webkit/webkittab.py
tests/end2end/features/history.feature
tests/unit/browser/test_tab.py

Use WebEngine's view-source: scheme for "view-source" command.
Inject qutebrowser's JS files at DocumentReady
Also add missing URL when viewing source for WebKit.
Resolves #3490
Resolves #2395
Resolves #2948
A bit less intrusive than the last PR, but we still need to test this to make sure injecting Qutebrowser's JS files at DocumentReady instead of DocumentCreation does not cause problems elsewhere.
If you guys can try this on your end, I'll be running this code from now on and report any odd behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3521)

view-source command now using scheme

---

README.asciidoc

http://pyyaml.org/wiki/PyYAML says:
> PyYAML is now maintained at https://github.com/yaml/pyyaml. This page is left for historical purposes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3543)

Updated PyYaml link

---

qutebrowser/browser/commands.py
qutebrowser/config/configcommands.py
qutebrowser/mainwindow/statusbar/command.py
qutebrowser/misc/editor.py
tests/end2end/features/editor.feature
tests/end2end/features/test_editor_bdd.py
tests/unit/config/test_configcommands.py
tests/unit/misc/test_editor.py

For any command that spawns an editor, tirgger an update on save, not
just on exit.
- :open-editor writes the text field on save
- :edit-url navigates on save
- :edit-url -t opens a new tab on each save
- :edit-command updates the statusbar text on save
- :edit-command --run runs a command on each save
- :config-edit reloads the config on save
Resolves #2307.
Helps mitigate #1596 by allowing users to 'save' partial work, and
notice if there was an error without closing the editor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3431)

Editor triggers update on every save.

---

qutebrowser/mainwindow/mainwindow.py

Hi, I decided to start working on #1716 as a hobby (not even sure if I'll be able to finish it, so nothing official), and since it'll force me to review almost the entire codebase I figured it would be a good opportunity to propose small/aesthetic changes while I'm at it.
In this case I noticed the same object being accessed via two different references: an instance attribute and using the object registry. I guess the first one makes more sense. Let me know if this makes sense.
Love your browser 👍
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3544)

Use the instance attribute instead of querying the registry

---

doc/help/commands.asciidoc
qutebrowser/browser/commands.py

The new `--no-last` flag prevents going to the last focused tab if a new tab does not
need to be focused.
Closes #3553.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3554)

Add a new --no-last flag to :tab-focus

---

qutebrowser/browser/webengine/webenginedownloads.py

Closes #3373 
On IRC, we discussed deleting the `_qt_item` object when we receive a `remove_requested` signal, however, I think that deleting it when the wrapper object is destroyed is a better solution, because it has a lower chance of the wrapper and the C++ object becoming disconnected, for example, due to a bug on the python side. Let me know if you prefer to do it the other way if you still think it is better, though.
I still want to do more testing, but from what I see so far, this seems to cause no problems for me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3555)

Delete QWebEngineDownloadItem objects when wrapper object is deleted

---

qutebrowser/browser/browsertab.py
qutebrowser/browser/commands.py

This PR handles suggestion #3539 
After this, using `:view-source --edit` will open the current page's source in the set editor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3563)

Add a way to view source in editor

---

qutebrowser/config/configdata.yml
qutebrowser/mainwindow/statusbar/backforward.py
qutebrowser/mainwindow/statusbar/bar.py
qutebrowser/mainwindow/statusbar/percentage.py
qutebrowser/mainwindow/statusbar/progress.py
tests/unit/mainwindow/statusbar/test_backforward.py
tests/unit/mainwindow/statusbar/test_percentage.py
tests/unit/mainwindow/statusbar/test_progress.py

I'm trying to implement the option in #598.
I have absolutely zero experience with PyQt and qutebrowser so I require some assistance here.
`config.statusbar.widgets` is similar to other format string options and it allows to change the order of the widgets, hide one or more widgets, insert an arbitrary text.
This is mostly working however there are a couple things to fix/do yet:
1. [x] If the `backforward` widget is hidden it will cause a new empty window to appear when opening a page
2. [x] Widgets have a margin, it should be removed so that spacing can be controlled from the format string like `"{scroll} {tabs}"`
3. [x] Add a `scroll_raw` widget without the % sign
4. [x] Fix the tests
--- …

Make statusbar widgets configurable [WIP]

---

qutebrowser/mainwindow/tabbedbrowser.py
qutebrowser/mainwindow/tabwidget.py
tests/helpers/stubs.py
tests/unit/mainwindow/test_tabwidget.py

I tested this all on ~80 about:blank tabs.
We call 'update_tab_titles' a lot of times which calls 'setTabText' on
every tab. 'setTabText' calls tabSizeHint and minTabSizeHint on every
tab as well, meaning this is an n^2 operation repeated many times.
First, this prevents setTabText from being called unless it's needed,
removing most of the work done.
Second, I remove tabs in reverse, to avoid recomputing the above for
every tab on shutdown (which is at least n^3)
The next target for optimization is paintEvent in tabWidget, as that 
seems to be the biggest issue after this patch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3582)

Improve performance of startup and shutdown with many tabs

---

qutebrowser/browser/qutescheme.py
qutebrowser/html/version.html
qutebrowser/misc/pastebin.py
qutebrowser/misc/utilcmds.py
qutebrowser/utils/utils.py
qutebrowser/utils/version.py

This PR is a work in progress, continuing on from the work done by @Transfusion in PR #3480 
Currently this applies all the code review changes suggested to the commit in the previous PR.
It's not completely satisfactory yet, in the following ways:
1. It instantly pastes when running, making the button pointless. - wasn't a bug, the button is meant to be there all the time, my bad
2. It doesn't store the url anywhere incase the command is ran again in the same session. The version shouldn't change for a given session. - done
I think this is now done, pending a code style review of course. Shadiest thing is using a global variable to store the paste url in. Alternatively, perhaps it could be stored in the registry?
---
This change is [<img src="https://reviewable.io/review_button.svg" …

Add :version --paste

---

qutebrowser/config/configexc.py
qutebrowser/config/configfiles.py
tests/unit/config/test_configcommands.py
tests/unit/config/test_configexc.py
tests/unit/config/test_configfiles.py

Solves (in a way) #3494 
I'm not 100% happy with this as a solution as it doesn't seem clear to me why `traceback.format_exc` isn't printing all the information. AFAIK it's meant to essentially do something like `*sys.exc_info()`
Throwing this PR in anyway, as @The-Compiler may have more knowledge about which area I should be looking at instead
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3561)
*edit by @The-Compiler to auto-close the issue: Fixes #3494*

Display exception type in configfiles

---

qutebrowser/browser/urlmarks.py
tests/unit/browser/urlmarks.py

I was adding some unit tests before starting #882 and noticed that `bookmark-add --toggle` won't mark the file as dirty when removing a bookmark.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3584)

Unit test bookmarks and fix one bug

---

doc/contributing.asciidoc

The language tags were changed (I think) at some point, which broke these links, making them show 'zero issues'. This fixes that!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3602)

Fix broken language links in contributing

---

qutebrowser/commands/runners.py
tests/end2end/features/misc.feature

This commit is a small extension to the variable substitution which simply remaps '{{url}}' to '{url}' for example.
It's a small change but should be considered temporary until better argument parsing comes along. It could be seen as a negative change as it infact adds some _more_ special cases, however I think this will be trivial to handle when said rework arrives.
See issues #1861 and #2017 for more information.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3562)

Add special cases of double quoted variables

---

tests/end2end/fixtures/test_webserver.py
tests/end2end/fixtures/webserver.py
tests/end2end/fixtures/webserver_sub.py

Part of #3020.
Very small refactor to use the new [HTTPStatus](https://docs.python.org/3/library/http.html#http.HTTPStatus) enum introduced in 3.5.
Added some more tests for all the changed endpoints to just be able to test these without having to run the whole end2end suite.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3599)

Use HTTPStatus enum from Python 3.5+

---

misc/userscripts/readability

I poked in the readability userscript, and I found it's hardcoding the data dir for readability.html, this PR changes it to use the QUTE_DATA_DIR environment variable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3610)

Use QUTE_DATA_DIR in readability userscript

---

README.asciidoc
scripts/asciidoc2html.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3617)

use up to date cheatsheet images from repo instead of qutebrowser.org

---

qutebrowser/javascript/webelem.js
tests/end2end/features/search.feature

baseNode isn't documented anywhere that I can find, but it seems to be getting us what anchorNode used to get us when selecting elements using javascript.
See https://stackoverflow.com/a/45246087 for the best information I could find on this.
Ideally we could figure out why anchorNode changed behavior in 5.10.1, or figure out what baseNode does. 
Let's see if this fixes the broken test on master first though, it dosen't seem to affect the behavior of :follow-selected when links are selected manually, for me at least.
(It might not be a good idea to use baseNode though, since it's not documented. I'll see if I can tweak the test and/or debug this further to try to avoid using this method, but this is what I have for now)
--- …

Use baseNode over anchorNode in follow-selected

---

qutebrowser/app.py

Fixes crash upon receiving invalid URL in OSX open event, as reported in #3633.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3637)

Handle invalid URLs on Apple events

---

pytest.ini
qutebrowser/browser/webengine/webenginetab.py
tests/conftest.py
tests/end2end/features/caret.feature

Converts the currently searched text to a selection when entering caret mode!
This is probably going to break on qt5.8 and 5.9 due to [this qtbug](https://bugreports.qt.io/browse/QTBUG-60673), we'll see if travis gets annoyed.
If it dosen't work on the qt version that's being run, should we print an error, or just let it be? 
Also, if someone could test this on 5.10, that would be nice (since the bug was supposed to be fixed in 5.10)!
Progress on #3583
(The missed search shown is #3511 by the way :P)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3620)

Convert searched text to a selection when enetering caret mode

---

qutebrowser/browser/commands.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webkit/webkittab.py
tests/end2end/features/search.feature

I discovered that #3511 was only an issue on webengine, as duplicate search requests seemed to be ignored on qtwebkit (from the backend). 
I think that ignoring the duplicate search requests is the best idea on qtwebengine, since the alternative (ignoring search on enter) feels a bit hacky to me. 
Let me know if the other way is preferred. 
I also changed the behavior of clearing when searching to only clear when needed, which seems to both reduce a lot of flickering when incsearching for me, and also allows the duplicate search filtering to work (previously, it would clear even when the search didn't go through). 
Let me know if anything seems amiss.
Fixes #3511
--- …

Ignore duplicate search requests on webengine

---

qutebrowser/completion/models/configmodel.py
scripts/dev/check_coverage.py
tests/unit/completion/test_models.py

Fixes #3649 and bumps the test coverage for `configmodel.py` to 100%.
@rcorre mind giving this a quick look?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3650)

Fix getting customized options

---

qutebrowser/browser/webkit/webkittab.py

Fixes old search results showing up after #3626 
Pretty simple fix, but let me know if anyone finds issues with it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3659)

Clear old search results on webkit

---

qutebrowser/completion/completer.py
tests/unit/completion/test_completer.py

When min_chars is nonzero, if the first command that opens the
completion has < min_chars on the word under the cursor, it triggers a
check for a condition where last_cursor_pos is None.
By setting last_cursor_pos=-1 we ensure that the completer always
updates the first time it is opened, and that there is never a check
against None.
This adds a test for the min_chars feature.
Resolves #3635.

Don't crash first completion update with min_chars.

---

qutebrowser/browser/webkit/webpage.py

Hopefully closes #3627
This feels like fixing the symptom instead of the problem but I am not
sure how such a situation would arise. Never the less, the crash logs
clearly show that `_inject_userjs()` is being called with a deleted
frame sometimes. It is being called from a closure that gets triggered
on frame.loadFinished so I am not sure how frame could be deleted at
that time unless:
* the error message is misleading and it is actually some reference to
the object that is no longer valid
* the frame gets deleted from some other handler of loadFinished.
No need to take similar action in webengine/webview.py because that doesn't handle subframes anyway.
--- …

Greasemonkey: don't inject JS into dead frames

---

qutebrowser/browser/webelem.py

The reaction button on PRs and comments on GitHub for example is a `<summary>` that couldn't be triggered with hints. This PR fixes that.
PS: Still WIP because I'll add some tests when I have the chance
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3676)

WIP: Add hints to <summary> elements

---

qutebrowser/browser/downloads.py
qutebrowser/browser/greasemonkey.py
qutebrowser/javascript/greasemonkey_wrapper.js
tests/helpers/fixtures.py
tests/helpers/stubs.py
tests/unit/browser/test_adblock.py
tests/unit/javascript/test_greasemonkey.py

This PR adds support for fetching scripts that greasemonkey user scripts specify as dependancies via the `@require` rule. And delaying the injection of said scripts into webpages until the dependancies have been fetched.
Also I have included a commit to mock the new greasemonkey 4.0 promises based API. Because the motivation for this work was getting the https://github.com/StylishThemes/GitHub-Dark-Script userjs to work and it was hard to test without. (It also requires regex `@includes` support and cross origin GM_xhr requests though.)
I made a change to the download manager to support overwriting files without prompting, see the commit message for that one for an alternative way of doing it.
I am using the download_stub fixture from the test_adblock.py and made a change to it to support …

Greasemonkey @require support

---

qutebrowser/utils/version.py
tests/conftest.py
tests/unit/utils/test_version.py

For POSIX OSes other than Linux and macOS set OS Version to
platform.uname() instead of showing 'OS Version: ?'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3700)

Show version for POSIX OSes

---

qutebrowser/mainwindow/prompt.py
tests/unit/mainwindow/test_prompt.py

There are some code duplications and I'm not sure if it actually needs to sit in a seperate method. I'm also not sure if completion should be just enabled by having a configuration variable. 
~~It also would be nice to set the text back to the entered text on wrapping around.~~ (done in second commit)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3606)

add basic completion to file dialog

---

qutebrowser/app.py
qutebrowser/browser/commands.py
qutebrowser/browser/hints.py
qutebrowser/browser/signalfilter.py
qutebrowser/completion/models/miscmodels.py
qutebrowser/mainwindow/mainwindow.py
qutebrowser/mainwindow/statusbar/backforward.py
qutebrowser/mainwindow/statusbar/bar.py
qutebrowser/mainwindow/tabbedbrowser.py
qutebrowser/mainwindow/tabwidget.py
qutebrowser/misc/sessions.py
qutebrowser/misc/utilcmds.py
qutebrowser/utils/objreg.py
tests/helpers/stubs.py
tests/unit/browser/test_signalfilter.py
tests/unit/completion/test_models.py
tests/unit/mainwindow/statusbar/test_backforward.py
tests/unit/mainwindow/test_tabwidget.py

Issue #600 
The following changes were made to refactor _TabbedBrowser_:
- TabbedBrowser now inherits from QWidget
- An instance of the class _TabWidget_ was created in the class _TabbedBrowser_ called **widget**
- Redirect all related function calls
- The following two functions of the class  _TabWidget_  are now public: _update_tab_title_, _update_tab_titles_
- Create the class _TabWidgetStub_, which is called by the class _TabbedBrowserStub_ and has the same functionality as the class _TabWidget_
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3613)

Refactor TabbedBrowser from inheritance to composition

---

qutebrowser/javascript/webelem.js
tests/end2end/data/hints/issue3711.html
tests/end2end/data/hints/issue3711_frame.html
tests/end2end/features/hints.feature

In qt5.9 (or the attached chrome version) there seems to be a bug where the exception thrown is a plain `DOMException` rather than a `frame.DOMException` if this kind of element is in a frame. 
I also added a test which passes for me on 5.9 (but fails on master), let's see if CI likes it for the other targets.
Closes https://github.com/qutebrowser/qutebrowser/issues/3711
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3713)

Fix Hinting on input ranges in qt5.9

---

qutebrowser/browser/commands.py
qutebrowser/misc/editor.py
tests/end2end/features/editor.feature
tests/unit/misc/test_editor.py

Currently the editor deletes its temp file whenever editing is finished.
With this patch, the file will not be deleted if the editor callback
encounters an exception.
One example is if the tab containing the edited element is closed. The
editor errors with "Edited element vanished", but with this patch it
will also print "Backup at ..." so the user does not lose their work.
Resolves #1596.
Supersedes #3641, using the cleaner approach started in #1677.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3704)

Preserve a backup if editor callback fails.

---

qutebrowser/config/configdata.yml

This Pull Request tries to fix Issue#3629 
I was not sure about whether to set minval to 0 or not as negative values seem pretty useless for this option.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3733)
[edit by @jgkamat to link issues: Closes #3629]

Add correct maximum and minimum value for tabs.switching_delay 

---

qutebrowser/config/configdata.yml
qutebrowser/utils/urlutils.py
tests/unit/utils/test_urlutils.py

when set to true, invoking a searchengine shortcut without argument
opens the baseurl of that searchengine instead of DEFAULT searchengine
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3604)

Add Option url.open_base_url

---

qutebrowser/config/configdata.yml
qutebrowser/mainwindow/tabwidget.py

This adds the setting requested in #3690.
I also fixed a bug in pinned width calculation which this PR exposed, which caused pinned tabs to occasionally be counted as one-width if there was absolutely no space at all in the tabbar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3692)

Add a tabs.min_width setting

---

qutebrowser/mainwindow/tabwidget.py
tests/unit/mainwindow/test_tabwidget.py

This fixes two bugs in #3692, where the minimum size for pinned tabs changed the size of vertical tabbars, and where unshrunk tabs were still behaving like pinned tabs (having a minimum size of their contents).
```
<s4ro> [14:55:21] Hello, in latest git (b67a03115) the tab width
configuration seems to be broken
<The-Compiler> [14:56:26] nonamethanks: ctrl-c copies, ctrl-enter
(with :open -t) opens multiple links
<The-Compiler> [14:56:33] s4ro: how so? (also cc jgkamat)
<s4ro> [14:57:22] The-Compiler: I have vertical tabs and now it always
displays the host name no matter the which is the width set
<nonamethanks> [14:58:01] well crap, i had no idea. Thanks! That's
pretty much exactly what i needed lol
<s4ro> [14:58:04] The-Compiler: removing {host} from tab name restrict
automatically the …
```

Fix minimum size for vertical and shrunk tabs

---

misc/qutebrowser.spec

Having `upx=True` will compress the files with upx if it finds it in the `path` (not good!).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3767)

Pyinstaller: don't use upx

---

qutebrowser/misc/keyhintwidget.py
tests/unit/misc/test_keyhints.py

The keyhint popup stops showing suffixes once you press a special character.
For ex:
```
:bind <Ctrl-C><Ctrl-C> message-info CcCc
:bind <Ctrl-C><Ctrl-X> message-info CcCx
```
Pressing `<Ctrl+c>` displays:
```
<Ctrl+c> message-info CcCc
<Ctrl+c> message-info CcCx
```
It's a trivial fix so just sending a PR instead of opening an issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3769)

Fix keyhints for special characters

---

qutebrowser/mainwindow/tabwidget.py

Switch tooltips to always display page titles rather than the contents of the tab's text from `title_format`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3751)

Always display plain titles in tab tooltips

---

qutebrowser/browser/browsertab.py
qutebrowser/browser/commands.py
qutebrowser/config/configdata.yml
qutebrowser/config/configfiles.py
qutebrowser/mainwindow/tabbedbrowser.py
qutebrowser/mainwindow/tabwidget.py
tests/helpers/stubs.py
tests/unit/config/test_configfiles.py

Closes #3440 
Options modelled after ``tabs.show``: ``always``, ``never`` and ``pinned``.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3680)

Add option to only show favicons for pinned tabs

---

qutebrowser/config/configdata.yml

This PR simply changes the default block list to the singular combined blocklist found at https://github.com/StevenBlack/hosts
As is, the blocklist parsing visibly chokes on one particular line which features more than one host on the line. This will be solved by a line parsing change in a following PR.
closes #3739 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3763)

Change default blocklist to StevenBlack combined

---

qutebrowser/browser/adblock.py
tests/unit/browser/test_adblock.py

This PR consists of two main changes.
Firstly, WHITELISTED is removed as a hardcoded variable, and replaced in-place with a simpler pair of rules:
1) Don't let a hosts list blacklist "dotless" hosts like localhost.
2) Don't let a hosts list blacklist "*.localdomain" hosts.
Secondly, with the recent change to StevenBlack's combined blocklist, one line with multiple hosts on causes a visible error. This parses multiple hosts on a line, and adds a test for the new behaviour.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3765)

Change host file parsing

---

qutebrowser/browser/greasemonkey.py
qutebrowser/javascript/greasemonkey_wrapper.js

This is a fairly naiive attempt to fix #3787.
instead of escaping js strings in jinja, I'm just escaping them with `javascript.string_escape`. 
Let me know if something seems off or if this seems bad for security reasons (?)
I verified this allows greasemonkey scripts (the ones that I tested at least) to run fine on jinja 2.8 from debian stable.
[cc: @toofar]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3788)

Escape strings with string_escape rather than tojson

---

doc/install.asciidoc

Based on issue #3799 
A minor documentation fix that just makes the launch command when installing under those environments easier to find.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3820)
[edit by @jgkamat to link issues: Closes #3799]

Added surrounding gray box to launch command for Ubuntu + Tox

---

qutebrowser/javascript/greasemonkey_wrapper.js

nemanjan00 reported this script not having any effect https://gist.github.com/nemanjan00/01537ec65cd672d1f125170c7807f400/raw/da850e49cc28bc9c94e1a3fb564939eaa2e0aa77/duckduckgo-deepdark.user.js
It turns out that the previous implementation of GM_addStyle was relying
on `document.onreadystatechange` when the script ran early enough that
there was no `head` element. That event wasn't getting fired for the
main frame of duckduckgo.com for whatever reason. Maybe using
`DOMContentLoaded` or something would have worked but I just copied the
fallback in the above linked script which seems to work just fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3792)

Greasemonkey: fix early GM_addStyle with fast sites.

---

qutebrowser/completion/models/miscmodels.py
tests/unit/completion/test_models.py

Closes #3800.
We were counting on `skip_win_id` being truthy when skipping window id's, and `0` seems to be considered falsy in python :(
I don't think we need tests for this, it seems like too much of an edge case. If you think they will help, I'll add them though.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3802)

Fix win_id 0 always being included in :tab-take completion

---

qutebrowser/browser/greasemonkey.py

Greasemonkey scripts are supposed to default to running on all pages.
@jgkamat and @nemanjan00 reported some script not running on all pages
unless they either removed (or broke) the metadata block or added an
include directive. Indeed I had a logic error when it only defaulted to
being included on all pages when no metadata block at all was included.
Whoops.
This bug applies to webengine 5.7.1 and webkit backends.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3803)

Greasemonkey: fix default include value

---

qutebrowser/browser/qtnetworkdownloads.py

After discovering that #3808 happened when a `:download` prompt was cancelled, I realized that the timer calling that method was never stopped in a cancel. The timer appears to still be active even at the end of the `cancel` method in downloads.py.
This fixes that.
Hopefully, this will solve #3808 (but I can't test, because I can't reproduce the error). Also see #3809 for an alternative solution.
```
09:43:29 DEBUG    downloads  downloads:cancel:538 cancelled
09:43:29 DEBUG    downloads  downloads:delete:557 Not deleting None
09:43:29 DEBUG    modes      modeman:leave:292 Ignoring leave request for KeyMode.prompt (reason left in other window) as we're in mode KeyMode.normal
09:43:29 DEBUG    modes      tabbedbrowser:on_mode_left:636 Left status-input mode, focusing …
```

Stop read timer when download is cancelled

---

qutebrowser/misc/autoupdate.py
qutebrowser/misc/httpclient.py
tests/unit/misc/test_autoupdate.py

Closes #3875
The autoupdator, which uses `qutebrowser.misc.httpclient`, has been failing recently because the URL that it hits to check version information is now serving a 301 moved permanently. By default QNetworkRequest doesn't follow redirects so it was getting back a (non-json, despite the request) body pointing to the new location, instead of version information. This PR fixes that by changing HTTPClient to use a QNetworkRequest subclass which follows redirects by default.
It lookes like HTTPClient is currently only used in autoupdate.py, version.py, and crashdialog.py so I don't expect any breakage.
5.6-5.8 Only had a boolean setting available which allows redirects, but not from the https scheme to http, 5.9 introduces a more nuanced setting. I have tested locally on 5.7.1 and …

Make HTTPClient follow redirects by default.

---

misc/userscripts/qute-pass

This was reported to me by someone via e-mail, this should hopefully take care of that issue. Maybe someone could chime in and tell me if I'm overlooking something.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3858)

qute-pass: Escape backslashes in username and password

---

misc/userscripts/qute-keepass

This is a basic userscript to fill passwords from keepass. It follows some of the same structure as `qute-pass`, but it is mostly rewritten (keeping only a few functions) so it dosen't make sense to combine both into one userscript, as it would get very messy.
Some abnormalities.
- Unlike `pass`, which queries for passwords through pinentry, keepass has no such mechanism, so I must query for the password myself. I used `PyQt5` to do this.
- I decided to keep it very simple, searching for any url matching `.*(host).*`. I think this is fairly reasonable, and works for me.
- I'm using `insert-text` over `fake-key`, as `fake-key` does interpretation of the input. For example, one of my passwords broke because it contained `<x>`. `:insert-text "<x>` works as expected, and should reduce the …

Add a keepass userscript

---

qutebrowser/browser/greasemonkey.py
tests/unit/javascript/test_greasemonkey.py

The greasemonkey `@match` directive is used to match urls against
chromium url patterns (as opposed to `@include` which treats its
argument as a glob expression). I was using fnmatch for both here
because I am lazy and knew someone else was going to implement chromium
url patterns for me eventually. Now it is done and I should switch to
using them instead. The most common failing case that this will fix is
something matching on `*://*.domain.com/*` because it wouldn't match
the url with no subdomain.
This codepath is only used on webengine 5.7.1 and webkit backends.
~NOTE: This PR conflicts with #3803 I just need to change that line to have `and not script.matches`. Probably should have put that commit at the start of this PR but it was a spur of the moment thing.~
---
This change …

Greasemonkey: use UrlPatterns for match directives

---

qutebrowser/browser/commands.py
qutebrowser/mainwindow/statusbar/command.py
tests/end2end/data/search.html
tests/end2end/features/search.feature

Previously, slash searching for things like `-m qutebrowser` would result in an error complaining about "unrecognized argument: qutebrowser".
This PR tries to fix this. Instead of taking a single string, I take in a varargs (as `["--", "-m", "qutebrowser"]` is a valid input).
Let me know if anything seems wrong.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3796)

Fix searching with leading arguments and ';;'

---

doc/qutebrowser.1.asciidoc
qutebrowser/qutebrowser.py

As discussed in IRC:
Assigns -B for basedir, -T for temp-basedir.
Assigns -d for debug, -D for debug-flags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3900)

Short options for basedir, temp-basedir, debug, and debug-flags

---

qutebrowser/browser/history.py
qutebrowser/browser/webengine/webenginetab.py

This creates a new slot that is emitted when clearing history, and connects the `clearAllVisitedLinks` function to that slot. I'm not sure if this is the best way to implement this still, so feedback would be appreciated!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3899)

Clear visited links when running :history-clear or Ctrl-d on webengine

---

qutebrowser/commands/command.py
qutebrowser/completion/completer.py
qutebrowser/completion/models/configmodel.py
tests/unit/completion/test_completer.py
tests/unit/completion/test_models.py

Offer successive completion for varargs.
Right now, this applies to `config-cycle`. Instead of stopping after the first value is entered, it will repeatedly suggest more values.
This should also support completing successive tags for the future `bookmark-tag` and `bookmark-load` commands for #882.
I also think there was some other feature that was blocked by the completion not regenerating as args change, but I can't find the conversation any more.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3790)

Vararg completion

---

qutebrowser/browser/hints.py
qutebrowser/config/configdata.yml
tests/end2end/features/hints.feature

This PR adds a `--first` flag to `:hint`, which just clicks the first element hinted.
I usually try to avoid taking easy issues, but this issue has been sitting for several years and has a lot of activity.
I'm not entirely sure if we should bind this to`gi` by default, because I think the intuitive (from vim) behavior of that is a bit different from what `--first` provides. Something like `gi` (focus last input) is going to come in #3433 automatically when entering insert mode normally though, so the binding is free. If you think `:hint inputs --first` should bind to `gi`, let me know and I'll add it.
If anyone is considering using this, you might want to consider setting `hints.auto_follow.always` and just binding to `:hint links`, as that gives you hints only when there's more than one …

Add --first flag to :hint

---

doc/help/configuring.asciidoc

I made a collection of [base16](https://github.com/chriskempson/base16)-color-schemes for qutebrowser and would like to share it. They can be found in [base16-qutebrowser](https://github.com/theova/base16-qutebrowser).
I'm not sure, if this is the right way, so I'm sorry if it isn't.
Thanks for your great work!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3963)

Add note about base16-qutebrowser

---

qutebrowser/config/configdata.yml
qutebrowser/misc/crashdialog.py

I've accidentally closed quite a few `:report`s (which is really bad when a crash happened), so I decided to unbind `<escape>` for `_CrashDialog`. By default `QDialog` calls [reject when escape is pressed](https://doc.qt.io/qt-5/qdialog.html#escape-key), and all this does is filter out the `<escape>` key.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3944)

Prevent closing :report dialog when pressing <escape>

---

misc/userscripts/qute-lastpass

Hi, 
I started using qutebrowser a week ago and saw this wasn't available yet (#3909). This script is mostly existing work from the qute-pass implementation by @cryzed with some few changes for the LastPass CLI differences. 
Here's an [example of it being used](https://i.imgur.com/zA61NrF.gifv) with a lower-quality gif version below:
Just some notes: 
- `lpass show` allows for a regex search on the _name of the LastPass entry_ and can return all matching entries in json so the flow is quite straightforward.
- When there are multiple entries, each entry is formatted as LastPass ID, name, url, and username for lack of a better idea
- As far as I can tell LastPass CLI doesn't have any way to search against an entry's url which makes more sense than searching an entry's name, which can be …

LastPass password fill implementation based off qute-pass code

---

pytest.ini
qutebrowser/browser/greasemonkey.py
qutebrowser/javascript/greasemonkey_wrapper.js
tests/conftest.py
tests/helpers/fixtures.py
tests/unit/javascript/test_greasemonkey.py
tests/unit/javascript/test_js_execution.py

Someone reported that OneeChan wasn't working with our greasemonkey implementation, this highlighted an issue with how we were isolating the different scripts, at least compared to other more mature implementations. I tested with Tampermonkey and saw what kind of environment it provided:
1. `window` looks the same as the one the page sees, with any modifications made by the page
2. the global scope looks the same as the page one before the page made any modifications to it, so before javascript started running I suppose
3. saving something to an attribute of `window` make it accessible via the global scope (that is, just referring to it directly)
I tried looking at the TamperMonkey source to see how they did it but I couldn't figure it out. Possibly they just use the environment presented …

Fix greasemonkey window scoping issues

---

qutebrowser/browser/hints.py
qutebrowser/utils/utils.py
tests/end2end/features/conftest.py
tests/end2end/features/hints.feature
tests/unit/utils/test_utils.py

Implements #3824 
I took care of clearing clipboard on first yank by adding `num` to `HintContext`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3825)

Support rapid hinting mode in yanking

---

qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webkit/webkittab.py
qutebrowser/javascript/webelem.js
tests/end2end/features/caret.feature

For qtwebkit, I couldn't find a way to do this without js, so I'm only supporting it there if js is enabled.
Closes #3935
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3947)

Add support for following tab selected elements to :follow-selected

---

doc/help/commands.asciidoc
doc/help/settings.asciidoc
qutebrowser/browser/browsertab.py
qutebrowser/browser/commands.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webkit/webkittab.py
qutebrowser/config/configdata.yml
qutebrowser/mainwindow/tabbedbrowser.py
qutebrowser/mainwindow/tabwidget.py

Closes #2331 
Muting was added in 5.7 so we shouldn't see version issues.
Pretty simple, but I'm not sure if I structured the API in a good way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3908)

Add support for muting tabs

---

doc/contributing.asciidoc
qutebrowser/qutebrowser.py
qutebrowser/utils/log.py
tests/unit/utils/test_log.py

Sometimes I want to see all the logs _except_ for the sql stuff and "marked cookies as dirty". with this you should be able to pass `--logfilter \!sql,save`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3973)

Allow negating categories in --logfilter

---

qutebrowser/browser/browsertab.py
qutebrowser/browser/commands.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webkit/webkittab.py

The --pygment argument allows to use the pygment version of view-source
over the qtwebengine internal one.
This version is slightly different in what's processed before the site
is generated, so some javascript created texts can be available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3654)

Add --pygment argument to view-source

---

qutebrowser/javascript/caret.js

This changes some of the style of the caret:
Use inherit rather than set colours so whatever is in the parent element is used.
min-width of 0.6em uses roughtly the whole character width, and it resizes in proportion with zoom and/or min-font-size. To use a vertical line it could be changed to 0.2em perhaps (untested).
mix-blend-mode inverts the text colour.
blink helps to make it stand out more
background could be background-color. Not sure yet what difference it makes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3940)
*edit by @The-Compiler to link issues: Fixes #3936*

Change caret style

---

scripts/dev/build_release.py

Currently the python executables paths are hardcoded and are different than the default ones the installer uses on a fresh setup. This patch attempts to get the values from the Windows registry and falls back to the previous values if the key doesn't exist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/3991)

build_release.py: Get python path from registry on Windows

---

qutebrowser/browser/greasemonkey.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webengine/webview.py

Allows putting greasemonkey compatible scripts in isolated JS worlds. As requested in #3238 and by @slackhead. I haven't added any tests because I think they would be bascially the same as `tests/unit/javascript/test_js_execution.py::test_simple_js_webengine()`. Although I suppose I could add tests for all the logic in `qutebrowser/browser/webengine/webenginetab.py::_inject_userscripts()`?
QtWebEngine (via chromium) has the ability to run injected scripts in
isolated "worlds". What is isolated is just the javascript environment
so variables and functions defined by the page and the script won't
clobber each other, or be able to interact (including variables saved to
the global `window` object). The DOM is still accessible from "isolated"
scripts.
This is NOT a security measure. You cannot …

greasemonkey: enable running in isolated js worlds

---

qutebrowser/browser/webengine/webenginetab.py

I think this might work towards https://github.com/qutebrowser/qutebrowser/issues/3896, but I'm not 100% sure yet. See 7162f15 and https://github.com/qutebrowser/qutebrowser/issues/3498 as well.
After 7162f15, I still got crashes, but they were slightly different:
```
00:11:41 DEBUG    config     webenginetab:_on_load_finished:1214 Loading https://github.com/ again because of config change
00:11:41 DEBUG    modes      modeman:_handle_keypress:172 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
00:11:41 DEBUG    keyboard   basekeyparser:_debug_log:91 Got key: 0x58 / modifiers: 0x0 / text: 'x' / dry_run True
00:11:41 DEBUG    modes      modeman:_handle_keypress:199 match: 2, forward_unbound_keys: auto, passthrough: False, is_non_alnum: …
```

Fix crash when tab is closed after a per-domain forced reload

---

qutebrowser/mainwindow/tabwidget.py

This PR is a tiny refactor to make it easier to change the audible strings.
With this PR, you can hackily (READ: NOT SUPPORTED) change the audible strings using:
```python
from qutebrowser.mainwindow import tabwidget
tabwidget.TabWidget.MUTE_STRING = "I AM NOT LOUD: "
tabwidget.TabWidget.AUDIBLE_STRING = "I AM VERY LOUD: "
```
#4088, cc @nemanjan00
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4089)

Move audible strings into class variables

---

misc/userscripts/qute-pass

This allows the aliasing of a domain using symbolic links. For example:
```
user@host ~ $ pass ls | grep -A 1 steam
├── steamcommunity.com -> steampowered.com
│   └── cryzed
├── steampowered.com
│   └── cryzed
```
Where `steamcommunity.com` is a symbolic link to `steampowered.com`. `pass` supports this by default, but `qute-pass` didn't.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4080)

[qute-pass] Follow symlinks when finding pass candidates

---

qutebrowser/browser/webengine/webenginetab.py

Closes  #4073
Adds the [same check](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/browser/commands.py#L1705) as the one in `:click-element` to `:follow-selected` as well.
I was hoping the `if elem.is_link()` would have solved this, but it dosen't for `qute://` urls due to a workaround (I think).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4090)

Add catch and error handling for errors in follow_selected click

---

qutebrowser/mainwindow/mainwindow.py

Fixes #2603
The call to processEvents fixes an apparent race condition with some window
managers, e.g. i3. QT seems to be thinking, that the window is not marked as
urgent and toggles it twice, so synchronizing before issuing the alert makes QT
behave correctly.
This change should not change the behaviour on other systems only correct the
fault reported in #2603.
This is only tested on Arch with the i3 window manager.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4072)

Process all events before issuing an alert

---

doc/faq.asciidoc

The main reason I didn't use Qutebrowser all the time was that it didn't support JavaScript blocking on a per-domain basis. But now #27 has been resolved, which makes this very easy. I added an entry to the FAQ which explains the basics of how to use it similar to No-Script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4103)

Add No-Script-like JavaScript blocking to FAQ

---

doc/help/commands.asciidoc
qutebrowser/misc/utilcmds.py
tests/end2end/features/utilcmds.feature

This would make it possible to repeatedly run commands like :tab-close and :undo without having to add flags for each and every one of them.
See https://www.reddit.com/r/qutebrowser/comments/96gmlc/using_count_to_literally_repeat_commands/
TODO:
- (X) Core functionality
- (X) Update documentation
- (X) Tests? (Should work, although i'm not that familiar with tox. I suggest taking a look at it.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4126)

Have :repeat be able to use [count]

---

qutebrowser/config/configdata.py
qutebrowser/config/configdata.yml
qutebrowser/utils/urlmatch.py
tests/unit/utils/test_urlmatch.py

https://github.com/qutebrowser/qutebrowser/issues/4006 seems to be working mostly, except a few edge cases. A few of those are tested here. Ideas were taken here:
- https://chromium.googlesource.com/chromium/src.git/+/c008bf657dbc01fadc4ff1ea3df21f9cf237569a%5E%21/
- https://en.wikipedia.org/wiki/IPv6_address
(I fucked up in one of the commit messages, dunno how to change it after the fact)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4118)

Tests for ipv6 support in urlmatch

---

qutebrowser/app.py

When using the QT Wayland backend, setting the desktop file name controls the `app_id` used for the xdg_shell protocol. This is similar to `WM_CLASS` in X11, and can be used to select and configure windows in compositors like `sway`. When the desktop file name is unset, it defaults to the executable name, which in qutebrowser's case is the much less useful `python3`.
I'm not sure if this is actually documented, but it's explained in the comment [here](https://github.com/qt/qtwayland/blob/5.12/src/client/qwaylandwindow.cpp#L147).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4153)

Set desktop file name

---

doc/install.asciidoc

When installing qutebrowser via tox on Ubuntu 18.04, the notes on linking
OpenSSL 1.0 instead of OpenSSL 1.1 to make QtNetwork SSL working are a bit
confusing, due to some path differences between Ubuntu and ArchLinux. The
addition of an item addressing this specific issue should help newcomers.
Ubuntu being widely used, it seems reasonable to add some help for this use case. Plus, some details on the procedure may help users of other distributions get their head around the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4156)

Add instructions to link against OpenSSL 1.0 on Ubuntu

---

qutebrowser/completion/models/miscmodels.py
tests/unit/completion/test_models.py

Don't alphabetically sort tab completion.
`ListCategory` was changed to sort completions (on the first column) by default in #3237, most callers that didn't want to be sorted were addressed but the tab completion missed out. This change address that and adds a test to ensure the completion stays in insertion order.
The test tests the case of where you have 11 tabs and if the model was sorted the tabs with index 10 and 11 would be sorted before the one with index 2.
The `random.choices` bit for the tab url and title is to also make sure the model isn't being sorted on those columns, whithout haveng to write and all ten lines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qute …

Sort tab completion properly with more than 9 tabs.

---

doc/help/commands.asciidoc
qutebrowser/config/configcommands.py
tests/unit/config/test_configcommands.py

This change brings Qutebrowser closer to Vim's behavior of `:set foo?` *and* `:set foo` displaying the current value of `foo`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4178)

Display value when calling :set without a value

---

qutebrowser/config/config.py
qutebrowser/config/configcache.py
qutebrowser/config/configinit.py
qutebrowser/mainwindow/tabbedbrowser.py
qutebrowser/mainwindow/tabwidget.py
scripts/dev/check_coverage.py
tests/helpers/fixtures.py
tests/unit/config/test_configcache.py

This addresses most of the problems in #4069, and allows using ~100 tabs (switching between them, resizing, etc) without much lag. With this PR, the next biggest bottleneck is `pinned_statistics` which should be resolved in #4070
I replaced values with the configcache based on if I saw them in the profiling I did, and if their usage was supported by the config cache. The actual implementation is very simple, which I'm pretty happy about.
Edit: I figured out the test issues :) 
Let's see how the benchmarks are impacted on CI :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4185)

Tab config cache

---

misc/userscripts/qute-pass

when using the 'username-taget secret' option, the supplied
regex 'username-pattern' will only scan the first line of the
secret file.
you could specify a username-pattern with '\n', but this will
break if the position of the username is not consistent.
this change will implement re.search and the re.MULTILINE
option to search every line in a secrect file.
example:
--secret file
my_secret_password
username: my_username
--secret file
spawn --userscript qute-pass --username-target secret --username-pattern "^username: (.*)"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4207)

add proper multiline support for qute-pass

---

misc/userscripts/README.md

A Qutebrowser user script enabling secure sharing of an URL between qutebrowser instances without need of any centralized service. Documentation is present on the main page:
https://github.com/sim590/qurlshare
The whole purpose of this script is sending an end-to-end encrypted URL from one computer to the other without the need of any centralized service.
My changes are the addition of a `README.md` file under `misc/userscripts/` for listing userscripts and particularly `qurlshare`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4029)

userscripts: README page and qurlshare userscript

---

qutebrowser/config/configdata.yml

I've recently turned off `content.images` by default, and while it's nice, some pages just don't work without the images shown, so I've added these bindings in my config.py, but I figured others may like these as well. The bindings are structured similar to the `tsh`/`tph` family of bindings to toggle JavaScript/plugins, using `i` instead of `s`/`p`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4231)

Add bindings to toggle content.images

---

qutebrowser/mainwindow/tabwidget.py

Sorry for spamming PRs but I think it's easier to merge them when they're bite size :)
After the other optimizations, `paintEvent` is one of the slowest parts. 
This PR [takes the reccomendation of the paintEvent docs](https://doc.qt.io/qt-5/qwidget.html#paintEvent) to only repaint parts that explicitly are requested, and avoids (relatively) expensive calls to drawControl and initStyleOptionTab when possible. This helps a lot when a (unpinned) tab is loading, as the size of the tab dosen't change but the indicator/text of the tab does.
This will probably also help (insane amounts) of vertical tabs too as we were always drawing every tab in that situation, even when we didn't need to, but I haven't profiled that.
---
This change is [<img src="https://reviewable.io/review_button.svg" …

Only repaint tabs when they are needed

---

qutebrowser/mainwindow/tabwidget.py
tests/unit/mainwindow/test_tabwidget.py

Because figuring out if a tab is pinned is done very often, it's important for it to be fairly fast, but it shows up to be a large chunk of the profile. I added a benchmark and decided to use `tab.data` instead of `tabData`, as `tabData` seems to rely on catching exceptions for every tab that's never been pinned, [which can be slow](https://docs.python.org/3/faq/design.html#how-fast-are-exceptions), and because `tabData` seems to be really slow to return its value either way (maybe it's something in pyqt with the return type being converted or something).
Without Patch:
```
Name (time in us)                               Min                    Max                Median          
---------------------------------------------------------------------------------------------------------- …
```

Don't rely on tabData for pinned tabs

---

qutebrowser/browser/commands.py
qutebrowser/browser/webelem.py
qutebrowser/browser/webengine/webengineelem.py
qutebrowser/browser/webkit/webkitelem.py
qutebrowser/javascript/.eslintrc.yaml
qutebrowser/javascript/caret.js
qutebrowser/javascript/webelem.js
qutebrowser/utils/javascript.py
tests/unit/utils/test_javascript.py

Closes #3786
`input` was the most logical change handler to trigger when we change text, as we don't need to provide any additional information to fire it. There are a couple of other good options though (such as `paste`) but they seem less general.
I don't know of any other websites that use this behavior other than gitlab, if someone could come up with a list, I could test them out and change the signal we emit if there are differences.
I'm not sure if it would be worth it to add tests for this (it would be a little bit of extra work to set up a page that checked for handlers firing), let me know if we do want them though.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qute …

Add support for triggering change handlers when using :open-editor

---

doc/contributing.asciidoc
doc/faq.asciidoc
doc/help/commands.asciidoc
doc/help/configuring.asciidoc
doc/help/index.asciidoc
qutebrowser/browser/commands.py

Based on issue #3457, this is a simple PR to fix some relative links when viewing docs on github.
I followed recommendation [here](https://asciidoctor.org/docs/user-manual/#navigating-between-source-files) for how to render correctly on github without affecting the publish HTML versions. 
I have *not* tested that this still works when asciidoctor converts to HTML. I'm not sure how to actually run that conversion, but will give it a shot if there's instruction somewhere. This is my first PR :)
I also fixed a relative link that was pointed to doc/stacktrace instead of stacktrace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4202)

Use outsuffix for relative links in asciidoc files

---

qutebrowser/config/configdata.yml
qutebrowser/mainwindow/tabwidget.py
tests/unit/mainwindow/test_tabwidget.py

Pretty small commit to add a `tabs.max_width` feature, as someone asked for it on IRC.
Might trivially conflict with #4246, but that's not really a problem :P
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4261)

Add tabs.max_width setting

---

qutebrowser/browser/shared.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/config/configdata.yml
qutebrowser/config/configfiles.py

See #4183 
This is my first contribution, so if there's a better way to do this (most likely), please give me feedback and I'll make the changes.
Should there be a config option for this, something like "scrolling.search_unhide" or "search.unhide_scrollbar"?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4186)

(QtWebEngine) Unhide scrollbar on search result

---

qutebrowser/mainwindow/tabwidget.py
tests/unit/mainwindow/test_tabwidget.py

Improves performance dramatically when all titles change at once, such
as when the first tab is removed.
I don't see any flashing going on at all. The `setVisible` call after the update is hot in the profile with the tab sizing methods, which means that (I think) they should be called properly.
After all these patches I'm noticing some sort of periodic hanging when adding/removing large batches of tabs (it feels like gc pauses, but I don't think that's what it is). I think that's always been there though, and I'm just seeing it now because it's fast in-between the pauses.
As discussed in IRC, [these forced calls to tabSizeHint and minimumTabSizeHint](https://code.qt.io/cgit/qt/qtbase.git/tree/src/widgets/widgets/qtabbar.cpp#n476) are what we want to avoid (as it is called for every single …

Turn off visibility of tabs while updating titles

---

doc/faq.asciidoc

For issue https://github.com/qutebrowser/qutebrowser/issues/4273
Hopefully clears up some of the issues with the PATH for MacOS users. Includes some basic info about why and links to the issue above for details and potential workarounds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4274)

FAQ: Add MacOS PATH info to Troubleshooting

---

qutebrowser/browser/commands.py

Resolves #4280 by stripping queries from the current URL before handling it as before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4282)

Fix url available to :navigate (strip query)

---

qutebrowser/mainwindow/tabwidget.py
tests/unit/mainwindow/test_tabwidget.py

Added a test, and works fine in testing.
If we continue to see issues, we might just want to disable this in 1.5.1, but we'll see.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4296)

Fix tabs appearing when updating all tab titles

---

qutebrowser/mainwindow/tabwidget.py

Using ce4ad878aa6a4a487a820a4f70bed29d0da8729f, the tab stress test is bottlenecked by the minTabSizeHint config calls. This is probably because the test is constantly changing the tab titles, and blowing it's cache.
Maybe if we get this method optimized enough we could remove the cache completely :)
Of course, this only helps the worst-case performance, so in practice it's probably not going to impact people too much, but it's pretty safe :)
Before:
```
[33m-------------------------------------------------------- benchmark: 9 tests --------------------------------------------------------
Name (time in ns)                                          Min                           Max                        Median          
---------------------------------------------------------------------- …
```

Cache config accesses in minimumTabSizeHint

---

qutebrowser/browser/downloads.py
qutebrowser/utils/utils.py
tests/helpers/fixtures.py
tests/unit/browser/webkit/test_downloads.py
tests/unit/utils/test_utils.py

As per #3922, downloading files with illegal characters fails on windows at file creation. This change uses `utils.sanitize_filename()` in two places, once where we finalize guessing a filename based on URL or Content-Disposition and once in get_filename_question where we prompt the user for a filename.
Filenames input at the download location prompt are not modified so a user can still input asterisks and such in there if they like.
Maybe this should be platform dependant, I have a slight preference for having the saved filename closer to the URL.
I wasn't sure about all the possible paths into and through the downloading code so I modified all the end2end tests because they seem to have good coverage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

Sanitize download filenames

---

qutebrowser/config/configcommands.py
tests/unit/config/test_configcommands.py

- `:config-remove-list` command to remove items from a list.
- `:config-remove-dict` command to remove items from a dict.
- Test coverage.
Continues #2794
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4324)

New config: More powerful :config- commands: remove

---

qutebrowser/browser/hints.py

Hinting performance increases by about 30~50% on my machine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4342)

Optimize HintLabel.update_text

---

qutebrowser/completion/completiondelegate.py

I did a little profiling of the completion and while scrolling through entries these config accesses are about ~10% of cpu while scrolling down through the completion (holding `tab`)
The rest seems to mostly be in `_get_textdoc` (but not much from the functions it calls), `draw` and `documentLayout` (which are qt builtins).
This is a pretty trivial change though, so I thought I'd just submit it :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4332)

Cache hot config accesses in completion

---

qutebrowser/browser/hints.py
qutebrowser/utils/utils.py
tests/unit/browser/test_hints.py

PR #3329 fixed #3242, however the code is not completely correct.
* First, the computation of `needed`. Because of some numerical error, `math.ceil(math.log(125,5))` is `4` (while it should be `3`) This can be fixed by subtracting a very small number before taking the ceil.
I think this don't have any real consequences anyway, as (with the change below) `short_count == len(elem) and long_count == 0`.
Alternatively, it's possible to loop multiply using only integers, that way there can't be any rounding error; however this approach already worked for all `len(elems)` up to more than a billion.
* `needed > 1`: To handle the special case of `len(elems) == 1` and `min_chars == 1`.
* `// (len(chars) - 1)`: For each `1` short link being added, `len(chars)` long links are removed, therefore …

Fix _hint_scattered

---

qutebrowser/keyinput/modeparsers.py

The old behavior clears the partial keystring multiple times (once for each connection made)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4363)

Fix _partial_timer connection in modeparsers

---

qutebrowser/mainwindow/tabwidget.py

The visibility toggle hack seems to have broken tab dragging, because dragging plays around with the visibility of tabs (I think).
This seems like the easiest way to fix it... I'm also wondering if we should just override isVisible temporarily instead of calling the setVisible method (to avoid problems like this).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4381)

Fix dragging with visibility toggle

---

qutebrowser/browser/hints.py

Before:
```
------------------------------------- benchmark: 2 tests ------------------------------------
Name (time in ms)                       Min                 Max              Median          
---------------------------------------------------------------------------------------------
test_show_benchmark[webkit]        218.9720 (1.0)      243.3722 (1.0)      229.8361 (1.0)    
test_show_benchmark[webengine]     229.7689 (1.05)     245.4788 (1.01)     237.2474 (1.03)   
---------------------------------------------------------------------------------------------
```
After:
```
------------------------------------- benchmark: 2 tests ------------------------------------
Name (time in ms)                       Min                 Max              Median …
```

Cache hot config accesses for hints

---

qutebrowser/keyinput/modeparsers.py

`dry_run_match` is not used in non-dry_run branch since commit ebb373ccad587522f80b2d6f3966dbfc87e8f905, there is no need to evaluate it.
Actually, the performance benefit is negligible, but the code is simpler. Besides, it reduces number of logging lines in debug mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4362)

Simplify logic in HintKeyParser.handle

---

qutebrowser/misc/miscwidgets.py
tests/unit/misc/test_miscwidgets.py

See #4377 for an alternative solution which also adjusts the selection on triple click. If on 5.10+, we might want to consider using that as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4382)

Fix selection clearing when using <shift-home>

---

misc/userscripts/password_fill

Currently, if the gpg file doesn't have a newline at the end, it's not recognized by the userscript. This fixes it using the simplest answer from [here](https://stackoverflow.com/questions/10082204/add-a-newline-only-if-it-doesnt-exist).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4420)

Allow password_fill to work without final newline

---

doc/changelog.asciidoc
qutebrowser/browser/commands.py
tests/end2end/features/navigate.feature

Resolves #4402 after introducing it in with #4282.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4408)

Strip fragment and query only for `:navigate up`

---

qutebrowser/completion/models/histcategory.py
tests/unit/completion/test_histcategory.py

Resolves #4411:
> When opening a webpage, the suggested results will include those whose
> URL ends with the beginning of the string you've typed and whose title
> begins with the rest of the string.
By joining the url and title with a space, we ensure that the last word
of the url and the first word of the title are treated as separate
words.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4412)

Don't complete url and title from same search word.

---

scripts/open_url_in_instance.sh

There are other scripts in scripts/dev/ that can use /bin/sh too, some of them without modifications... but I can't test them right now, so I'm fixing only this script that I use everyday :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4460)

Use POSIX shell instead of bash on scripts/open_url_in_instance.sh

---

qutebrowser/browser/downloadview.py

The native style does not have the windows-specific issues, which are the rationale for setting the style to Fusion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4488)

Use native style for downloads view on macOS

---

qutebrowser/browser/browsertab.py
qutebrowser/browser/commands.py
qutebrowser/components/misccommands.py
qutebrowser/config/configdata.yml
tests/end2end/features/tabs.feature

Implement a new setting, `pinned.tab.frozen` (boolean), which when false
allows a user to navigate to new URLs in a pinned tab (default behavior
is to have `pinned.tab.frozen = true`, in which no navigation is allowed).
closes #4400
Changes to be committed:
modified:   qutebrowser/browser/browsertab.py
Add `navigation_blocked` method to AbstractTab, which returns
true if navigation is allowed on a tab.
modified:   qutebrowser/browser/commands.py
Change `openurl` to use `navigation_blocked` method of a tab to
determine behavior while navigating a pinned tab.
modified:   qutebrowser/components/misccommands.py
Change `home` to use `navigation_blocked` method of a tab to
determine behavior while navigating a pinned tab.
modified:   qutebrowser/config/configdata.yml
Add `pinned.tab.frozen` …

Implement pinned.tab.frozen setting (issue #4400)

---

qutebrowser/config/configcache.py
tests/unit/config/test_configcache.py

Since we are using configcache more and more (and I've started to barely see it in some profiles), I took another look at the control flow and I think we can optimize the most common case to avoid a lookup. I bumped up the iterations in the test case for this, but:
Before:
```
--------------------- benchmark: 1 tests ---------------------
Name (time in ms)                        Min      Max   Median
--------------------------------------------------------------
test_configcache_naive_benchmark     76.9207  78.5182  77.5965
--------------------------------------------------------------
```
After:
```
--------------------- benchmark: 1 tests ---------------------
Name (time in ms)                        Min      Max   Median
-------------------------------------------------------------- …
```

Optimize configcache for critical path

---

qutebrowser/completion/completiondelegate.py

For some reason, populating the text (even if we completely overwrite
it later) before the highlighter is added results in no highlighting.
I think this has something to do with python locking/delayed
re-highlighting.
At some point, it would be nice to file this as a bug, but I can't
seem to make a small c++ example.
See https://codereview.qt-project.org/#/c/244699/4//ALL and
https://bugreports.qt.io/browse/QTBUG-71307 for more information.
(cc: @Morten242, if they want to take a closer look)
Closes #4519
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4524)

Fix match highlighting on qt 5.11.3 and 5.12.1+

---

doc/faq.asciidoc

'What's the difference between insert and passthrough mode?'
to reflect escape->shift+escape keybinding change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4526)

Update qutebrowser.org/doc/faq.html question

---

qutebrowser/browser/webengine/webenginesettings.py
qutebrowser/config/configdata.py
qutebrowser/config/configdata.yml

Red Flag - DnsPrefetch is enabled by default (as that is how it was on qtwebkit), but it is disabled by default in qtwebengine.
See https://github.com/qutebrowser/qutebrowser/issues/3992
I'm not sure how to actually test if this is getting enabled, but it seems to be following the right code-paths to me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4567)

Add setting for DnsPrefetchEnabled

---

qutebrowser/mainwindow/tabwidget.py
tests/unit/mainwindow/test_tabwidget.py

This makes it so pinned tabs will always have an icon, if one isn't provided by the site, it will get:
This was requested in IRC from someone who wanted to remove all paddings and only use icons in their pinned tabs which seems reasonable (since other browsers do this). This setting won't change anything if `tabs.favicons.show` is never.
Does anyone have any strong opinions about this?
This is pretty low priority, so I'm fine with keeping it in the queue until the other more important PRs are dealt with (and that gives time for others to comment too).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4309)

Always show icons for pinned tabs

---

doc/help/configuring.asciidoc

Just installed v1.6 on my windows work notebook and noticed that a config-source looks in the subfolder config/ for the config.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4629)

Fix config path for Windows in doc

---

doc/changelog.asciidoc
qutebrowser/config/configcommands.py
tests/unit/config/test_configcommands.py

```
$ qutebrowser --temp-basedir --debug ':config-dict-add alias test nop'
...
DEBUG    init       app:process_pos_args:287 Startup cmd ':config-dict-add alias test nop'
DEBUG    commands   command:run:535 command called: config-dict-add ['alias', 'test', 'nop']
DEBUG    commands   command:run:550 Calling qutebrowser.config.configcommands.ConfigCommands.config_dict_add(<qutebrowser.config.configcommands.ConfigCommands object at 0x7f0c4cc400b8>, 'alias', 'test', 'nop', False, False)
ERROR    misc       crashsignal:exception_hook:214 Uncaught exception
File "/usr/bin/qutebrowser", line 11, in <module>
load_entry_point('qutebrowser==1.6.0', 'gui_scripts', 'qutebrowser')()
File "/usr/lib/python3.7/site-packages/qutebrowser/qutebrowser.py", line 194, in main …
```

Fix crash in :config-dict-add, :config-dict-remove, :config-list-add and :config-list-remove with invalid option

---

misc/org.qutebrowser.qutebrowser.desktop

I also thought about adding --target window to the new-window exec, but I'd rather make the smallest diff possible (and it seems to open a new window either way for me).
Also, this will need to be cherry picked onto 1.6.1 which has a different name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4624)

Add undefined actions to action list

---

qutebrowser/mainwindow/statusbar/bar.py

This relies on the default background-color of widgets being transparent.
Discussion:
```
[21:56:43] <jgkamat> this is an interesting issue, not sure how we can fix it https://www.reddit.com/r/qutebrowser/comments/axccr0/lefttoright_gradient_as_status_bar_background/
[21:59:21] <The-Compiler> jgkamat: probably by all those widgets having a transparent background, and only the container widget being colored
[21:59:33] <The-Compiler> kinda surprised that isn't already the case
[21:59:41] <jgkamat> yah, that's what I thought we did already
[21:59:53] <jgkamat> otherwise we would need to update the background of all the widgets when mode changes
[21:59:58] <jgkamat> which I'm pretty sure we don't do
[22:00:26] <The-Compiler> not sure looking at _generate_stylesheet() in …
```

Only set background color on StatusBar

---

qutebrowser/misc/ipc.py

I was looking into how to reproduce high memory usage in the python process by some means other
than using the process for a few weeks and ran across this false positive (I don't use an IPC client normally).
The [docs][0] for `nextPendingConnection` say:
> The socket is created as a child of the server, which means that it is automatically deleted when the QLocalServer object is destroyed. It is still a good idea to delete the object explicitly when you are done with it, to avoid wasting memory.
And indeed it does waste memory. You can test it by doing, for example,
for _ in `seq 0 1000`;do open_url_in_instance.sh ":nop";done
For me the %MEM column in top for the qutebrowser python process rose
about .2 each time I ran that loop (so like 16M?).
I don't think we have to worry about use …

Delete disconnected IPC sockets.

---

qutebrowser/config/configdata.yml
qutebrowser/mainwindow/tabwidget.py

I added attributes in `qutebrowser/config/configdata.yml` for pinned tabs.
New attributes are in the form of `colors.tabs.pinned.odd.fg`
I also added '.pinned' to setting when drawing tabs in `paintEvent` in `qutebrowser/mainwindow/tabwidget.py`
This allows for pinned tabs to have their own color separate from main tabs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4654)

Create color attributes for pinned tabs

---

qutebrowser/completion/models/histcategory.py

Testing with: `python3 -m qutebrowser --basedir /tmp/qbtest --debug --logfilter sql` and pasting `i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i qutebrowser.org` with my history.sqlite.
Master:
```
21:44:34 DEBUG    sql        debug:__exit__:265 Running completion query took 0.035386 seconds.
```
(the queries are especially slow while deleting/retyping the `.org` part of the query
Patch:
```
21:46:13 DEBUG    sql        debug:__exit__:265 Running completion query took 0.013893 seconds.
```
(at least for me, deleting and re-typing the 'org' part of the URL becomes bearable)
and, moving the `qutebrower.org` to the front (which is what my next patch will probably be):
Master: `0.016221 seconds`
Patch: `0.004146 seconds`
My best guess for the difference in the …

Use OR instead of concatenation for queries

---

www/qute.css

If the user has customized their background color, the text color will
not stay as the default but the background will, leading to unreadable
text.
Should be pretty harmless either way though :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4515)
*edit by @The-Compiler: fixes #4510*

Default to white background

---

qutebrowser/browser/browsertab.py
qutebrowser/browser/webengine/webenginetab.py

Closes #4619
Not sure if this is the best way to get the current mode (but I would like to avoid objreg). I put the variable in the abstract base class for simplicity, but I could move it to the child if you would like (although I would need to make an init for that).
Not sure if we can / if it's worth adding a test for this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4620)

Ignore caret callbacks when outside of caret mode

---

qutebrowser/browser/hints.py
qutebrowser/mainwindow/mainwindow.py

Before, we applied a custom stylesheet on every hint object, which was
slow. It's much faster to apply it globally and change the objectName
to tweak access.
Also see https://github.com/qutebrowser/qutebrowser/pull/4334.
For me, before:
```
------------------------------------- benchmark: 4 tests -------------------------------------
Name (time in ms)                        Min                 Max              Median          
----------------------------------------------------------------------------------------------
test_match_benchmark[webengine]       3.1533 (1.0)        3.2160 (1.0)        3.1791 (1.0)    
test_match_benchmark[webkit]          3.1607 (1.00)       3.5663 (1.11)       3.1819 (1.00)   
test_show_benchmark[webkit]         144.1625 (45.72)    167.2484 (52.00) …
```

Apply hint stylesheet on main application

---

qutebrowser/config/configtypes.py
tests/unit/config/test_configtypes.py

100% for a hue slot should correspond to 359, not 255.
This bug was introduced deliberately in 66cc5f5 for compatibility with
Qt's faulty behavior.
QTBUG-70897 was fixed, so we should do the same on our end.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4606)

Correctly parse hue values from config.

---

qutebrowser/app.py
qutebrowser/browser/downloads.py
tests/end2end/features/downloads.feature

If there is a change in the configuration download location, this new location is used instead of the last used directory. Fixes issue #4674
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4675)

Clear last_used_directory when download.location.directory changes

---

tests/end2end/features/downloads.feature
tests/end2end/features/history.feature
tests/unit/browser/test_caret.py

Fixes a couple of test failures in https://github.com/qutebrowser/qutebrowser/issues/4592
These fixes are independant and can be merged separately.
It seems more stuff is being URL decoded in the content disposition header now. We still don't save downloads to ../whatever though so only changes to tests required.
There have been more changes to the signals that are fired on page load. In this case pages with invalid URLs don't get urlChanged signals. I'm pretty sure the test in question was only using the title as a proxy for watching for a page load anyway. The tests around actually checking the URL doesn't end up in history are still passing.
This one isn't failing for me. (Although on appveyor it says at one point it is looking for `http://localhost:1058/data/hello\\.txt/?` in the …

Fix some 5.13 test failures

---

.pylintrc

I don't really think that list comprehensions are any clearer than `map` or a simple for loop (I would say list comprehensions are much more confusing than all the alternatives). The worst example is:
`[str(x) for x in [1,2,3]]`
"run 'str' on a temp variable for elements in [1,2,3]"
`map(str, [1,2,3])`
"map 'str' over [1,2,3]"
I couldn't find a way to disable this only for map, but I think filter is clearer than list comprehensions as well:
`[x for x in [True, False, True] if x]`
"collect a temp variable for elements in [t,f,t] if it's truthy"
`filter(None, [True, False, True])`
"Filter keeping truthy elements in [t,f,t]"
While more general examples are more disputable, I would still say this holds for most other cases:
`[x.atime for x in web_history_items]`
"get the atime attr on a temp …

Disable bad-builtin pylint rule

---

misc/userscripts/qute-pass

I use `qute-pass` to fill in login prompts with qutebrowser. It works really well, however with some sites it's not always clear what domain name is being searched for, and so what to name my `pass` entries.
This PR makes a small change to `qute-pass` to add the list of domains tried to help the user name their pass entries correctly. Feedback welcome, of course. The change only affects the "no matching sites found" error (see below).
Original message:
> No pass candidates for URL 'https://www.access.service.gov.uk/login/signin/creds' found!
New message:
> No pass candidates for URL 'https://www.access.service.gov.uk/login/signin/creds' found! (I tried ['www.access.service.gov.uk', 'service.gov.uk'])
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

make qute-pass more informative when no matching pass entry is found

---

qutebrowser/misc/crashdialog.py
qutebrowser/utils/log.py

Logging is rather expensive in python, and it's quite hard to just tweak the ones that are the worst ones (as it seems to me like there's a very long tail on these).
This pr disables logging completely when passing `--loglines=0`, which provides an easy opt-out, and while it's still measurable, it's much less overhead than actually logging .
As a bonus, I also fixed an exception when passing `--loglines=0` in the reporter. If you'd like that in a separate PR, I can split that commit off though.
http://bugs.python.org/issue30962 is interesting as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4719)

Disable logging completely on --loglines=0

---

qutebrowser/browser/history.py
tests/unit/browser/test_history.py

I'm finding that on newer versions of qt, I'm getting many duplicate entries in my history list, which is causing my history file to balloon. On a computer that I started using about ~9 months ago, my history file is ~250mb. This is due to a combination of:
1. https://github.com/qutebrowser/qutebrowser/issues/3596
2. We save history blindly every time.
This PR is a naiive solution (to be more similar to chrome's history list) which only saves into history if the last URL wasn't the exact same. At the very least, this avoids double saves on every url (which I'm getting at the moment). The main difference is that chrome updates the access time to be the newer access, while this dosen't. I think there's more value in the older time personally, and I'd rather keep things simple, so I'm trying …

Ignore duplicate consecutive history entries from the same url

---

qutebrowser/config/configtypes.py
qutebrowser/misc/utilcmds.py
tests/unit/config/test_config.py

Currently, this is the most expensive part of string validation, especially on longer strings. Unfortunately, this method is called quite frequently (eg: user agent), during intercept request, and needs to be cheap.
The 'proper' fix for this would be to subclass String (and all other immutable types), add a flag to set when fully validated, and use that flag instead. Ideally, we could do this for dicts too, so we wouldn't need to do the traversal which is extremely costly, and gets even worse if people have bound a lot of keys.
If you'd like, I could try to solve this a different way. This shouldn't take up much more memory because these strings are sitting in the config system anyway, but I really don't like sticking caches on everything instead of the proper fix.
I also made a profile …

Add basic_str_validation cache

---

misc/userscripts/format_json

It doesn't work without the ".html", maybe because of changes in Chromium/Qt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4735)

Add ".html" suffix to mktemp in userscript "format_json"

---

misc/userscripts/qute-pass

The current script does not respect the PASSWORD_STORE_DIR environmental variable used by pass.  This pull request fixes that, but retains the scripts -p argument for use with alternative / multiple password stores.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4739)

support PASSWORD_STORE_DIR environmental variable

---

qutebrowser/config/configfiles.py

I missed the coverage check for a branch on #4733. Since I'm never expecting this value to not be a string, I just made it into an assert (even though I'd like to not crash in this case). Do you think this is the cleanest solution?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4737)

Fix missing branch coverage in migrate_string_value

---

qutebrowser/misc/keyhintwidget.py

By default, timers are not single-shot, which means they will keep
firing every `interval` seconds after being started. This is unnecessary
for the keyhint timer, and causes it to eat ~100% CPU with
keyhint.delay=0.
Fixes #4742.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4743)

Prevent keyhint timer from eating all CPU.

---

qutebrowser/config/configfiles.py
tests/unit/config/test_configfiles.py

#4737 was unsafe, string values seem to be coerced to null by the config system.
I added some tests to cover this case as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4751)

Fix string migration when type coercion is used

---

tests/end2end/fixtures/quteprocess.py

It appears that this makes a test in https://www.travis-ci.org/qutebrowser/qutebrowser/jobs/526048084 fail.
--------
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4752)

Fix open_url: the "load status success" line must be after the command called line

---

tests/end2end/features/tabs.feature

It seems like that those tests fail for some recent PRs.
Note that `<enter>` is not strictly equivalent to `command-accept`; however if `fake-key` correctly enter text into the status bar then it would be reasonable to assume that the `<enter>` goes to the status bar as well.
~~(I didn't run tests locally)~~ (the relevant tests seems to pass on AppVeyor, but some other tests break. I think they are unrelated)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4750)

Fix some flaky tests by using <enter> in fake-key -g instead of command-accept

---

qutebrowser/browser/hints.py
qutebrowser/browser/webelem.py
qutebrowser/browser/webengine/webengineelem.py
qutebrowser/browser/webkit/webkitelem.py
qutebrowser/javascript/webelem.js
tests/end2end/features/hints.feature

Add a hint target to delete the selected element. This can be useful for doing ad-hoc deletions of elements, although I don't think the currently defined targets make it fully useful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4755)

Add delete target for hints

---

qutebrowser/browser/hints.py
tests/end2end/features/hints.feature
tests/unit/browser/test_hints.py

Reopen this because accidentally closed #4763.
Currently tabbed_browser and tab are not check for None because
> I think at this time, the tab should not be closed (because otherwise find_css would raise an error), so tabbed_browser cannot be None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4764)

Check if the tab is current in HintManager._start_cb

---

qutebrowser/config/configdata.yml
qutebrowser/mainwindow/tabbedbrowser.py
tests/end2end/features/hints.feature

Even with #4723, #3596 causes hints to be cleared when page load is finished. Because of this, hints are cleared if hinting starts during page load. This adds a setting to tweak that.
I can't find any reason to make this per-domain so I didn't to minimize the increase in page load time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4741)

Add setting to avoid cancelling hints on load

---

qutebrowser/mainwindow/tabwidget.py

I was profiling large numbers of tabs again and I found that getting the style for the icon width is pretty slow for some reason. These profiles are cloning up to 200 tabs and waiting until idle.
```
Total time: 5.74861 s
File: /home/jay/Code/qutebrowser/qutebrowser/mainwindow/tabwidget.py
Function: minimumTabSizeHint at line 555
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
555                                               @profile
556                                               def minimumTabSizeHint(self, index: int, ellipsis: bool = True) -> QSize:
567    256015     315532.0      1.2      5.5          icon = self.tabIcon(index)
568    256015    1894999.0      7.4     33.0          style = self.style() …
```

Add cache for icon padding on tabbar

---

doc/help/commands.asciidoc
qutebrowser/browser/hints.py

I messed up and only inserted the docs in the HintContext docs block, this should be a trivial commit to fix it :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4782)

Add missing docs for delete hint target to :hint

---

qutebrowser/browser/webkit/webview.py
qutebrowser/config/configdata.yml
qutebrowser/mainwindow/tabwidget.py
qutebrowser/utils/jinja.py
qutebrowser/utils/qtutils.py
tests/unit/utils/test_qtutils.py

Per the qt docs, we should not call setPalette on a class that also
uses stylesheets. Since #4637, we set a stylesheet on the application,
so we cannot use setPalette anymore. This commit refactors those calls
to use stylesheets instead.
As far as I can tell, QPalette is OK to use when manually drawing (we
currently use it there).
http://doc.qt.io/archives/qt-4.8/qapplication.html#setPalette
Let me know if there's a QColor->Qss conversion function somewhere, I couldn't find one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4788)

Fix tab and webkit background colors clearing on config change

---

qutebrowser/app.py
qutebrowser/browser/webengine/webenginesettings.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webengine/webview.py
qutebrowser/mainwindow/tabbedbrowser.py
qutebrowser/misc/sessions.py
qutebrowser/utils/qtutils.py
qutebrowser/utils/version.py
tests/unit/browser/webengine/test_webenginesettings.py
tests/unit/utils/test_version.py

Qutebrowser no longer launches in single process mode on Qt5.12.2 ([relevant change](https://codereview.qt-project.org/#/c/248197/)) because we are constructing two `QWebEngineProfile`s. This PR has two main changes:
* don't create a private profile when in single process mode
* handle the private profile possibly being null
The second part is a little more widespread than it should have been because it turns out that the [previous attempt](https://github.com/qutebrowser/qutebrowser/commit/574d7c6a11030) at preventing private windows from being created in single process mode missed a couple of cases, starting fresh with the `content.private_browsing` setting set and loading a session with private windows.
This change will also stop `qutebrowser -T -s qt.args "['single-process']" -s …

Fix single process mode 5.12.2

---

qutebrowser/config/configcache.py

Some people complain that this is micro optimization, but I think we should remove the "weird" restriction on when not to use config cache.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4797)

Improve config cache

---

qutebrowser/browser/webengine/interceptor.py
qutebrowser/extensions/interceptors.py

Not sure if we should/can add tests for this, but a quick manual test with a sample plugin seems to work as expected:
```
from qutebrowser.api import interceptor
from PyQt5.QtCore import QUrl
def f(info: interceptor.Request):
"""Block the given request if necessary."""
url = info.request_url
if (url.host() != 'jgkamat.gitlab.io'):
info.redirect(QUrl("https://jgkamat.gitlab.io"))
interceptor.register(f)
```
Nothing too complicated here overall, pretty simple.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4667)

Add support for redirection to interceptor api

---

qutebrowser/browser/browsertab.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webkit/webkittab.py
qutebrowser/mainwindow/mainwindow.py
qutebrowser/mainwindow/statusbar/progress.py
qutebrowser/mainwindow/tabbedbrowser.py

This contains the following changes around loadStarted/Finished signals:
- `load_finished` is always emitted when Qt does it, i.e., only on full page loads - mostly reverts #3427 and fixes #4535
- The load status (used to color the URL) is rewired to use the workaround, so that #3110 doesn't regress.
- The progress bar always hides on 100% progress instead of loadFinished, so that #3401 doesn't regress.
- Modes are left on loadFinished rather than loadStarted, which fixes #3596
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4723)

Fix load started/finished signals

---

qutebrowser/completion/completiondelegate.py
qutebrowser/config/configdata.yml

Matched text in my completion widget wasn't very readable on the selected line's background. With this option you can color the matched text differently in the selected item.
Also fixes a typo in the description of the `colors.completion.item.selected.border.top` setting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4818)

Add colors.completion.item.selected.match.fg setting

---

tests/helpers/fixtures.py
tests/unit/browser/webkit/test_tabhistory.py

Disable error pages in webpage fixture.
Due to a [change](https://github.com/annulen/webkit/commit/3b3724183bbe) in webkit that introduced a default error page the the webkit/test_tabhistory.py::test_titles broke with the active tab because network access is disable in the webpage fixture, so the error page was rendered.
This change disables the default error pages in the fixture by telling the error notify thing that it doesn't support doing anything with the errors. It also disables the `ChooseMultipleFilesExtension` which should be used with this fixture since we override that for real in qutebrowser
I'm declaring the class inside the method because I don't know how to skip declaring a class in stubs.py with importskip.
Fixes: #4811
--- …

Properly(?) fix tab history title test on WebKit

---

qutebrowser/config/configdata.yml

Remove "not": it is when new_instance_open_target is set to window that new_instance_open_target_window is irrelevant. Not the opposite.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4820)

Fix error comment new_instance_open_target_window in qute://settings/

---

misc/org.qutebrowser.qutebrowser.appdata.xml

The Open Age Ratings Service (OARS) https://hughsie.github.io/oars generates information about the application based on answering some questions. Software front-ends like GNOME Software can then implement filtering based on this information.
This change implements minimal content rating without giving actual content information. Further items that should be added in my opinion are _Online Text-only Messaging_ and _Online Audio and Video Messaging_.
The empty environment is necessary to pass Flathub tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4834)

Add empty Content Rating to appdata

---

doc/help/commands.asciidoc
qutebrowser/browser/commands.py

Add `--enter` to `:fullscreen` to only enter, but never leave fullscreen mode. Without any force :-)
Closes: #4828
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4833)

Fullscreen enter option

---

misc/org.qutebrowser.qutebrowser.appdata.xml

Having up-to-date release information is nice, because it gives store frontends more information to show to the user. https://flathub.org/apps/details/org.qutebrowser.qutebrowser shows the latest version from the current appdata file in the *Updated* section.
It would be nice if we could add such a release string to the appdata file with the same commit that bumps `__version_info__` in `__init__.py`. Maybe a small script could do both at once?

Complete release information in appdata

---

qutebrowser/mainwindow/messageview.py

Previously, these objects would float around (I think forever, due to the parent->child link). Now, these objects are deleted after they are replaced.
I think this should be fairly safe, but I'm not 100% sure yet.

Fix leak of message objects on replace (zoom)

---

qutebrowser/utils/version.py

The platform does not specify a pretty name yet, so that remains *Unknown* for now. I will see if I can get a pretty name into upstream.

Add KDE Platform to known distributions

---

qutebrowser/config/configdata.yml
qutebrowser/mainwindow/tabbedbrowser.py

For me, with this stress test patch (http://paste.debian.net/plain/1084216) (as a super naiive calculation), memory increases about 40mb every tab delete (of a default tab), which means that currently, every tab delete (that's not undone) costs us about 1/3rd of a kb at minimum, since I didn't have any history. Assuming this minimum per tab average, this will cap this usage to 33kb by default.
Similar to #4801
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4814)

Add config to limit size of undo stack

---

qutebrowser/browser/webkit/webkithistory.py
qutebrowser/config/config.py
qutebrowser/config/configdata.py
qutebrowser/config/configtypes.py
qutebrowser/mainwindow/tabwidget.py
qutebrowser/misc/debugcachestats.py
qutebrowser/misc/utilcmds.py
scripts/dev/check_coverage.py

While doing https://github.com/qutebrowser/qutebrowser/pull/4808#discussion_r288973940, I feel that it should be done properly. (although this is just a refactor)
------
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4819)

Register debug-cache-stats with a decorator

---

qutebrowser/browser/hints.py
qutebrowser/config/configdata.yml

The other hint colors are being set in a Qt stylesheet, this one isn't.
I turned it into a QtColor because that returns a QtColor out of the box
and I don't need to construct a new one. `QColor.name()` returns a #RRGGBB
string by default.
No need for escaping since we will be inserting a fixed format now.
This means colors.hints.match.fg will no longer support gradients, as
per the QssColor/QtColor docs. I thing that doesn't make sense for text
color anyway, but I don't know about such things.
That config.cache access could be inside the conditional too. Though I
guess that only helps when they are initially shown or else they
wouldn't be rendered if they didn't have a matching part.
Fixes: #4893

Fix colors.hints.match.fg with rgb() syntax.

---

misc/org.qutebrowser.qutebrowser.appdata.xml

Assuming every tag is a release with the format `vVERSION`:
```sh
git tag \
--sort=-creatordate \
--format='%(refname:short)" date="%(creatordate:short)"/>' \
| sed 's/^v/		<release version="/'
```
Note that this drops `v0.1.0` as there doesn't seem to be a corresponding tag.

Add release information to appdata

---

misc/userscripts/qute-pass

If you execute qute-pass with `username-target=path` and `username-only`, qute-pass still asks you for your password even though it only needs to read the username from the filename. This PR checks for that particular combination of arguments and only executes pass if needed.

Don't execute pass if it's not needed

---

qutebrowser/config/config.py
qutebrowser/utils/version.py
tests/unit/utils/test_version.py

after the "paths" section in :version there is a line indicating when the autoconfig.yml is loaded
this is related to #3504 and #4941

add indicator if autoconfig.yml is loaded to :version

---

misc/userscripts/qute-pass

Currently, qute-pass can only be used if the domain is either a public
domain (which means that its suffix needs to be included in the Public
Suffix List [PSL]), or if an IPv4 address is used.
Some uses might want to use qute-pass to login into the web interface of
their router, printer, NAS or other network-enabled device that is only
accessible from the local network. However, currently users to need
to remember or bookmark the IPv4 addresses of these devices.
If a local DNS server is used to assign domains like "mydevice.local" to
these devices, qute-pass won't work because all potential targets are
empty:
>>> tldextract.extract('https://mydevice.local')
ExtractResult(subdomain='mydevice', domain='local', suffix='')
>>> tldextract.extract('https://mydevice.local').fqdn
''
>>> …

qute-pass: Add support for private domains (e.g. "myrouter.local")

---

qutebrowser/components/adblock.py
tests/unit/components/test_adblock.py

This is a fix for https://github.com/qutebrowser/qutebrowser/issues/4473. I was able to:
* Change `_read_hosts_file` to be more like `_parse_line`
* Refactor `_parse_line` to return a list of found hosts (and update `_merge_file`) as well as implement `find` instead of a `try/except ValueError`
I was unable to reproduce https://github.com/qutebrowser/qutebrowser/issues/4325. I believe my changes would fix this problem anyway (using `line.strip()` on line 150 should remove extra spaces and produce an empty list) but I was unable to test if so.
I tested this own my own by adding `127.0.0.1 www.youtube.com` to `~/.config/qutebrowser/blocked-hosts`. Before, YouTube would not be blocked by this addition. Afterwards, YouTube is properly blocked.
I did not add any test cases for my changes. I'm …

Fixed blocked hosts misinterpretation

---

qutebrowser/config/config.py
qutebrowser/utils/jinja.py
tests/unit/utils/test_jinja.py

Huge performance improvement with `:config-source`.
Note that further improvement is possible by batching all calls at the end of `:config-source`.
-------------
By the way, (with master branch, not this branch) I once got this result
```
$ time qutebrowser ':repeat 3 config-source ;; quit'
Segmentation fault (core dumped)
```
No idea why that happens, but may be related to doing `config-source` before some Qt objects are ready.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4808)

Only update stylesheet when related config option changes

---

qutebrowser/browser/shared.py

This allows qutebrowser to find netrc entries for things like "localhost:7777" instead of just looking for "localhost".

Search netrc for {host:port} when port is present in url

---

qutebrowser/completion/completionwidget.py
qutebrowser/completion/models/histcategory.py
tests/unit/completion/test_histcategory.py

It seems like queries that have a lot of hits complete much faster than those that have few or no hits. I think this is because the completion seems to (?) not get all the results, but cache the first x relevant ones.
```
// many, many hits
12:03:01 DEBUG    sql        sql:run:215 query bindings: {':0': '%qute%'}
12:03:01 DEBUG    sql        debug:__exit__:265 Running completion query took 0.000519 seconds.
12:03:01 DEBUG    completion debug:__exit__:265 Set pattern qute took 0.003181 seconds.
// many hits
12:03:23 DEBUG    sql        sql:run:215 query bindings: {':0': '%qutebrowser.org%'}
12:03:23 DEBUG    sql        debug:__exit__:265 Running completion query took 0.001016 seconds.
12:03:23 DEBUG    completion debug:__exit__:265 Set pattern qutebrowser.org took 0.020116 seconds.
// no …
```

Avoid un-needed queries in the completion

---

qutebrowser/keyinput/keyutils.py
tests/unit/keyinput/test_keyutils.py

I'm not sure if this is the best way to fix this, it should perhaps be checked somewhere else, but this is the basic idea. And this does allow me to type emoji into qutebrowser. This is my attempt at fixing #4439.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4492)

Fix crash on key-event-based input of characters in the Supplemental Planes (e.g. emoji 😬)

---

qutebrowser/browser/webengine/spell.py
qutebrowser/browser/webengine/webenginesettings.py
scripts/dev/update_3rdparty.py
scripts/dictcli.py
tests/unit/browser/webengine/test_spell.py
tests/unit/scripts/test_dictcli.py

Before this change, we sometimes assumed that a dictionary filename had a .bdic
suffix, sometimes not, and sometimes we added it by hand.
For some reason (probably some minor API change?) this currently breaks running
dictcli.py.
While the minimal fix in #4986 works, it only does so because we use re.match
(not re.fullmatch) inside spell.py, so the .bdic suffix (which is present
there) is ignored.
This change instead refactors all dict handling so that the suffix is always
included in the filename, and only stripped off in the last moment when passing
it to QtWebEngine.
Closes #4986
Closes #5002

Clean up filename handling in dictcli/spell.py

---

qutebrowser/keyinput/keyutils.py
qutebrowser/keyinput/modeparsers.py
tests/unit/keyinput/test_keyutils.py

The 2 first commits just move codes around, they don't change the behavior. The 3rd commit fixes #4264.
Related: #4504 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/qutebrowser/4691)

Fixes "Pressing shift resets hint keystring"

---

qutebrowser/keyinput/basekeyparser.py
tests/unit/keyinput/test_bindingtrie.py
tests/unit/keyinput/test_keyutils.py

Closes #4721.
Note:
* For operations like `1000j` it reduces the time from about 4.5s to about 3.0s (if `-OO --loglines=0` is used each one is reduced by about 0.5s)
* With PR #4536 the time for `1000j` is reduced about 1.5s - 2s further.
* This implementation is iterative. See /binding-trie branch for a recursive implementation (it looks worse).
* Regarding `1000j`: it only invokes `ShortcutOverride` event; but I think the result doesn't matter anyway because we don't have shortcut keys for arrow keys. I chose that because it's easy to test.
* Here ~~I didn't inherit `MutableMapping` because I'd need to implement some more methods (iter, len)~~ iter, len and delitem raises NotImplementedError, which (currently) the code don't need to use. Note that implementing `len` in constant time …

Implement trie for bindings

---

misc/userscripts/readability-js

The main reason for switching to a new library is that the previously used readability libraries seem largely unmaintained, and hence often rendered a lot distracting elements (see e.g.  the discussion in https://github.com/qutebrowser/qutebrowser/pull/4991). In contrast, Mozilla's readability library will be maintained for the foreseeable future (possibly as long as Firefox is around). Other improvements I observed include slightly more retained textual information and images, as well as the preservation of hyperlinks. The latter feature requires accessing the `QUTE_URL` variable, in contrast to the `QUTE_HTML` variable that was used in the previous script. Apart from this change, this script should be functional equivalent to the older, python based version. 
Possibly interesting …

New readability userscript based on Mozilla's readability library

---

misc/userscripts/README.md

The list of userscripts (`misc/userscripts/README.md`)  is missing an entry on the new readability-js userscript.

Add readability-js to the list of userscripts

---

qutebrowser/browser/browsertab.py
qutebrowser/browser/shared.py
qutebrowser/mainwindow/statusbar/bar.py
qutebrowser/mainwindow/statusbar/url.py
qutebrowser/mainwindow/tabbedbrowser.py

I frequently use a website which triggers https://github.com/qutebrowser/qutebrowser/issues/3596 almost constantly, which is extremely annoying as it causes the webview to lag out a lot (making the site totally unusable).
With this patch, the website is barely usable.
The only questionable bit is the `polish` function (instead of applying the stylesheet). Normally you're supposed to unpolish then polish, but since we are always overriding a single value (the color) dynamically, I think we can get away with just a polish (doing a unpolish/polish is more expensive than setting the stylesheet).
(also, I would really like to reduce the amount of logging here, logging alone was taking up ~30% of the total profile when on this website).
Also see …

Optimize loading hooks

---

misc/userscripts/qute-bitwarden

Hi,
I've made a qute-bitwarden userscript by modifying qute-lastpass. It's mostly the same as qute-lastpass except that the json returned by bitwarden is slightly different and Bitwarden uses a session hash which I store using keyctl (I took inspiration from [bitwarden-rofi](https://github.com/mattydebie/bitwarden-rofi)).
I've also added the parameter `--auto-lock` (as in bitwarden-rofi) which allows you to specify the timeout after which you must re-enter your master password.
Relevant issue here: #5030

Bitwarden password fill based off qute-lastpass

---

doc/contributing.asciidoc
scripts/dev/run_profile.py

Fixed TypeError crash:
```
$ scripts/dev/run_profile.py --profile-tool=none           
File "scripts/dev/run_profile.py", line 102, in <module>
main()
File "scripts/dev/run_profile.py", line 63, in main
profilefile = os.path.join(os.getcwd(), args.profile_file)
File "/usr/lib/python3.7/posixpath.py", line 94, in join
genericpath._check_arg_types('join', a, *p)
File "/usr/lib/python3.7/genericpath.py", line 149, in _check_arg_types
(funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```
Updated and improved the docs.

run_profile: Set default profile file for --profile-tool=none

---

misc/userscripts/readability-js

Most websites work fine without explicitly specifying an UTF-8 encoding, even if they have unicode characters (e.g. the wiki article on [Japanese](https://en.wikipedia.org/wiki/Japanese_language)). However, I encountered [this website](https://www.frontiersin.org/articles/10.3389/fnhum.2013.00443/full), which renders some characters incorrectly when the input is not encoded as UTF-8. The python readability script works fine on the latter website, mainly because it reads `QUTE_HTML` as UTF-8:
```python
with codecs.open(os.environ['QUTE_HTML'], 'r', 'utf-8') as source:
data = source.read()
```
This PR adds the same explicit encoding to the `readability-js` script.

[readability-js] Encode input as UTF-8

---

doc/help/settings.asciidoc
qutebrowser/config/configdata.yml
qutebrowser/mainwindow/tabwidget.py

To minimize changes, we can limit this setting to a restart. That way
we won't need to loop over every tab.
Closes #5042

Add setting to toggle tab tooltips

---

qutebrowser/browser/downloads.py
qutebrowser/browser/pdfjs.py
qutebrowser/browser/qtnetworkdownloads.py
qutebrowser/browser/qutescheme.py
qutebrowser/browser/webengine/webenginedownloads.py
tests/unit/browser/test_pdfjs.py
tests/unit/browser/test_qutescheme.py

Closes #4303. (using the workaround stated there because nobody said anything about it)
note:
* It opens in a new tab.
* Probably won't work for PDFs got with a POST request.
todo:

Pdfjs persistent

---

qutebrowser/config/configutils.py
scripts/dev/run_vulture.py
tests/unit/config/test_configutils.py

Previously, adding a pattern setting was an O(n) operation, which made
large sets of pattern settings impossible.
Instead of storing pattern settings in a list, we can stored them in
an ordered map from pattern -> ScopedValue. This provides relatively
fast deletion and insertion.
With this change, the newly added benchmark of adding the existing
hosts_list measures to 1s, where it was timing out/crashing for me
when limited to 1000 entries before.
Now, the bottleneck is the initialization of UrlPattern objects.
However, if we do anything more clever for faster lookup, we will take
a penalty to init time (which is worth it).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qutebrowser/quteb …

Use ordered dicts to reduce complexity of pattern add

---

qutebrowser/config/configutils.py
qutebrowser/utils/urlmatch.py
qutebrowser/utils/urlutils.py
scripts/dev/run_vulture.py
tests/unit/config/test_configutils.py
tests/unit/utils/test_urlutils.py

Requires #4544. Tentatively closes #4409
Before:
```
------------------------------------------------------ benchmark: 4 tests -----------------------------------------------------
Name (time in ms)                                                         Min                 Max              Median          
-------------------------------------------------------------------------------------------------------------------------------
test_domain_lookup_sparse_benchmark[http://www.qutebrowser.com/]     100.1871 (1.0)      102.9923 (1.00)     101.7632 (1.01)   
test_domain_lookup_sparse_benchmark[http://bop.foo.bar.baz/]         100.6100 (1.00)     106.1524 (1.03)     101.8571 (1.01)   
test_domain_lookup_sparse_benchmark[http://foo.bar.baz/]             100.7740 (1.01)     102.7752 (1.0) …
```

Use a domain mapping to reduce complexity of per-domain lookups

---

doc/contributing.asciidoc

The old `.org` URL would 404 on me when I first tried to open the link. Though later on after finding the right address and having the new `.io` domain cached, the redirect on the old `.org` address worked fine.
Still, I think it's good to update it for future readers.

Update: link for tox in contributing.asciidoc

---

doc/changelog.asciidoc
doc/help/settings.asciidoc
qutebrowser/browser/browsertab.py
qutebrowser/browser/commands.py
qutebrowser/browser/hints.py
qutebrowser/browser/qtnetworkdownloads.py
qutebrowser/browser/webengine/interceptor.py
qutebrowser/browser/webengine/webenginesettings.py
qutebrowser/browser/webkit/webkitsettings.py
qutebrowser/browser/webkit/webkittab.py
qutebrowser/browser/webkit/webpage.py
qutebrowser/commands/userscripts.py
qutebrowser/config/config.py
qutebrowser/config/configdata.yml
qutebrowser/config/configfiles.py
qutebrowser/config/configutils.py
qutebrowser/config/websettings.py
qutebrowser/utils/usertypes.py
qutebrowser/utils/version.py
tests/end2end/features/misc.feature
tests/helpers/fixtures.py
tests/unit/browser/webengine/test_webenginesettings.py
tests/unit/browser/webkit/test_webkitsettings.py
tests/unit/config/test_configfiles.py
tests/unit/config/test_configutils.py
tests/unit/config/test_websettings.py
tests/unit/utils/test_version.py

This PR refactors user-agent handling so we don't directly use the default UA from QtWebKit/QtWebEngine anymore (#513). To do so, the `user_agent` setting now is a template string, getting filled from information we parse from the default UA.
With that change, we can also fix issues like #2800 properly, as we now can get a proper UA without having a QWebEngineProfile/QWebPage handy.
I also added some code so specific `ScopedValue` settings can be hidden from `qute://configdiff`, which fixes #4076. Finally, this allows us to introduce "site specific quirks", i.e. custom user agents for badly behaving websites such as Google, WhatsApp or Slack (#4810 and others).
Since this turned out to be a quite big change, I'd love some feedback. Looking at the commits, for most commits one of you made …

Refactor user agent handling and introduce site-specific quirks

---

qutebrowser/commands/cmdexc.py

While perusing the file `qutebrowser/commands/cmdexc.py`, I noticed a minor grammar mistake in one of the docstrings. Then also reworded 2 others to make their verb tenses more consistent (sorry if this seems a bit nitpicky).

Use (slightly) clearer wording

---

qutebrowser/browser/commands.py
qutebrowser/completion/models/miscmodels.py
tests/end2end/features/tabs.feature
tests/unit/completion/test_models.py

* Window ID (category labels) are removed from completion
This PR is meant to address #5114 
A few points/uncertainties:
* `miscmodels.py` felt like the best place to make the change, since the requested behavior is specific to the `:buffer` command, though I could be wrong
* I'm not at all convinced that this was a good, let alone best, implementation of this behavior
* primarily I got a nagging feeling that it's a tad too verbose; but can't quite trim it down even after thinking about it for quite a while
* being a complete newcomer to qutebrowser (both as a user and a contributor), it's quite likely I missed some consideration related to this change, so please let me know if that's the case
* lastly if tests should be added to cover this change, just say the word

Add new behavior for tabs_are_windows setting

---

doc/faq.asciidoc

I've recently found myself in the situation where I needed to update a CA cert and a client cert because they had expired.
After reading some manpages and fiddling around I managed to do it.
Since I was unable to find any documentation / examples regarding the use of client certificates I went ahead and added a section to the FAQ.

add documentation for client cert usage

---

misc/userscripts/qute-pass

Currently qute-pass works only if PASSWORD_STORE_DIR is not ending by
slash character (on unix).
find_pass_candidates compute pass_path = path[len(password_store_path)+1:]
where +1 is used to count an extra slash.
So if PASSWORD_STORE_DIR ends by slash we count it twice, leading to
failure.
Signed-off-by: Abdel Benamrouche <abdel@unxp.fr>

Fix PASSWORD_STORE_DIR suffix

---

misc/userscripts/qute-pass

The new CLI-switch `--pass-executable` makes qute-pass compatible with the gopass password store (https://github.com/gopasspw/gopass). While gopass itself is mostly compatible with pass, it offers the possibility to mount multiple shared password stores. qute-pass way of just traversing PASSWORD_STORE_DIR won't help in that case.
--
I've tried to keep backwards-compatibility with the old behaviour as much as possible. The method `find_pass_candidates` will now just branch out into two different modes depending on which password executable is used. In the `pass` way, the code stayed the same.
Closes #5142

Add gopass support to qute-pass via a CLI switch

---

qutebrowser/javascript/greasemonkey_wrapper.js
tests/unit/javascript/test_greasemonkey.py

Introduces a shared `window` proxy for Greasemonkey scripts as discussed in #5266. I also edited `greasemonkey_wrapper.js` to use a consistent level of indentation throughout. I added a unit test which passess (at least on my machine). In the browser the test scripts end up executing in a random order, so they only work correctly some of the time. This pull request does not address the execution order of scripts because Qt doesn't currently provide a method to control this. See this [issue](https://codereview.qt-project.org/c/qt/qtwebengine/+/281433).

Greasemonkey shared window proxy

---

qutebrowser/browser/browsertab.py
qutebrowser/browser/commands.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webkit/webkittab.py
qutebrowser/config/configdata.yml
tests/end2end/features/search.feature

Closes #5136.
With QtWebEngine, the API does not support the necessary flags to stop
wrapping, so the implementation via checking which match the search is
currently on is required. (The new functionality is disabled on Qt < 5.14)
It is not possible to display a message with QtWebKit since there is no
feedback from the search function.
This pull request is still WIP, as I have not yet created tests and am not completely certain of the stability of the solution.
And probably more.
I had to change the `findText` call from the `QWebEngineView` object to its `page()`, since only `QWebEnginePage` supports the new API for some reason. (Another good question would be why QWebEngine is lacking QWebKit functionality even though it's supposed to be its successor). The WebEngine solution is …

Add search.wrap configuration option

---

qutebrowser/config/configdata.yml
qutebrowser/config/configtypes.py
qutebrowser/utils/urlutils.py
tests/end2end/features/yankpaste.feature
tests/unit/config/test_configtypes.py
tests/unit/utils/test_urlutils.py

In the search engine url replacement, only quote the search term if the
search engine format explicitly requests this:
- The placeholder {} inserts the plain search term without quotation
like before of #4434. This seems to be the default for other
browsers' search engines and to be supported by most websites. For
example, https://en.wikipedia.org/wiki/AC/DC leads to the wikipedia
article of AC/DC.
- A new placeholder {quoted} inserts the quoted search term. For
example, with
c.url.searchengines['jpc'] = 'https://www.jpc.de/s/{quoted}'
the command "jpc AC/DC" correctly redirects to https://www.jpc.de/s/AC%2FDC
given results for "AC/DC". Here, the placeholder {quoted} is indeed
necessary (as of March 2020), since  https://www.jpc.de/s/AC/DC only
searches for "AC".
This addresses the issue …

Only quote search engine terms if requested

---

doc/help/settings.asciidoc
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/config/configdata.yml
qutebrowser/mainwindow/mainwindow.py
qutebrowser/misc/miscwidgets.py

#5297 This pull request introduces new :set option "content.fullscreen.overlay_timeout", with which can be configured timeout for fullsceen notification. 
It also renames "content.windowed_fullscreen" for "content.fullscreen.window" to keep names united. 
The documentation about these two settings have been updated too.

#5227 Make fullscreen notification overlay timeout configurable 

---

misc/userscripts/qute-bitwarden

Moves the TOTP code to clipboard, which can be then pasted by the user,
much like the Firefox add-on. Uses the pyperclip Python module, which
is cross-platform (currently doesn't support wayland, but there is an
open issue).

Enable TOTP support in Bitwarden userscript

---

doc/help/settings.asciidoc
qutebrowser/config/configdata.yml
qutebrowser/mainwindow/mainwindow.py

This pull request adds the ability to round the corners of hints with the configuration option `hints.radius`. The default value is set to `0px`.
I was not sure if I should make the corner radius an integer or a string that represents the CSS value. I went with the second, but let me know if you like it otherwise and I will fix the PR.
Known issues:
- Rounding stops working (it is no longer applied) with values higher than 14px (with border width 0). Looks like this is due to the small size of the hint widgets, since when I increase the border width, I can also increase the border radius.
- It does not work with CSS values such as `50%`. This could be related to the issue above or it could be a Qt limitation since Qt only implements a subset of CSS. A value of `50%` is supposed to turn …

Add border radius and padding configuration options for hints

---

misc/userscripts/readability-js

A baby change, but one that keeps your tabs nice and organized! Previously, the readability tab would go to the far-right. Now, it opens the tab next to the current page, so that they remain grouped together.

Open readability page next to original tab

---

misc/userscripts/readability-js

I'm not sure whether you like my idea and/or approach, but I sometimes have slight difficulty recognizing what my readability tabs are. I thought a favicon might help me differentiate them from the rest. Moreover, most browser have a symbol that indicates them being in 'readability' mode. 
I've embedded the favicon as a base64 encoded svg. Not sure if you like this approach, but at least this allows the script to remain fairly "standalone".
The icon is just the Mozilla readability icon, but with its color changed to white. (if I understand correctly, their license allows qutebrowser to redistribute it without any further requirements) 
Not sure about the color of the icon, but I went with pure white because it goes okay with the standard qutebrowser color scheme and has a lot of contrast. …

Add a readability favicon

---

qutebrowser/browser/eventfilter.py

Currently while in hint mode, if the user scrolls with the mouse, the hint labels are left on the screen at the original position when the user started hinting at.
This makes it a little hard to follow a hint accurately if you accidentally scroll.
For instance, my touchpad is extremely sensitive and picks up accidental scroll events from time to time when my palm touches the edge. This makes hinting extremely frustrating at times because I have to restart the hint sequence after scrolling back to the position I originally started hinting at.
If this is not the best place to implement this change, let me know.

Don't allow page to be scrolled while hinting

---

qutebrowser/browser/browsertab.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webkit/webkittab.py
qutebrowser/components/caretcommands.py
qutebrowser/config/configdata.yml
qutebrowser/javascript/caret.js
qutebrowser/mainwindow/statusbar/bar.py
qutebrowser/mainwindow/tabbedbrowser.py
tests/unit/browser/test_caret.py

This PR introduces visual mode line for both webengine and webkit backends. It follows the behaviour of visual line mode in Vim, except for commands move-to-next-word, move-to-prev-word and move-to-end-of-word. It is because in browser is not possible to have cursor even under selection, thus the functionality then will be very similar to move-to-next-line and move-to-prev-line.
Please correct me if otherwise.
In this PR also unit tests are implemented, please let me know me, if more tests are needed.

Visual line mode

---

qutebrowser/browser/commands.py

If the tab is actually located into a private window, it will just behave
normally.
This handle the case described in this issue: #4935

Allow to pluck tab into a private window instance

---

qutebrowser/app.py
qutebrowser/config/configdata.yml
qutebrowser/config/configtypes.py
qutebrowser/qutebrowser.py
qutebrowser/utils/log.py
tests/unit/utils/test_log.py

Log levels can now be configured in config.py by setting
loggin.level.console (for stdout/stderr) and logging.level.ram (for
:messages).
This is of interest for users who would like password-manager
integration that uses `fake-key` to send sensitive strings to websites.
The default 'debug' ram logging would store various logs containing the
sensitive data.
Previously the loglevel was only configurable through CLI flags, and
those only affected the console loglevel. We felt a config value would
be nicer than just adding another flag for RAM loglevel, requiring you
to create an alias for qutebrowser and ensure _that_ alias gets used
anywhere qutebrowser might be invoked.
Logging is initialized before the config is loaded, so configuration-set
loglevels have to be loaded in a second, later …

Add loglevel config settings.

---

qutebrowser/app.py
qutebrowser/misc/utilcmds.py

Now `:set logging.level.{ram,console}` will work after qutebrowser has
started. This allows us to derecate debug-set-loglevel.
Logging is initialized too early for `config.change_filter` to work, so I
had to hack it.

Enable configuring loglevel at runtime.

---

qutebrowser/components/adblock.py

By default every blocked request is logged, which seems way too verbose for those who aren't debugging this component

Decrease log verbosity of adblock component

---

qutebrowser/browser/browsertab.py
qutebrowser/browser/commands.py
qutebrowser/browser/inspector.py
qutebrowser/browser/webengine/webengineinspector.py
qutebrowser/browser/webkit/webkitinspector.py

New clean branch/PR based on current master - replacing PR #4290 .
Fixes #1400
It is now possible tell the inspector where to go. For example `:inspector bottom`. Possible values: `right, left, top, bottom, window`.
`:inspector` will open the inspector in the last used position or close it if it is already open.

Inspector inside Tabs - second attempt

---

doc/faq.asciidoc

Just a few small improvements that would have aided my understanding of this feature.
- clarify that `tsh` is a keybinding not a command
- document where the exceptions are written to
- reword language around whitelisting

faq: clarify secion on noscript bindings

---

qutebrowser/config/configdata.yml
qutebrowser/utils/urlutils.py
tests/unit/utils/test_urlutils.py

* when `url.auto_search = 'no-url-scheme'`, URLs
must contain schemes to be considered valid
* implements feature requested in #5038 
-------------------------
I'll add the tests in if the code looks good to you guys.

Add: new mode for Auto Search

---

qutebrowser/mainwindow/mainwindow.py

This is my first time doing a pull request so hopefully I didn't do anything wrong but this is just a few lines that allow the browser window to be transparent. If there is some reason why anyone wouldn't want this feature then it could also be made an option in the config file instead.

Support transparency for tabs / status bar

---

doc/help/settings.asciidoc
qutebrowser/config/configdata.yml
qutebrowser/mainwindow/tabwidget.py

A small and potentially controversial proposal 😄 Currently when you have more than 9 tabs open and you are using vertical tabs, alignment is off by one character and this makes it very unaesthetic 😁  
But if we pad this with a space character, it becomes much more pleasant to look at with up to 99 tabs 😄 
This patch isn't particularly noticeable with horizontal tabs:
What do you think?

Align tab index

---

misc/userscripts/qute-lastpass

This is just @user202729 's fix. I tested it and it works properly. `qute-pass` doesn't have this issue because it is able to use a set as the candidate output seems to be scalar.
Sorry for the delay. I was trying to look into creating a unit test for the qute-lastpass script, but python isn't my native language and I ran into the following blockers below. Any suggestions would be helpful so I can open a PR in the future to fix.
1. `qute-lastpass` having a dash seems to violate import naming policy, using `importlib.import_module` as a workaround is not possible from the lack of a `.py` extension
2. Refactoring out parts to address the above into a separate python file that follows convention seems to violate the current userscripts convention where each script is atomic.
3. Opting for an …

Fix for #5550: qute-lastpass merge-candidate bugfix from @user202729

---

qutebrowser/config/configtypes.py
tests/unit/config/test_configtypes.py

#5583 didn't pan out but in the process I learned that both QtColor and QssColor support #AARRGGBB via QColor, which isn't currently documented.

Document #AARRGGBB for QtColor and QssColor

---

misc/requirements/requirements-tests.txt
misc/requirements/requirements-tests.txt-raw
misc/userscripts/qute-lastpass
tests/unit/misc/userscripts/test_qute_lastpass.py

This PR contains the following:
- implements @user202729's regex suggestion from #5581 
- properly escapes the period in the address to prevent interpretation as regex token
- adds tests for qute-lastpass itself (!!!!)
**For posterity, here's an example test case of the previous `lpass` lookup behavior:**
```
$ lpass show -G '.*github.com.*'
Multiple matches found.
Professional/github.com [id: 2953045716]
github.com2 [id: 4403545512357498789]
githubocomer.com [id: 6176415432651238513]
ragithub.com [id: 5593872512970787522]
```
**Corrected behavior using @user202729's regex:**
```
lpass show -G '\bgithub\.com'
Multiple matches found.
Professional/github.com [id: 2953045716]
github.com2 [id: 4403545512357498789]
```
Note that the `merge-candidates` flag uses several variations of lookup so …

Fix for #5581: Tighten qute-lastpass lookup regex and add tests

---

doc/help/commands.asciidoc
doc/help/settings.asciidoc
qutebrowser/app.py
qutebrowser/browser/commands.py
qutebrowser/completion/models/miscmodels.py
qutebrowser/config/configdata.yml
qutebrowser/mainwindow/mainwindow.py
qutebrowser/mainwindow/tabbedbrowser.py
tests/end2end/features/conftest.py
tests/end2end/features/tabs.feature
tests/helpers/stubs.py

Adds the ability to re-open the last closed windows with shift+u. Closed windows are stored in a global stack so it doesn't matter which window is focused when you run the command.
All of the hard work around managing restored tab order and such is done by the existing tab undo mechanism. We were already making undo entries for the closed tabs when closing a tabbed browser, with this PR we will be saving them somewhere. Where they are saved isn't particularly importand, I chose to save them to the main `Application` because the life-cycle fits. I suspect when we move window/tab access out of objreg there will be a new place to store them.
The other requirement is that they are stored somewhere that the command dispatcher can access/import. We are working around the importloop at the …

Add :undo --window

---

qutebrowser/browser/commands.py
qutebrowser/mainwindow/tabbedbrowser.py
tests/end2end/features/tabs.feature

Probably the main situation in which this is useful is when you close a couple of tabs in quick succession and want to reopen one other than the most recent. Currently you have to either manually find the url in your history and reopen it, or :undo repeatedly until you get the one you want and then reclose the others.
The competing possible implementation of a count for :undo is reopening everything from the end of the stack down to and including [count] instead of skipping through and just reopening [count], but I find the latter more useful. If someone really wants that behavior it would be pretty easy to add with a config option in the future.

Make :undo reopen the [count]th to last closed tab

---

doc/help/commands.asciidoc
qutebrowser/browser/browsertab.py
qutebrowser/browser/commands.py
qutebrowser/browser/webengine/tabhistory.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webkit/webkittab.py
qutebrowser/completion/models/completionmodel.py
qutebrowser/completion/models/miscmodels.py
qutebrowser/misc/sessions.py
tests/unit/completion/test_models.py

Adds a completion for :back and :forward based on the history API for
the current tab in the current window. The column widths are copied from
the buffer completion. The first column is just the index in history.
I imagine that people may be interested in the `item.lastVisited()`
value which appears to be supported by both backends but we don't save
it out to the session file and it isn't used anywhere else in the
codebase so I held off on that.
Both backend's history classes also have `backItems()` and
`forwardItems()` but they aren't exposed in qutebrowsers history API,
hence the conditional in the list comprehension.
I haven't added a delete function, although I'm sure people will want
it, because:
* since there is no API for it it would involve serializing, editing,
and deserealizing …

Add completion for :back/:forward

---

doc/help/commands.asciidoc
qutebrowser/browser/downloads.py
qutebrowser/browser/downloadview.py

This one adds a right click context menu option to open a downloaded file's directory.
Instead of just opening the file, which may be dangerous / wanting to inspect or operate on it first,
a right click context menu option of `Open directory` lets one open the file's directory. This is akin 
to the main big browsers who has a similar option. i.e. `Show in folder`
Caveats:
- Platform agnostic. uses `os.path.sep`
- Uses the same [utils.py open_file()](https://github.com/qutebrowser/qutebrowser/blob/f3000da73446dfb43f4ef6056ecf61bc4f53ef1c/qutebrowser/utils/utils.py#L653-L709) and [downloads.py open_file()](https://github.com/elig0n/qutebrowser/blob/5bc142a7dbbb171e9fdb931a6f6aa23a5d210b6d/qutebrowser/browser/downloads.py#L623-L641) mechanisms which for most of the cases means utilizing the …

Open a downloaded item's directory via a context-menu option

---

misc/userscripts/qute-pass

The argument is actually `--username-pattern`.

FIX doc userscript qute-pass

---

qutebrowser/completion/completiondelegate.py
tests/unit/completion/test_completiondelegate.py

QStrings use UTF-16, which means characters with Unicode code points above FFFF are represented by a surrogate pair. Python strings represent these code points as a single character. This means that character indices might differ between the two different representations of a string, so if we're using Qt functionality to highlight matches, then we have to get UTF-16 indices (e.g. by using Qt search functionality).
This seems like the sort of issue that might also be causing bugs elsewhere.

Fix misaligned completion highlighting after UTF-16 surrogate pairs

---

misc/userscripts/qute-pass

Since gopass 1.10, reading secrets via "gopass <secret-name>" will yield a deprecation
warning which _run_pass() will stumble over. As it turns out - even "pass" can be called
with "pass show <secret-name>", so the fix will be compatible with both gopass and pass.
Refs #5690

Fix gopass 1.10.x deprecation in qute-pass userscript

---

misc/userscripts/readability-js

Currently, the `readability-js` userscript leaves images untouched, while mozilla's firefox applies at least two  css attributes to them (I checked the html generated by their readability extention to verify this). 
Mozilla's approach seems better: in qutebrowser's `readability-js`, every image is displayed in its original size. For really big images, this can look really odd, and it moreover makes their contents hard to grasp at a glance.
* Example without css styling (note how both images are cut-off):
* Example with css styling, such that images are proportionally shrunk in size in case they're wider than the body-text (achieved by `max-width:100%; height:auto`):
Mozilla does this slighlty differently (I think they center large images, and then make them slightly less wide than the …

[readbility-js] Apply css styling to images

---

misc/userscripts/qute-pass

The `--password-store` argument to `qute-pass` does not affect the invocation of `pass` in the `_run_pass` function.
This leads to a situation where the password is found to exist and the username is returned, but no password is returned (unless the password is found in the default password store).
Easily solved by propagating the relevant path to `pass` as the environment variable `PASSWORD_STORE_DIR`. At least with pass v1.7.3, this is the only documented way of using a non-default password store.

Specify 'PASSWORD_STORE_DIR' when invoking pass from qute-pass

---

misc/userscripts/readability-js

After looking at mozilla's readability script some more, I noticed a couple changes they make to css elements in order to make them easier to visually differentiate from other html elements, and arguably more readable in general. I generally just copied over their css code.  Some of these changes are of a more aesthetic nature, but I would argue that they also have a functional component. 
Btw: I don't think there's much css styling to add after this PR, so don't worry about this script becoming enormous. 
Tables and codeblock elements (`<code>` and `<pre>` tags) now visually standout more. Also note how   the different table cells are the easier to distinguish.  Codeblocks are not really styled in mozilla's readability script, so I copied over the way Github styles them and changed the …

[readability-js] Add css styling to more html elements

---

misc/userscripts/readability-js

Previously, this userscript always assumed the user wanted to parse the current page. However, this meant that something like `:hint all userscript readability-js` wouldn't work. To fix this, the script now checks if qutebrowser is in hinting mode, and sets the target page accordingly.
An alternative solution would be to rewrite this script to rely on `QUTE_URL`+`JSDOM.fromURL` accross the board. However, using `QUTE_HTML` when the target page is already loaded seems faster, uses less data, and works offline.

[readability-js] When hinting, use the URL selected via hints

---

doc/help/settings.asciidoc
qutebrowser/config/configdata.yml

Hi! It's that time of the year again. Now that all the drama with "spamtoberfest" has ended (although I see that qutebrowser was fortunately not affected) I'll be sending some small PRs to fix issues here and there.
I noticed that there is something wrong with the way the documentation for the `tabs.title.format` setting is rendered. It seems to be related with the double single-quotes around `webkit` and `webengine`, so I replaced those with back quotes. The ``` - ``` in
`{title_step}` also looked weird so I changed that too. I'm attaching a screenshot of how it looked:

Fix bad formatting in tabs.title.format docs

---

.gitignore

Do not add vim undofiles by default.
Also, after .swp comes .swo etc., so added those as well.
For hacktober :+1:

update .gitignore for temporary vim files

---

scripts/open_url_in_instance.sh

I have had a bit of hard time debugging `open_url_in_instance.sh` to find out why isn't it faster than just `/bin/qutebrowser` anymore. Turns out I uninstalled `socat` somewhere in the past and the script silently fell back to running `/bin/qutebrowser`. I believe that outputting an error message here doesn't harm. Errors of `socat` are still silenced by the `-lf /dev/null` flag i.e. the script won't complain if there is no socket yet.

Let open_url_in_instance.sh complain if socat is not installed.

---

qutebrowser/browser/webengine/webengineinspector.py

The package on fedora is called `qt5-qtwebengine-devtools`. While a minor issue it helps
pointing users to the needed package when trying to install.
This seems to be the case for all Fedora versions at least 30 or higher:
https://pkgs.org/download/qt5-qtwebengine-devtools

Correct qt devtools package name on Fedora

---

qutebrowser/config/config.py
qutebrowser/config/configcache.py
qutebrowser/config/configcommands.py
qutebrowser/config/configdata.py
qutebrowser/config/configdiff.py
qutebrowser/config/configexc.py
qutebrowser/config/configfiles.py
qutebrowser/config/configutils.py
qutebrowser/config/qtargs.py
qutebrowser/config/websettings.py

`configtypes.py` is large enough by itself that I'll create a separate PR for it.
See #5396

mypy: use from-import for typing in `config`

---

qutebrowser/utils/utils.py
tests/unit/utils/test_utils.py

Closes #5799 
This PR does the following things:
- Fix ```utils.interpolate```  to interpolate alpha channel 
- Makes ```utils.interpolate``` more readable by changing variables names ```a_c1```, ```a_c2``` and ```a_c3``` to ```r1```, ```g1``` and ```b1``` for RGB. Makes similar changes for other color systems as well.
- Fix ```utils._get_color_percentage``` to take alpha channel values as well and return interpolated alpha value based on percentage values
- Add test for alpha interpolation.

Fixes utils.interpolate_color to interpolate alpha channel

---

.mypy.ini
README.asciidoc
misc/requirements/requirements-dev.txt
misc/requirements/requirements-dev.txt-raw
misc/requirements/requirements-qutebrowser.txt-raw
misc/requirements/requirements-tests-git.txt
qutebrowser/browser/webkit/mhtml.py
qutebrowser/utils/version.py
requirements.txt
scripts/dev/recompile_requirements.py
tests/unit/browser/webkit/test_mhtml.py
tests/unit/utils/test_version.py

Closes #5878
This PR does the following things:
- Removes cssutils dependent code from ```mhtml.py```
- Removes cssutils tests from ```test_mhtml.py``` and ```test_version.py```
- Remove everything related to cssutils (readme, requirments, .mypy.ini)

Remove cssutils dependency

---

misc/userscripts/dmenu_qutebrowser
misc/userscripts/qutedmenu

As there is not a file called _history_ to cat from in $QUTE_DATA_DIR, but instead a sqlite file called history.sqlite.
So the changes I've made was to use sqlite3 and an inline query, to extract distinct urls from the History table, and appending them to the list piped into dmenu.
The rest works as it has always done.
Fixes #3091

Re-adding history to dmenu_qutebrowser userscript

---

misc/userscripts/readability-js

I've noticed significant differences between Qt versions in the color output produced under darkmode (often improvements!). Per Qt 5.15.2, I noticed that lines/borders drawn in dark colors are  less visible on pages produced by `readability-js` (not entirely sure why — a lot of borders on other pages seem to stand out more). In fact, table borders are currently invisible, because they're drawn in black, which for some reason doesn't get inverted anymore. 
To rectifiy this, I decided to draw all borders/lines in grey, in line with  what chromium's (?) user agent stylesheet seems to be doing. Because a lot of borders on the web actually seem to be drawn in grayish colors (and not in pure black/white), I think this is a good permanent change (and not just a workaround for something in Qt …

[readability-js] Increase visibility of certain elements under darkmode

---

qutebrowser/completion/models/listcategory.py

The latter is deprecated. See:
https://doc.qt.io/qt-5/qregularexpression.html#notes-for-qregexp-users
Fixes #5909.
Note:
The docs say:
> QRegExp by default does Unicode-aware matching, while
> QRegularExpression requires a separate option; see below for more
> details.
I don't think we need this option, as it only influence character
classes, which we arent using:
https://doc.qt.io/qt-5/qregularexpression.html#PatternOption-enum
> The meaning of the \w, \d, etc., character classes, as well as the
> meaning of their counterparts (\W, \D, etc.), is changed from matching
> ASCII characters only to matching any character with the corresponding
> Unicode property.

Use QRegularExpression instead of QRegExp.

---

qutebrowser/browser/webengine/darkmode.py
qutebrowser/config/qtargs.py
tests/end2end/test_invocations.py
tests/helpers/utils.py
tests/unit/browser/webengine/test_darkmode.py
tests/unit/config/test_qtargs.py

QtWebEngine 5.15.2 doesn't toggle the preferred color-scheme media query
when using `--force-dark-mode`, instead a blink-specific setting needs
to be toggled.
Note: This same setting could probably be used on earlier versions as
well, but to avoid breaking anything that already works, only
QtWebEngine 5.15.2 and above will use this alternate setting.
Note 2: It's not clear that this is the correct value of
`preferredColorScheme`. According to the Chromium source, `kDark` is 0
and `kLight` is 1, but setting `preferredColorScheme` to 0 causes it to
use light mode.
Closes #5915

Fix dark color preference with Qt 5.15.2

---

qutebrowser/app.py
qutebrowser/qutebrowser.py

This adds support an --desktop-file-name CLI option which will set the app_id property under Wayland.
The option is used on Linux to support creating "single site browsers" that function as independent apps-- the window manager will recognize them as independent apps to launch and switch to.
For example, you could treat Gmail as an independent app from "Qutebrowser"
In Chromium, these feature is exposed through the GUI menu as "More tools... > Create Shortcut "Open as window".
The result is a `.desktop` file located in `~/.local/share/application` with lines that looks like this:
```
Exec=/usr/bin/chromium "--profile-directory=Profile 1" --app-id=aebhdehjpceoxxxyyymkchpgbnngobd
StartupWMClass=crx_aebhdehjpceoxxxyyymkchpgbnngobd
```
Qutebrowser already supports `--basedir` as a custom …

Like Chromium, support --app-id arg to set Wayland app_id

---

qutebrowser/utils/jinja.py

Further progress on #4467
guess_mimetype is quite happy with a string and doesn't need to extract temp files that may or may not ever be cleaned up anyway.

reduce use of pkg_resources by not extracting a file to find its filename

---

qutebrowser/misc/utilcmds.py
qutebrowser/utils/utils.py
tests/unit/utils/test_utils.py

The :later command is modified to accept either an integer or time
duration with properly formatted units.
The expected format is XhYmZs, where X, Y and Z are integers
corresponding to hours, minutes or seconds respectively.
The user needs to specify at least one of the units for the command to
work.
In case of integer input, unit is assumed to be seconds.
Closes #5934.

Time units added to :later command

---

README.asciidoc
misc/requirements/requirements-qutebrowser.txt-raw
qutebrowser/utils/utils.py
qutebrowser/utils/version.py
requirements.txt
scripts/dev/recompile_requirements.py
setup.py
tests/unit/utils/test_version.py

In python 3.9, we can get any resource from a package subdirectory using files(), but on older versions of python, even where importlib.resources exists, we need the backport.
Further progress on #4467

Migrate read_file from pkg_resources to importlib.resources

---

qutebrowser/completion/models/miscmodels.py
tests/unit/completion/test_models.py

Because 10 shouldn't be higher than 2.

Retain sort order for undo completion model

---

misc/userscripts/qute-lastpass
tests/end2end/features/keyinput.feature
tests/unit/misc/userscripts/test_qute_lastpass.py

Previously passwords that contains at least two `<` will be entered incorrectly. (for example `:fake-key \<\<` inserts only one `<`)
The bug starts from commit 2f9b3f5ab8ca6e5d1be188201b18ef4835d71004 which changes a somewhat-unrelated issue.
Remark:
* I think if `<less>` is always properly escaped then `<greater>` is unnecessary, but this is just to be sure.
* Actually it's possible to use `\ ` instead of `" "` to escape space too -- unless it's at the end of the string (this feels like a parsing bug somehow), in which case appending `""` works too.
* This is backward-incompatible (some user might not understand why the site reports "incorrect password" after an update), but the same thing happened with the previous change.
* Somewhat related: an error message will be raised if either …

Fix qute-lastpass userscript enters text containing multiple <

---

misc/userscripts/qute-pass

With [this](https://github.com/gopasspw/gopass/pull/1415) gopass PR, a new password format was devised which also became the default.
This format stores passwords in a KV format instead of as raw text, so when invoking `gopass show` the entire KV entry is listed:
```
$ gopass show <my-pass>
> Password: <the-password>
```
qute-pass then pulls in the prepended `Password:`, breaking functionality.
A new `-o` switch was introduced for `show` which allows you to print just the password, which is akin to the old behavior, i.e. what we want actually want.
The switch is harmless for stores using the old format, and so shouldn't break anything for those users.

Fix gopass mime format for qute-pass userscript

---

qutebrowser/mainwindow/tabwidget.py

There is a small typo in qutebrowser/mainwindow/tabwidget.py.
Should read `while` rather than `whlie`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, whlie -> while

---

qutebrowser/browser/shared.py

`scrolling.bar = 'overlay'` does not apply since a14d0d433eec6edb5c9ecb872d458b5793c7f2bd.
It was caused by a simple mistake so I fixed it.

Fix condition for using overlay scrollbar

---

qutebrowser/completion/models/listcategory.py
tests/unit/completion/test_listcategory.py

Entering an overly long search term into the completion causes a crash:
```
PyQt5.QtCore.QRegularExpression.PatternOptions(1)) is not valid: regular expression is too large
```
This can happen, for example, when pressing `go` at the qutebrowser
error page. I'm unclear on exactly what the limit is, but 50k
characters seems to trip it on my machine. Still, it seems like any
pattern larger than a certain amount is likely an error, so I settled on
limiting it to 5k.
Fixes #5973

Don't crash on long search patterns.

---

qutebrowser/config/configdata.yml
qutebrowser/config/qtargs.py
tests/unit/config/test_qtargs.py

Any environment variables can be set using the qt.environ setting in the config.
Closes #5899

Add qt.environ setting in config

---

qutebrowser/browser/history.py
tests/unit/browser/test_history.py

The completion is now regenerated when `completion.web_history.exclude` is set or changed in `config.py`.
I tested this on both `config.py` and `autoconfig.yml` with the setting set, unset and modified, found no issues or crashes.
I think this could be used to replace the rebuild mechanism used exclusively by the `autoconfig.yml`, since it rebuilds any time the patterns change in the already loaded config. I'm not really sure since I'm not familiar enough with the codebase, yet. 
Closes #5868

Fix completion.web_history.exclude not working when set in config.py

---

misc/userscripts/readability-js

Before, the first line of a `code` element within a `pre` element had indentation/padding applied to it, creating the illusion that the first line started with a space. Now, all the lines in `code` elements horizontally align.
Sorry for the messy git stuff, not really sure what I did wrong. The whitespace and capitalization changes in this commit actually match the current contents of readability-js.

[readability-js] horizontally align codeblock contents

---

doc/install.asciidoc

The provided MacOS installation command provided in the docs:
$ brew cask install qutebrowser
When running this, I received the following:
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
I was able to install using:
$ brew install qutebrowser --cask
My homebrew is up to date (2.7.2).

Fix brew installation instructions

---

doc/help/settings.asciidoc
qutebrowser/config/configdata.yml

Default `fileselect.*.command` doesn't work with terminals other than xterm (at lease in st and alacritty). Since default is xterm, this is fine but simply replacing xterm with another terminal should work.

Change default fileselect commands

---

doc/help/settings.asciidoc
qutebrowser/completion/models/filepathcategory.py
qutebrowser/completion/models/urlmodel.py
qutebrowser/config/configdata.yml
tests/unit/completion/test_models.py

In regards to https://github.com/qutebrowser/qutebrowser/issues/32 and https://github.com/qutebrowser/qutebrowser/issues/5792
This adds a new completion category for `:open` for local files. URLs starting with ~ work.

Add local file paths to URL completion

---

qutebrowser/browser/pdfjs.py
qutebrowser/html/no_pdfjs.html

Closes #6076 (which is actually a "discussion", not an "issue").

pdfjs is in the official repositories, no more in the AUR

---

qutebrowser/browser/hints.py

This PR fixes a crash when using the `:hint` command while `hints.mode` is set to `word` and `hints.dictionary` points to a file that can't be decoded as UTF-8.

Prevent crash on non-UTF-8 hint dictionary

---

qutebrowser/browser/shared.py
tests/end2end/features/editor.feature

Closes #6175 
@The-Compiler I think actually it was indeed the `nnn` which accidentally deleted the file, since we do create it [here](https://github.com/AckslD/qutebrowser/blob/6175-no-tmp-file/qutebrowser/browser/shared.py#L358).
Anyway, I added a try-except block and a test where the fileselector is just `['rm', '{}']`.
Is there any way to assert a warning but using e.g. a regex in the `Then the warning ... should be shown`? For example the error is now something like 
```
Failed to open tempfile /tmp/qutebrowser-fileselect-moc83tj9 ([Errno 2] No such file or directory: '/tmp/qutebrowser-fileselect-moc83tj9')!
```
but I would like to just assert the
```
Failed to open tempfile .*!
```
part.
Btw, what's your view on #6116 ?

Handle error if fileselector deletes temporary file

---

tests/unit/misc/test_editor.py
tests/unit/misc/test_ipc.py

Replaced the os methods by their pathlib equivalent when available according to the doc and #176
in the tests/units/misc directory
I'll look into the rest when my exams are finished

Replaced os.stat by the pathlib equivalent

---

qutebrowser/mainwindow/statusbar/command.py
tests/end2end/features/misc.feature

Related to #2865
Ex commands (from `:` prompt) that start with a space are not saved to command history.

Don't save commands starting with space

---

qutebrowser/html/error.html
qutebrowser/utils/jinja.py

Instead of using JavaScript for the "Try again" link on the error page, use a regular link which works even when `content.javascript.enabled` is set to false.
Closes #6204

Use link instead of button+JS in error page

---

qutebrowser/browser/commands.py
tests/end2end/features/sessions.feature
tests/end2end/features/tabs.feature

This PR modifies the existing :open command so that in a pinned tab it shows a warning '_**Tab is pinned!Opening in new tab**_'.And then opens in a new tab like expected.
Closes #6184 .

PR makes :open command in pinned-tab open in new tab.

---

misc/userscripts/readability
misc/userscripts/readability-js

Until per-domains stylesheets are implemented, there is no way to
apply style to the readability page only. With this patch, you can
just use the global setting `content.user_stylesheets` by writing
a more specific CSS selector. For example:
body.qute-readability {
font-family: Libertinus;
font-size: 1.2em;
text-align: justify;
}
will change the font and text alignment of the readability page,
without altering the style of other websites.

userscripts/readability: add unique body class

---

misc/userscripts/readability-js

The mozilla/readability library doesn't output a body by default.
So, let's add one in the header and plug the result in.
I set up nodejs and tested this properly: It seems to work now.
By the way, I see these two warnings in the console:
```﻿
readability.html:5 The key "text/html" is not recognized and ignored.
readability.html:5 The key "charset" is not recognized and ignored.
```
which are about this tag:
```
<meta name="viewport" content="width=device-width, initial-scale=1, text/html, charset=UTF-8" http-equiv="Content-Type">
```
I'm not sure if it's expected...
cc: @The-Compiler @rien333

userscripts/readability-js: fixup of 55fdae8

---

misc/userscripts/readability-js

Apparently, a document's charset is [defined differently in HTML5](https://stackoverflow.com/questions/4696499/meta-charset-utf-8-vs-meta-http-equiv-content-type). Most pages on the web specify their `<meta>` tags in a way that matches the contents of this PR (see e.g. this [mozilla page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta)). 
This fixes a harmless developer console warning oiginally discovered by @rnhmjoj in https://github.com/qutebrowser/qutebrowser/pull/6241#issue-587107512.

[readability-js] Use HTML5 meta tag

---

misc/userscripts/qute-keepassxc

The link [6] in the `qute-keepassxc` userscript points to a documentation site that is not reachable (as of 2021-03-14). This commit repleaces it with the corresponding section in the official doc’s Getting Started guide that explains the steps necessary to set up browser integration with KeepasXC.

userscripts: keepassxc: Fix broken link

---

qutebrowser/commands/parser.py
qutebrowser/commands/runners.py
qutebrowser/completion/completer.py
qutebrowser/completion/models/configmodel.py
qutebrowser/config/config.py
qutebrowser/keyinput/modeparsers.py
tests/unit/commands/test_parser.py
tests/unit/commands/test_runners.py
tests/unit/config/test_config.py

Fixes #5942.
For bindings like `o -> :set-cmd-text -s :open`, the user conceptually
expects that `o` maps to `open`, yet they do not show in the command
completion UI.
With this patch, a binding to a command of form
`set-cmd-text [flags...] :<cmd> [cmdargs]` will be treated as if it were
bound to `<cmd> [cmdargs]` instead for the purpose of completion.
Bindings to `set-cmd-text --append` are ignored.
It ended up feeling right to put this in `get_reverse_bindings_for`, but I
could be convinced it belongs in the completion code instead.

Show set-cmd-text command bindings in completion.

---

misc/userscripts/qute-pass

When the qute-pass userscript is used for OTP generation with gopass, the `-o` flag is necessary (analogous to `gopass show`), otherwise gopass returns some metadata as well, which is also pasted into qutebrowser.
Without `-o`:
297511 lasts 29s 	|-=============================|
With `-o` (the desired behavior):
297511
This PR adds the `-o` flag to the `gopass otp` invocation analogous to `gopass show`.

qute-pass userscript: Add -o flag to gopass otp invocation

---

doc/help/settings.asciidoc
qutebrowser/browser/webengine/webenginesettings.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webkit/webkitsettings.py
qutebrowser/config/configdata.yml

#6209 
Whatsapp: Things seems to be working as expected tested with ```--temp-basedir -s content.site_specific_quirks.skip "['ua-whatsapp','js-whatsapp-web']"  web.whatsapp.com```
Google : Things seems to be working too I got the error once with ``` --temp-basedir -s content.site_specific_quirks.skip "['ua-google']" accounts.google.com``` before getting detected by their js I guess

Disable individual quirks

---

misc/userscripts/qute-keepassxc
qutebrowser/browser/commands.py
tests/end2end/features/conftest.py
tests/end2end/features/sessions.feature
tests/end2end/features/tabs.feature

~~Adds a `--soft` flag to `:tab-only`, which keeps pinned tabs without prompting the user. Essentially it's the opposite of `--force`.~~
Replaces the `--force` flag for `:tab-only` with a `--pinned` flag which decides how pinned tabs should be handled, allowing for the following values: `prompt` (default), `close` and `keep`.
This is my first pull request for qutebrowser, so I'd appreciate any feedback or guidance. So far this is a barebones implementation without any tests.
My use case is that I pin tabs precisely so they won't get closed by `:tab-only`, so it becomes somewhat annoying to have to decline the prompt each time.

Add extra options for handling pinned tabs in :tab-only

---

misc/userscripts/readability-js

This PR solves two problems.
Unlike chromium's and firefox's reader mode, qute's reader output doesn't display the article's title on top of the page. This was done intentionally, because I felt that one could simply glance the title from the tab bar.
I changed my mind, however. First, one's tab bar can be  hidden. Second, it can also be too cramped to contain discernible textual information. Often, I found myself longing for a quick, easy to parse way to tell what a reader tab I once opened was all about. 
Given the screenshot below, it's difficult to tell what the focused article is about.
I think this PR improves this a lot:
It's also more aesthetically pleasing (imo), and more in line with what people expect from a "reader mode".  (note that the text justification is custom css …

[readability-js] Add article metadata on top of the page

---

misc/userscripts/qute-pass

I have a few logins where I only need a password, no username.
And when i run the script currently shipped with qutebrowser using `--password-only`, I get `Failed to match username pattern!`. 
Which is annoying, and I didn't want to add dummy username when the credentials for the site is password-only.
So I edited my local script to only try to match username when its actually needed, so this error wont happen.
And i thought this might be nice to have upstream also, so others can enjoy `--password-only` without having to have a valid username in the file.

qute-pass: extract username/pw only when needed

---

misc/userscripts/qute-bitwarden

Closes #6376 
When requesting credentials from bitwarden CLI (`bw`), this makes the script to check for return code of the process, rather than the current `stderr`.

Make qute-bitwarden to use return code rather than stderr for error check

---

misc/userscripts/qute-pass

`qute-pass` in its current state runs pass twice when ran with `--otp-only` arguments, which is annoying having to authorize twice when using hardware gpg key etc.
So I added `not arguments.otp_only` to the condition here to avoid that.

qute-pass: dont run pass twice when otp-only is used

---

doc/help/settings.asciidoc
qutebrowser/config/configdata.yml

Having `text` at a different part of the documentation confused people, so I added it to valid_values. This should not change anything in behavior, since this option will be intercepted before the valid_values are handled.
Closes #6414

Added `text:` to statusbar.widgets valid_values

---

qutebrowser/config/config.py
tests/unit/config/test_config.py

2c4bb064e introduced support for showing bindings in the completion menu
for commands initiated with set-cmd-text. This would crash if given a
binding for just 'set-cmd-text' with no args.
Fixes #6453.

Fix crash in cmd completion for set-cmd-text.

---

misc/nsis/qutebrowser.nsi

Because of the workaround for the uninstaller elevation bug of Windows, this is required for the silent uninstall of `AllUsers`, even when started elevated. Fixes #6496.

Windows Installer: Allow elevation when silent

---

misc/userscripts/readability-js

I just added the readability package to the [AUR](https://aur.archlinux.org/packages/nodejs-readability-git/).
Not much of a difference from using npm directly, but, personally, (i) I prefer to manage all my (important) packages using `yay`, and (ii) like to perform all system upgrades from one place (i.e. `yay --devel`, instead of also remembering to deal with npm).

[readability-js] Add reference to AUR package

---

doc/userscripts.asciidoc
qutebrowser/browser/hints.py

Related to #937
I used the added variable to create the following userscript that yanks the URL with an element that has an `id` attribute. (e.g. selecting "hints selectors" section puts qute://help/settings.html#hints.selectors in clipboard)
To make it work, add `"[id]"` as a `hints.selectors`.
Now in qutebrowser:
`:hint <hints.selector> userscript <script_path>`
```bash
#!/bin/bash
URL=$(echo $QUTE_CURRENT_URL | cut -f -1 -d "#")
HTML_ID=$(echo "$QUTE_SELECTED_HTML" | grep -oP 'id="\K(.+?)(?=")')
LINK="$URL#$HTML_ID"
echo $LINK | xclip -selection clipboard
echo "message-info 'url copied to clipboard'" >> "$QUTE_FIFO"
```

feat: expose 'currently open URL' variable via hints to userscripts

---

doc/help/configuring.asciidoc

Adding link to a new collection of qutebrowser themes I just started, as requested in [discussions](https://github.com/qutebrowser/qutebrowser/discussions/6612#discussioncomment-1033462).
There's only onedark so far, but I'll be adding more.

add link to 'leosolid/qutebrowser-themes' in docs under 'Pre-built colorschemes'

---

misc/userscripts/qute-pass

The default behaviour of qute-pass userscript will insert a password automatically if there is only a single candidate found.
This option will force the selection prompt (i.e. dmenu) to show regardless of how many
password candidates are found.
I'd like to confirm that the correct password is selected before entering it into a site.

Optionally ask for confirmation before inserting a password in qute-pass userscript

---

misc/userscripts/qute-pass

Add an option to show all secrets, whether they match the current url or not.
I have two use cases where this comes in handy:
1. Password is shared between services, but is not duplicated in the password store. This is mostly when I use shared password store where I do not have control over the content
2. Services might temporarily be reachable under a different URL or via port forwarding and therefore not matching the name/path stored in the store

Optionally provide unfiltered selection of secrets in qute-pass userscript

---

qutebrowser/browser/commands.py
tests/end2end/features/tabs.feature

Adds a `--private` option to `:tab-clone` to clone the tab into a private window, matching the flags already available for `:open` and `:tab-give`.

Add a --private option to :tab-clone

---

qutebrowser/browser/commands.py
qutebrowser/browser/webengine/notification.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/commands/runners.py
qutebrowser/keyinput/keyutils.py
qutebrowser/keyinput/modeman.py
qutebrowser/utils/debug.py

I managed to get a new enough cmake and icu on debian so I have a 6.2 Qt build now. I wanted to get a working browser running on it so I can look for regressions in Qt but haven't really managed to get past PyQt yet. Probably won't have too much more time to look at it until next weekend.
This PR is based on the qt6-test branch and all the fun on there. The good news is that a lot of stuff works! (To be clear to anyone unclear of the state of qutebrowser's 6.2 support: getting stuff working at this point just lets us do regression testing, there is still a bunch of refactoring to do to make the codebase work on both 5.15 and 6.2.)
The most widespread issue I've seen so far is from enums. There are a bunch of places where we do things like:
`int(some_enum_value)`
`if some_enum_value:`  (so …

More (Py)Qt 6 hacks

---

tests/conftest.py
tests/end2end/conftest.py
tox.ini

With these changes the backend is picked automatically when running tests.
QtWebKit will be picked over QtWebEngine if both are available. Otherwise we pick the backend, which is available.
The backend auto-detection mechanism can be overriden by passing the backend to pytest via `--qute-bdd-backend=<backend>` or by settings the environment variable `QUTE_BDD_BACKEND=<backend>`. Accepted values for `<backend>` are `webkit` or `webengine`.
Closes #3051

Pick backend automatically for tests

---

qutebrowser/browser/commands.py
qutebrowser/mainwindow/tabbedbrowser.py
tests/end2end/features/tabs.feature

Add an optional boolean argument to `tabbed_browser.close_tab()` called
`transfer` which indicates whether the tab is closing as a result of
being given to another window (`tab-give`) or taken by another window
(`tab-take`). If so, the tab will always close, even if it is the last
tab in the window and `tabs.last_close` is not set to 'close'.
Closes #5836.

Always close tabs when given or taken

---

qutebrowser/config/configdata.yml

It's very common for `tabindex=-1` which just means to remove the element from sequential tabbing.  Modifying the default hinting selecto `[tabindex]` to ignore them when the value is `-1` removes a lot of false positive hints.
https://github.com/philc/vimium/blob/master/content_scripts/link_hints.js#L998
Related: https://github.com/qutebrowser/qutebrowser/issues/178
See the album text before and after change
BEFORE
AFTER

ignore -1 tabindex for hints

---

qutebrowser/browser/webengine/webenginetab.py
qutebrowser/mainwindow/tabbedbrowser.py

Closes #6168. On tabs with audio that becomes silent for short intervals, e.g. lectures or podcasts, the audible status indicator [A] no longer flickers in and out of the tab title.
I picked a 2 second delay because this change is meant to work around the QT signal [recentlyAudibleChanged](https://doc.qt.io/qt-5/qwebenginepage.html#recentlyAudibleChanged)'s failure to be "emitted with an approximate two-second delay, from the moment the audio is paused".
On my machine, starting any audio in a tab emits `recentlyAudibleChanged` twice. `tab.audio.is_recently_audible()` is `False` the first time around and `True` the second time, so the line `self._on_audio_changed_throttle._last_call_ms = None` is necessary to immediately display the indicator [A]. This asymmetry in behaviour upon dropping …

Delay changing audible status

---

qutebrowser/mainwindow/mainwindow.py

Fixes #3615. This is maybe only a temporary fix, given the larger issues in #632, but I'm submitting a PR anyway because the current behaviour is a *major* annoyance for `tabs_are_windows` users.

Make confirm_quit=downloads only ask when closing the last window

---

doc/help/settings.asciidoc
qutebrowser/config/configdata.yml
qutebrowser/mainwindow/tabwidget.py

Adds `relative_index` to FormatString, which provides tab numbers like to `relativenumber` in vim.  You can try it out by running:
```
set tabs.position left;; 
set tabs.title.format '{relative_index} |{aligned_index}: {current_title}';;
repeat 20 tab-clone
```
This closes #6616. 
EDIT: This is what it looks like

add relative line numbers for tabs

---

qutebrowser/browser/webengine/notification.py
tests/end2end/features/notifications.feature

This is my first time in the qutebrowser codebase, so apologies if I did things in a weird/roundabout way.
Fixes #5796.

Switch to a matching tab when clicking on notification

---

misc/userscripts/qute-bitwarden

This allows it to work on Wayland (my use case), but also opens up the
possibility of using the system keychain to manage the password, or any
other method the user might want.
Closes #6558
Alternative to #6930
/cc @The-Compiler @JonnyHaystack @carlosgarciafm
---
I use this with the following config:
```yaml
<Ctrl+Shift+l>: spawn --userscript qute-bitwarden --totp --dmenu-invocation 'wofi --dmenu --insensitive --prompt Bitwarden' --password-prompt-invocation 'wofi --dmenu --prompt "Master Password" --password --lines 0'
```

qute-bitwarden: let the user specify their password prompt

---

misc/userscripts/README.md

In response to the request on [r/qutebrowser](https://www.reddit.com/r/qutebrowser/comments/s3xqas/comment/hsqn8db/?utm_source=share&utm_medium=web2x&context=3), I'd like to add yomichad, a Japanese pop-up dictionary to the list of userscripts.

Add yomichad to userscripts

---

qutebrowser/completion/models/miscmodels.py
tests/unit/completion/test_models.py

As delete_tab was assuming that completion column contains window ID, it was showing
exception in case of tab-focus, as it doesn't have the window ID in completion column.
So instead a new parameter named current_win_id is used in _tabs which is also passed
in all uses of the _tabs function. This PR Closes #6967.

Added window id parameter in _tabs funciton used it in delete_tabs function

---

qutebrowser/html/settings.html

Show only the first line of the description of a setting. 
This makes all the settings the same size, giving a better overview. 
Display or hide the description according to the button click.
Show more:
Show less:

Hide long description of settings 

---

misc/userscripts/cast

The `cast` userscript hasn't worked for me in a while (qutebrowser says "Casting \<my url\>" but the TV just shows black), because it attempts to launch youtube-dl which has been replaced by yt-dlp for some time. Switching this one command gets `cast` working for me.

Switch `cast` userscript from youtube-dl to yt-dlp

---

misc/userscripts/qute-pass

Since at least two years back (gopass 1.9, but probably further back) gopass has supported specifying a subfolder prefix when listing secrets (`gopass list mysubdir`). This can easily be supported by qute-pass in gopass-mode, without affecting any other use cases: Even if the user specifies an invalid subfolder, gopass will handle that problem and fail gracefully.

qute-pass: Support folder prefixes in gopass-mode

---

qutebrowser/browser/webengine/webengineinspector.py

When double-clicking a network resource in the devtools, one
get AttributeError: 'WebEnginePage' object has no attribute 'view'.

Qt6 WebEnginePage creatWindow api change

---

misc/userscripts/ripbang

Duckduckgo now rejects requests without a user agent set, and has changed the redirect url format slightly.  Qutebrowser's searchengines setting moved, and needs to be set with config-dict-add instead of set.

Fix ripbang userscript

---

doc/userscripts.asciidoc
qutebrowser/browser/commands.py

There might already be a way to do this, but I couldn't figure it out. The impetus for this change came up when I was writing a [simple "autorefresh" script](https://github.com/willruggiano/dotfiles/blob/main/modules/common/qutebrowser.nix#L47-L78).

feat: pass QUTE_TAB to userscripts

---

qutebrowser/config/configdata.yml
qutebrowser/misc/editor.py
tests/unit/misc/test_editor.py

Second attempt, thanks to the comments by @The-Compiler.
This patch provides an option to never remove the files written by an external editor. This can be useful if you are dealing with a rogue website, where the texts could be properly written but later lost anyway (because of automatic logoff or network failure, for example).

External editor: add an option to never remove the file upon closing

---

misc/userscripts/open_download

Make `open_download` compatible with Flatpak.
flatpak-xdg-utils's `xdg-open` send the request to open a file with associated application through XDG Desktop Portal, letting the user select application with the AppChooser Portal.  
In the Flatpak sandbox, we don't know which app would be launched, and we know very little about mime types.  
I also think that `open_download` should wait for `xdg-open` return code. We want to know when `xdg-open` failed, and we want to read the output with `:process`.

userscripts/open_download: Flatpak compatibility

---

misc/userscripts/qute-keepassxc

This PR fixes a bug in the keepassxc user script, where using the `--insecure` flag would not lead to the expected behaviour.
The main issue is, that `args.key` is never None, which makes the `if gpgkey is None` check useless. \
My fix is to check against the `insecure` flag instead.

fix bug in keepassxc user script when using --insecure

---

misc/userscripts/qute-bitwarden

The qute-bitwarden userscript is not able to autofill for a multi-level subdomain URLs (e.g. `http://my.sub.domain.local/`).
qute-bitwarden exits with status code 2 and returns the following on stderr:
```
No pass candidates for URL 'http://my.sub.domain.local/' found!
```
Joining the extracted subdomain and domain with a `.` solves the issue.

Fix qute-bitwarden userscript URL matching for multi level subdomains

---

qutebrowser/config/configdata.yml
tests/unit/browser/webkit/test_webkitelem.py

This makes e.g. channels in Slack's channel list hintable.

Add `[role="treeitem"]` to hintable elements

---

misc/userscripts/readability-js

It makes no sense to force text to be white, especially for users that already use a white background. I probably included this line by mistake.

[readability-js] Remove superfluous css

---

scripts/asciidoc2html.py

I recently tested the patched I proposed a few months ago in<https://github.com/qutebrowser/qutebrowser/issues/7106#issuecomment-1087654549> in a virtual environment installation of `qutebrowser` and it worked.
As mentioned in #7106, this issue will probably be resolved either way once qutebrowser v3 is released and the documentation will be rewritten in `sphinx` instead of `asciidoc`, but, since qutebrowser v2.5.1 has been released after I published the patch, and there is a plan for a qutebrowser v2.5.2 release, I think it makes sense to use the patch and fix this issue. :)
Closes #6900

asciidoc2html.py: also install qute://install.html and qute://stacktrace.html

---

misc/nsis/install.nsh
misc/nsis/qutebrowser.nsi

I'm submitting these two small fixes, in case the new version won't be ready for the next release.
Fixes #7109: On upgrades, the Desktop/StartMenu icon creation is deselected, if not already present.
Fixes #7112: Change the default color values of the interface, so that they are retrieved from the system, instead of being hardcoded.

Windows installer fixes

---

qutebrowser/browser/shared.py
qutebrowser/config/configdata.yml
qutebrowser/mainwindow/prompt.py
tests/end2end/features/conftest.py
tests/end2end/features/downloads.feature
tests/end2end/features/test_downloads_bdd.py
tests/end2end/features/test_editor_bdd.py

Closes #1365 
I haven't added tests yes cause it would be great to have some feedback if others think this is a good way to handle things.
What this MR enables is a new command and keybind in the download prompt to trigger an external folder picker. When the picker finishes the prompt gets updated with a new default value.
One could do some things differently here. For example:
* When a folder is chosen, directly accept the prompt. However I thought it would be better to first see what was chosen and then accept.
* Allow a setting such that the external picker is triggered directly. But is seems nice to still have the option to for example choose to open the download etc.

feat(download) support external location picker

---

qutebrowser/browser/browsertab.py
qutebrowser/browser/commands.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webkit/webkittab.py
qutebrowser/config/configdata.yml
qutebrowser/mainwindow/mainwindow.py
qutebrowser/mainwindow/statusbar/bar.py
qutebrowser/mainwindow/statusbar/searchmatch.py
qutebrowser/mainwindow/tabbedbrowser.py
scripts/dev/check_coverage.py
tests/end2end/features/search.feature

Fixes #3910, #6345, #5351.
This PR adds a match counter to the statusbar when starting a search and using `:search-prev` and `:search-next`, which is between the keystring and URL display by default (but can be moved and disabled like the other statusbar widgets).
It also adds an option to disable the search wrapping messages (`Search hit TOP` and so on) and restructures some of the QtWebEngine searching code in general.
I removed the janky "check scroll position to determine whether we wrapped around" code and replaced it with a match counter comparison, which does mean that the wrapping messages will no longer display on `qt < 5.14`, but will now work even when wrapping doesn't cause scrolling (because all the results are grouped together or the page is very short). If the messages …

Add statusbar match counter and option to silence search wrap messages, fix wrap messages not displaying

---

qutebrowser/browser/browsertab.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webkit/webkittab.py
qutebrowser/misc/sessions.py

Currently the session-save commande make a dump of all tabs history and stores
them in the session file. --minimal flag adds the option to store only the last
item of the history.
Signed-off-by: shirenn <shirenn@crans.org>
Closes #7183

Add --minimal option to session-save command

---

README.asciidoc

It seems that, now, the luakit homepage is at <https://luakit.github.io/> and <https://luakit.github.io/luakit/> is just an HTML redirect to it.
Let's avoid the annoying redirect.

README.asciidoc: avoid HTML redirect for luakit website

---

doc/install.asciidoc

Before the patch:
After the patch:

docs: fix asciidoc syntax in install.asciidoc

---

.mypy.ini
README.asciidoc
misc/requirements/requirements-qutebrowser.txt-raw
qutebrowser/mainwindow/mainwindow.py
qutebrowser/misc/earlyinit.py
qutebrowser/utils/version.py
requirements.txt
scripts/dev/changelog_urls.json
tests/unit/utils/test_version.py

Use PyObjC to call `setWindowMask:` with resizable flag on the
underlying NSWindow.
Fixes #4067

macOS: fix hide_decoration making window nonresizable

---

.github/workflows/ci.yml
misc/requirements/requirements-mypy.txt
qutebrowser/browser/browsertab.py
qutebrowser/browser/hints.py
qutebrowser/browser/qtnetworkdownloads.py
qutebrowser/browser/webelem.py
qutebrowser/browser/webengine/certificateerror.py
qutebrowser/browser/webengine/darkmode.py
qutebrowser/browser/webengine/notification.py
qutebrowser/browser/webengine/webenginedownloads.py
qutebrowser/browser/webengine/webengineinspector.py
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/browser/webengine/webview.py
qutebrowser/keyinput/keyutils.py
qutebrowser/mainwindow/mainwindow.py
qutebrowser/mainwindow/prompt.py
qutebrowser/mainwindow/tabbedbrowser.py
qutebrowser/misc/sql.py
qutebrowser/qt/sip.py
qutebrowser/utils/debug.py
qutebrowser/utils/qtutils.py
qutebrowser/utils/usertypes.py
qutebrowser/utils/version.py
tox.ini

I'll probably merge this next week some time since I don't think it is too contentious. But if anyone wants to have a look at the mypy fixes/hacks and suggest any improvements then please feel free!
As per the discussion https://github.com/qutebrowser/qutebrowser/discussions/7372 we're gonna get mypy running in CI with PyQt5 first, as that's the closes by far to actually working, and then figure out PyQt6 later. This PR re-enables the mypy github action, based on PyQt5, and fixes (well, ignores) errors mypy raises in that.
There are three general classes of issues here:
1. stuff that was added in the last few months when we didn't have mypy setup in CI and just didn't have (the right) type hints
2. stuff that was dependant on the backend that mypy couldn't reason about
3. the PyQt5-stubs …

Get mypy working, with pyqt5, on qt6-v2 branch

---

misc/userscripts/readability

Used to construct fully-qualified URLs from relative links. Without it you get broken images and links.

Send source URL to Breadability

---

doc/contributing.asciidoc
tox.ini

Adds a bit in the styleguide bit of the contributor docs about mypy. Not sure if that's the right place for it.
There is probably too many words here. I'll have another look at it on the weekend.
I had to do some uglyness in that paragraph trailing the code block to keep it indented properly in the generated docs and somewhat indented in the source. The internet says to avoid indentation in lists in asciidoc and use `**`, `***` etc for nested lists. But we are indenting stuff a lot in this file already.
Also updates the default tox env list which I forgot to do when changing the mypy targets.

doc: add some contributor notes about mypy

---

qutebrowser/app.py
qutebrowser/browser/commands.py
qutebrowser/browser/navigate.py
qutebrowser/browser/shared.py
qutebrowser/browser/webelem.py
qutebrowser/mainwindow/mainwindow.py
qutebrowser/mainwindow/prompt.py
qutebrowser/mainwindow/tabbedbrowser.py
qutebrowser/mainwindow/tabwidget.py
qutebrowser/mainwindow/windowundo.py
qutebrowser/misc/quitter.py
qutebrowser/misc/sessions.py

To fix #7504, delay calling `.show()` on windows until after a tab has been added to them.
This needed various bigger changes - I've tried to keep things in separate commits and add explanations to the commit messages. 
Other than the actual changes needed for the issue, this also contains a workaround/fix (hopefully!) for QStyle-related crashes in #5385 and #5124 - and finally, while I was at it, switches to QProxyStyle: #812.

qt6: Delay showing windows

---

misc/userscripts/tor_identity

Usage of the following example is not available unless `-p` is added.
`usage: tor_identity [-h] [-c CONTROL_PORT] [-p PASSWORD]`

Fix: Add `-p` to examples

---

qutebrowser/browser/history.py

Recently the FreeBSD port of sqlite has DQS feature disabled by default. Without this feature enabled, it's not allowed to use double quotes for string literals. As such quoting is used in the history.py module, qutebrowser fails to work on such configurations.
The fix is to use single quotes instead.
ref: #7596

browser: history: fix queries for when DQS disabled

---

qutebrowser/config/configdata.yml

I noticed this one was left when I yanked an URL.

Add `utm_name` to URL params that are stripped

---

tox.ini

```
$ tox -e vulture-pyqtlink
vulture-pyqtlink installed: adblock==0.6.0,colorama==0.4.6,Jinja2==3.1.2,MarkupSafe==2.1.3,Pygments==2.15.1,PyYAML==6.0,qutebrowser==2.4.0,toml==0.10.2,vulture==2.7,zipp==3.15.0
vulture-pyqtlink run-test-pre: PYTHONHASHSEED='499409345'
vulture-pyqtlink run-test: commands[0] | .tox/vulture-pyqtlink/bin/python scripts/link_pyqt.py --tox .tox/vulture-pyqtlink
File "scripts/link_pyqt.py", line 232, in <module>
main()
File "scripts/link_pyqt.py", line 226, in main
wrapper = os.environ["QUTE_QT_WRAPPER"]
File "/usr/lib/python3.10/os.py", line 680, in __getitem__
raise KeyError(key) from None
KeyError: 'QUTE_QT_WRAPPER'
ERROR: InvocationError for command .tox/vulture-pyqtlink/bin/python scripts/link_pyqt.py --tox …
```

tox: Fix vulture-pyqtlink environment

---

qutebrowser/browser/commands.py
tests/end2end/features/search.feature

These changes fix a regression introduced in e15bda307e42c288b926f578e7bf8c610e4767af:  
> When doing `/thisdoesnotexist` and then pressing `n` or `N`, "Search result vanished..." gets displayed.
We do not want to display any message. So we simply remove the message and cover this behavior with two test cases.
---
Closes #7275

Don't show warning when jumping to next/prev search result without matches

---

qutebrowser/browser/network/pac.py
qutebrowser/browser/qtnetworkdownloads.py
qutebrowser/browser/webkit/network/networkmanager.py
qutebrowser/misc/earlyinit.py
qutebrowser/misc/httpclient.py
qutebrowser/misc/quitter.py
qutebrowser/qt/machinery.py
qutebrowser/utils/log.py
qutebrowser/utils/qtlog.py
tests/end2end/test_invocations.py
tests/unit/utils/test_log.py
tests/unit/utils/test_qtlog.py

Using the `--logfilter` argument crashes qutebrowser:
```
$ qutebrowser -T about:blank --debug --logfilter sql
File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "__main__.py", line 27, in <module>
sys.exit(qutebrowser.qutebrowser.main())
File "qutebrowser.py", line 239, in main
earlyinit.early_init(args)
File "misc/earlyinit.py", line 340, in early_init
info = machinery.init(args)
File "qt/machinery.py", line 278, in init
raise Error("init() already called before application init")
qutebrowser.qt.machinery.Error: init() already called before application init
```
Introduced in f65a692 cbea801.
These changes …

Don't crash on --logfilter at startup 

---

scripts/mkvenv.py

This is a follow-up of #7770 which was an attempt to fix the script broken in 9212ba9.
Before flipping the QT6 switch.

mkvenv: Fix '--pyqt-type link' without --pyqt-version

---

setup.py

Building qutebrowser showed some warnings as the following:
```
/tmp/build-env-4jb2oh0t/lib/python3.8/site-packages/setuptools/command/build_py.py:201: _Warning: Package 'qutebrowser.html' is absent from the `packages` configuration.
!!
********************************************************************************
############################
############################
Python recognizes 'qutebrowser.html' as an importable package[^1],
but it is absent from setuptools' `packages` configuration.
This leads to an ambiguous overall configuration. If you want to distribute this
package, please make sure that 'qutebrowser.html' is explicitly added
to the `packages` configuration field.
Alternatively, you can also rely on setuptools' discovery methods
(for example by using …
```

Include namespace packages in setuptools build

---

qutebrowser/utils/version.py
tests/unit/utils/test_version.py

Currently, ":version" fails to show the sip version for Qt6. This is because the sip module can't imported in the same way as Qt5. In Qt5, the sip module can be imported after "from PyQt5.QtCore import *". In Qt 6, this is no long the case,
>>> from PyQt6.QtCore import *
>>> import sip
File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'sip'
So import sip from PyQt6 explicitly.

qt6: import sip from PyQt6

---

.github/workflows/ci.yml
tox.ini

Add a CI job for running a package build with warnings turned into exceptions.
Now CI will fail on any warnings popping up during the package build (e.g. `DeprecationWarning`). This will help catch potential issues early on.
Related docs:
* https://docs.python.org/3/using/cmdline.html?highlight=pythonwarnings#envvar-PYTHONWARNINGS
* https://docs.python.org/3/library/warnings.html#warning-filter
* https://docs.python.org/3/library/warnings.html#describing-warning-filters
---
Closes #7773

Run package building on CI with warnings turned into errors

---

qutebrowser/misc/sessions.py
tests/end2end/features/sessions.feature

Opening a download in a new tab leaves a "dead" tab (see example of a "dead" tab below) behind. When saving a session containing such a "dead" tab, we end up with entries in the session like this one:
```yaml
- active: true
history:
- active: true
last_visited: '1970-01-01T02:00:00'
pinned: false
scroll-pos:
x: 0
y: 0
title: ''
url: ''
zoom: 1.0
```
When loading a session containing such a "dead" tab, qutebrowser does not restore any history of that session and logs the following error:
```
ERROR: Failed to load session default: PyQt6.QtCore.QUrl('') is not valid
```
As pointed out by @The-Compiler in https://github.com/qutebrowser/qutebrowser/issues/7696#issuecomment-1672854592, the behavior of [QWebEngineHistoryItem::isValid()](https://github.com/qt/qtwebengine/blob/v6.5.2/src/core/api/q …

Don't include "dead" tabs when saving sessions

---

qutebrowser/browser/webengine/webengineelem.py
tests/end2end/data/hints/link_inject.html
tests/end2end/features/conftest.py
tests/end2end/features/hints.feature
tests/end2end/fixtures/quteprocess.py
tests/helpers/testutils.py

As of Qt 6 navigating from local to remote origins requires user interaction. This broke following links to remote origins via hints from a local file (e.g. `bookmarks.html`), because hints use JavaScript to open links by default.
Example:
1. Have a local `bookmarks.html`:
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>My bookmarks</title>
</head>
<body>
<a href="https://example.com/" id="link">some bookmark</a>
</body>
</html>
```
2. Open that local `bookmarks.html` in qutebrowser (e.g. `:open path/to/bookmarks.html`)
3. Start hinting
4. Follow a link to a bookmark (e.g. https://example.com/)
5. Instead of the link opening, be presented with `Your internet access is blocked` error
To fix this, we simply force a user interaction for all hints on file:// URLs (like we …

Allow navigating from file:// to remote origins via hints

---

qutebrowser/browser/webengine/webenginetab.py
qutebrowser/keyinput/modeparsers.py

Closes #7887.
Moves the `timer.timeout.connect` statements to regions where they will only be run once, which fixes the referenced issue and duplicate slots no longer accumulate ad infinitum.

Fixing timers accumulating duplicate slots

---

doc/changelog.asciidoc
doc/help/settings.asciidoc
qutebrowser/config/configdata.yml
qutebrowser/config/qtargs.py
tests/unit/config/test_qtargs.py

Adds a `qt.workarounds.disable_accelerated_2d_canvas` setting that can handle adding the `--disable-accelerated-2d-canvas` setting into the Qt args as desired.
It's set to `auto` by default and added in based on whether the webengine's chromium version is 111 or higher. (Note that we still need to verify that fix in chrome 111 actually fixes the issue our users are seeing). And [apparently](https://github.com/qutebrowser/qutebrowser/blob/434f6906f9088172494fa7e219a856d893ed55ba/qutebrowser/utils/version.py#L616) chromium 112 will be in Qt 6.6.0.
I'm a little leary of the double negative in the setting (setting it to `never` means you do get accelerated canvas), but it is a "workaround" setting so the disable terminology comes from that. Accelerated canvas is the default, so while we could …

Add setting to disable accelerated 2d canvas

---

qutebrowser/mainwindow/prompt.py

A possible solution for #7222 
Prevents `QFileSystemModel` from trying to load an icon for every entry in the download directory (which is not needed since the download prompt doesn't display icons), by overriding the `icon` method of `QAbstractFileIconProvider` with one that always returns a "null icon". The `type` method returning some (nonempty) fixed string replaces a further lookup for the textual description of a mime type.

Override IconProvider for QFileSystemModel

---

doc/changelog.asciidoc
qutebrowser/browser/webengine/webview.py
qutebrowser/utils/qtutils.py
tests/unit/browser/webengine/test_webview.py

Add filename extensions to the filepicker from the python `mimetypes` module to mitigate installs affected by the upstream bug around QMimeDatabase only looking at the first mime database where it found a registered type.
Oh, regarding the image/* bit, this is there qtwebengine does the same thing, for reference: https://github.com/qt/qtwebengine/blob/6.5.2/src/core/file_picker_controller.cpp#L264
Fixes: #7866

Add suffixes for mimetypes to filepicker from python

---

qutebrowser/utils/message.py

I tried to use `message` in `confirm_async` as per the docstring, resulting `TypeError: _build_question() got an unexpected keyword argument 'message'`. Nothing actually tries to use it. Follow-up to f0ed43ec203026952955882d533ecadaee4832fc. :smile:

Fix docstrings

---

doc/changelog.asciidoc
qutebrowser/mainwindow/mainwindow.py
qutebrowser/mainwindow/prompt.py
qutebrowser/mainwindow/statusbar/bar.py
qutebrowser/mainwindow/tabbedbrowser.py

Almost 7 years ago, it was observed that hiding the status bar causes some websites being scrolled to the top: #2236.
Back then, it never really was clear why this happens. However, with the v3.0.0 release, we had a regression causing the same thing to happen when leaving prompt mode: #7885.
Thanks to "git bisect", the culprit was found to be 8e152aa, "Don't give keyboard focus to tab bar", which was a fix for #7820. However, it still wasn't clear why this phenomenon happens.
What made things clearer to me was a combination of debugging and an old comment by pevu: https://github.com/qutebrowser/qutebrowser/issues/2236#issuecomment-337882102
> Chromium-browser has the same issue. When you open lipsum.com, scroll down,
> then focus the location bar (url box), then press Tab, it will jump to …

Explicitly handle focus before hiding UI elements

---

qutebrowser/completion/models/listcategory.py
tests/unit/completion/test_listcategory.py

Part of #6114. Bookmarks and `:tab-select` are searched in any order of search terms. Commands and setting names etc. don't yet support multi-word searches.
`url_completion_benchmark` becomes 11% slower (453->505ms) and a [heavier benchmark](https://github.com/arza-zara/qutebrowser/commit/4f447faeb748027785b5e49f2542e218debcc74b) becomes 20% slower.
This seems to be compatible with #3855 (I haven't tested).

Search ListCategory in any order of search terms

---

qutebrowser/mainwindow/tabbedbrowser.py
qutebrowser/mainwindow/treetabbedbrowser.py
qutebrowser/misc/sessions.py
tests/end2end/features/sessions.feature
tests/end2end/features/treetabs.feature

Relating to https://github.com/qutebrowser/qutebrowser/issues/8076 and following on from https://github.com/qutebrowser/qutebrowser/commit/a2f98aa78b529de9a730beaafe522b38a8a977c3 this PR proposes a fix and an improvement:
**fix loading of tab in collapsed tab groups**
Tabs in collapsed tab groups were being dropped because the code was iterating over the tabs loaded into the tab widget instead of all those in the tree. Easy spot, easy fix.
**support loading legacy tree tab session formats**
There are some long time community members who have been using this PR for a while and may have built up complicated session files which they are dreading having to rebuild. Currently if they pull the latest on the `tree-tab-integration` branch the browser will just crash on startup.
I had a look at …

Fix loading collapsed tabs and legacy session support

---

doc/changelog.asciidoc
qutebrowser/misc/crashsignal.py
tests/unit/misc/test_crashsignal.py

Before this commit qutebrowser would just exit when receiving a SIGHUP. Now it will reload the config using the bare config_source function, just like the :config-source command does.
Closes #8108.

Allow reloading config on SIGHUP

---

doc/changelog.asciidoc
qutebrowser/utils/version.py
tests/unit/utils/test_version.py

Webengine added a getter for their chromium patch level back in Qt 6.3, since they backport security fixes from chromium in the periods between doing major chromium feature upgrades. The default simplebrowser start page (chrome://qt/) inspired me to add it to our version page:
It's pulled from a hardcoded string in the webengine source `src/core/web_engine_context.cpp` that's manually updated when they backport something.
The "(plus any distribution patches)" bit in there is because it was pointed out that some distributions backport their own security patches or even use webengine from a branch when the hardcoded string only gets updated at release time, despite patches being backported in the meantime. As discussed in the linked issue.
Closes: #7187

Show chromium security patch version in :version

---

tests/end2end/features/conftest.py
tests/end2end/features/treetabs.feature
tests/end2end/fixtures/quteprocess.py

I simply translated [parts of @toofar's superb documentation](https://github.com/qutebrowser/qutebrowser/blob/160e9f274f252bd54a6c03f369b0de6e0ab8c98d/doc/treetabs.md?plain=1#L60-L66) into end2end tests.
Covering
* `:tab-close` without `--recursive`
* `:tab-next --sibling`
* `:tab-prev --sibling`
* `:tab-focus parent`
* `:tab-move <index>`
---
Fixes part of #8072

Add more end2end tests for tree tabs feature

---

qutebrowser/html/version.html
qutebrowser/utils/version.py
tests/unit/utils/test_version.py

Split the version info into multiple lines to make it a bit more digestible. Infer the security version based on the QtWebEngine version if the API is unavailable, since we already have that information anyways (see the commit message for details).

Improve Chromium (security) version output

---

doc/changelog.asciidoc
qutebrowser/completion/completionwidget.py
tests/unit/completion/test_completionwidget.py

* Change `on_clear_completion_selection()` back to call the Qt getter instead of our one that does an `assert not None` check, it already handles None being returned fine
* Add a half-hearted unit test (which was failing previously because of the assertion error)
I didn't put much effort into reproducing it beyond manually hammering the completion in a temp basedir (possibly if the completion was slower because of more items it would be easier to reproduce). That commit history was pretty clear, we've always handled this situation (whatever it is) until adapting to type hints recently.
An alternate implementation is adding an `allow_none` or similar kwarg to our getter.
Fixes: https://github.com/qutebrowser/qutebrowser/issues/7901

Handle no selectionmodel on clear selection

---

.mypy.ini
doc/changelog.asciidoc
qutebrowser/browser/webengine/webenginetab.py
qutebrowser/completion/completer.py
qutebrowser/mainwindow/messageview.py
qutebrowser/mainwindow/statusbar/clock.py
qutebrowser/mainwindow/tabwidget.py
qutebrowser/misc/httpclient.py
qutebrowser/misc/ipc.py
qutebrowser/utils/usertypes.py
scripts/dev/misc_checks.py
tests/end2end/fixtures/webserver.py
tests/unit/completion/test_completer.py
tests/unit/misc/test_guiprocess.py
tests/unit/misc/test_ipc.py
tests/unit/utils/test_qtutils.py
tests/unit/utils/usertypes/test_timer.py

I figured I would create a PR for visibility before merging. These are the changes discussed in #8191. I've dropped the changes to CI.yml but left the made-then-reverted changes to ipc.py, in case someone wants to find them again in the future.
This PR adds a sanity check for QTimers firing early do to a Qt but, and logs a warning if it sees that happening. It also adds code into the IPC server to avoid closing a connection early if that did happen, which we were seeing a lot in tests - not sure why, possibly because we are stopping and starting a timer a fair bit in there.
It also switches more places to use our usertypes.Timer subclass of QTimer, instead of QTimer directly, so that we can do the sanity check in more places and logs an incrementing ID from the IPC server so we can better …

Workaround IPC connection closing due to misfiring QTimers on Windows

---

.github/workflows/bleeding.yml
.github/workflows/ci.yml
doc/changelog.asciidoc
qutebrowser/browser/pdfjs.py
qutebrowser/utils/version.py
scripts/dev/ci/docker/Dockerfile.j2
scripts/dev/update_3rdparty.py

* Add polyfill of `Promise.withResolvers` for recent versions of PDF.js.
* Enable some existing PDF.js related tests (in qutescheme.feature) in just a couple of CI environments.
* Fix a unit test for newer PDF.js versions (oh, actually it was the real version parsing code, that the unit test was testing)
* Adapt `update_3rdparty.py` to only import stuff from qutebrowser if needed, due to some weirdness trying to run it in the bleeding edge test setup
I tested the docker container locally and the relevant tests passed.
Closes: #8170

Add Promise.withResolvers polyfill for latest PDF.js version

---

tests/unit/browser/webkit/test_cookies.py

Background:
As part of my work on reproducible builds for openSUSE, I check that software still gives identical build results in the future. The usual offset is +16 years, because that is how long I expect some software will be used in some places. This showed up failing tests in our package build. See https://reproducible-builds.org/ for why this matters.

Fix tests after year 2036

---

misc/userscripts/qute-pass

I have implemented support for Internationalized Domain Names (IDNA). Currently, this only kicks in when the normal 'pass' mode (not 'gopass') is used because I am no gopass user so I could not test this right now.
@cryzed You are listed as script author, would you mind having a look at this?

Add Unicode normalization and IDNA encoding to qute-pass userscript

---

pytest.ini
qutebrowser/completion/completionwidget.py
tests/unit/completion/test_completionwidget.py

Don't call `QTreeView.setModel(None)` as it cases a leak of `QItemSelectionModel`s. Normally the selection models get cleaned up when the model they are linked to is destroyed. But when you set a null model the selection models get linked to a static empty model that lives forever.
Just deleting the model and letting the connections to its `destroyed` signal seems to be an alternate way of resetting the state of the `QTreeView` and deleting the selection models and it does have the problem of creating new `QItemSelectionModel`s with a long lifetime.
I spotted this leak with KDAB's Gammary. Maybe we'll spot more that way later (it gets really slow with many objects though).
I'm not sure how to add a test to ensure these are getting cleaned up since it's being done async. I think the fact …

Make sure we clean up old QItemSelectionModels

---

doc/contributing.asciidoc
tests/conftest.py
tox.ini

The dependancy update job was complaining about something webkit only, and I wanted to be able to check if I broke stuff locally. So I had a crack at getting something setup locally based on the webkit docker container used for CI and took some notes for myself for next time. Let me know if there is a better way to acheive this!
---
My virtualenv I used to run webkit has rotted long ago and I don't remember how I set it up. There is a PyQtWebKit project on PyPI but I don't know who that's published by.
So I figured I would write some notes for myself on using the docker container used for CI instead. I chose to mount the current directory (which is presumably a qutebrowser checkout!) directly into the container instead of cloning it so I could have quicker feedback between making code …

Tips for contributors to run the webkit backend

---

doc/changelog.asciidoc
doc/help/settings.asciidoc
qutebrowser/config/configdata.yml
qutebrowser/misc/pakjoy.py
tests/unit/misc/test_pakjoy.py

Fixes #8257.
Hopefully, the extension can eventually be removed from QtWebEngine.
If not, and until then, this setting disables it, using the existing code in `pakjoy.py`.

Add setting to disable Google Hangouts extension

---

doc/help/configuring.asciidoc
doc/help/settings.asciidoc
qutebrowser/config/configtypes.py
qutebrowser/utils/urlmatch.py

The link to match patterns is broken (404).
This pull request updates the link to point to a working location.

Update link to match patterns documentation

---

doc/install.asciidoc

This flag is vital for the allow-list configuration to be picked up. It should be set globally and `dev-qt/qtwebengine` should be recompiled after it's enabled.
Ref #8313.

📝 Mention `kerberos` USE-flag on Gentoo

---

.github/workflows/bleeding.yml
.github/workflows/ci.yml
doc/changelog.asciidoc
misc/requirements/requirements-tests-bleeding.txt
misc/requirements/requirements-tests.txt
misc/requirements/requirements-tests.txt-raw
pytest.ini
qutebrowser/utils/standarddir.py
scripts/dev/changelog_urls.json
tests/conftest.py
tests/end2end/conftest.py
tests/end2end/fixtures/quteprocess.py
tests/end2end/fixtures/test_quteprocess.py
tox.ini

* Takes a screen capture of the XVFB screen when an e2e test fails
* It won't take any if you aren't using xvfb
* On local runs it'll put the screenshots in $TEMP/pytest-current/pytest-screenshots/
* On GitHub actions it'll attach any screenshots as run artifacts in a zip file
* Handles multiple test workers running in parallel (eg they don't clobber the output dir)
* Only captures the frontmost window if multiple are open
* Will capture screenshots for tests that are rerun by https://github.com/pytest-dev/pytest-rerunfailures, which is not ideal because we don't get error logs for the failed-by-rerun tests
Example: <https://github.com/qutebrowser/qutebrowser/actions/runs/10537503218?pr=8243#:~:text=Produced%20during%20runtime>

Save screenshots when end2end tests fail

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
misc/nsis/install.nsh
misc/nsis/qutebrowser.nsi
scripts/dev/build_release.py

The Qt5 builds for Windows and macOS are failing because the most recent PyQt5-Qt5 release either has issues with them (macOS) or doesn't support them at all (Windows).
We aren't making new Qt5 builds anyhow, so this PR removes those jobs from the nightly workflow and removes Qt5 support from the build scripts too.
I've ran the nightly builds on this branch [here](https://github.com/qutebrowser/qutebrowser/actions/runs/11189136733) and tested both builds in a VM, no issues spotted.
Closes: #8260

Remove support for making Qt5 builds

---

misc/requirements/requirements-tests.txt
tests/end2end/conftest.py
tests/end2end/features/backforward.feature
tests/end2end/features/caret.feature
tests/end2end/features/completion.feature
tests/end2end/features/conftest.py
tests/end2end/features/downloads.feature
tests/end2end/features/editor.feature
tests/end2end/features/hints.feature
tests/end2end/features/history.feature
tests/end2end/features/invoke.feature
tests/end2end/features/javascript.feature
tests/end2end/features/marks.feature
tests/end2end/features/misc.feature
tests/end2end/features/navigate.feature
tests/end2end/features/notifications.feature
tests/end2end/features/open.feature
tests/end2end/features/private.feature
tests/end2end/features/prompts.feature
tests/end2end/features/qutescheme.feature
tests/end2end/features/scroll.feature
tests/end2end/features/search.feature
tests/end2end/features/sessions.feature
tests/end2end/features/spawn.feature
tests/end2end/features/tabs.feature
tests/end2end/features/test_history_bdd.py
tests/end2end/features/test_sessions_bdd.py
tests/end2end/features/urlmarks.feature
tests/end2end/features/utilcmds.feature
tests/end2end/features/yankpaste.feature

fixes #8342
This is untested and purely based on the information provided in the referenced issue.
But it looked pretty straightforward to me so I just used a bit of `git grep` + `vim`-foo to insert the `"""` where I understood they would be required now, adjusting the indentation appropriately.
Let me know if I missed anything or messed up in any other way.

Rewrite `.feature` files to use the `"""` syntax

---

scripts/open_url_in_instance.sh

In POSIX, "echo" flags are undefined so using "echo -n" may not work on all systems. To avoid this, use printf which is more portable and POSIX compliant.

In POSIX sh, echo flags are undefined

---

doc/contributing.asciidoc

Use 'contribute' link to list good-first-issue, as 'easy' label is gone.

docs: update contributing guide with new issue tracker link

---

doc/help/configuring.asciidoc

I stumbled upon <https://www.reddit.com/r/qutebrowser/comments/77eqiq/solarized_or_base16_color_theme_for_qutebrowser/> and <https://bitbucket.org/kartikynwa/dotty2hotty/src/1a9ba9b80f07e1f63b740da5e6970dc5a97f1037/qutebrowser.py> and decided to build that into a proper theme that can be downloaded and applied easily. This PR adds a link to its repo to the docs

Add Solarized theme

---

misc/userscripts/qute-bitwarden

Fixes https://github.com/qutebrowser/qutebrowser/issues/7605 .

Bitwarden: Pass master password in environment variable

---

misc/userscripts/qute-bitwarden

This could be seen as "mac failed" error in the logs.
The issue was that opening a session after it has been cached in qutebrowser caused the cache to be invalidated.
This PR adds "detection" of this situation and forces the user to log in again in such case.
The potentially problematic case is when `mac failed` string would be raised for another reason (that would not require user to log in again). But it's not likely in my opinion.
_I've tested this with the username/password, but I don't use TOTP in Bitwarden so couldn't check it. Logic seems the same though, so should work._  Update: TOTP tested and works fine
Closes https://github.com/qutebrowser/qutebrowser/issues/7607

userscripts: fix qute-bitwarden failing with expired session

---

qutebrowser/browser/commands.py
tests/end2end/features/tabs.feature

Do the modulo by 1 incase self._count() is 0 or negative. 
1, 0 or -1 would all lead to 0 with `% 1`
Starting the browser with 
`qutebrowser --temp-basedir --debug ":tab-move +"` 
now  returns 
`qutebrowser.api.cmdutils.CommandError: Can't move tab to position 1!`
which is also displayed in the statusbar.
Closes #7966

Fix zero division bug in tab-move +

---

qutebrowser/mainwindow/treetabbedbrowser.py
tests/end2end/features/treetabs.feature

Updates `tabs.select_on_remove=prev` for tree tab windows so that the previous sibling is selected, instead of the previous tab in the tab bar. I've found that the selected tab descending to the rightmost leaf node of a tab group when I close a top level tab is never what I want.
(I'm doing a couple of nice-to-have features on the tree tabs branch to motivate myself before I jump into type hints, then writing up proposed setting changes and such I guess. I'll probably merge this myself in a few days, just opening for visibility)
It may have been more respectful of people's preferences and habits to add a "previous-sibling" option for the `tabs.select_on_remove` option, but that would be a fair bit of work. Turning that option into strings and mapping them to QTabBar enum values at the …

Tree tabs: Make `select_on_remove=prev` select previous sibling

---

qutebrowser/browser/commands.py
qutebrowser/mainwindow/tabbedbrowser.py
qutebrowser/mainwindow/treetabbedbrowser.py
qutebrowser/misc/notree.py
tests/end2end/features/treetabs.feature
tests/unit/misc/test_notree.py

Overall this was less eventful than the [tabbedbrowser](https://github.com/qutebrowser/qutebrowser/pull/8122) and [session](https://github.com/qutebrowser/qutebrowser/pull/8084) passes. There is a fair bit of tree specific code in the commands.py class, but it's all fairly clearly delineated from non-tree code. So hopefully the cognitive load for maintainers who don't have tree stuff in their heads isn't too bad.
The main chunks of this PR is reducing the complexity of the `_tree_tab_give()` and calling the `TreeTabbedBrowser.close_tab()` method instead of iterating over the tree and handing the details in commands.py.
My main takeaways:
* Having to support tree specific flags (like `--recursive` and `--sibling`) in methods and commands that may not know anything about tabs is "smelly". …

Feat/8077 remove tree code from commands.py
